wix/react-native-ui-lib

src/components/avatar/index.js

@ethanshar - in order to properly [detox test](https://github.com/wix/detox) some components that use the `Avatar` component, I need a `testID` on the online badge as well. While touching this, I also changed the casing from `testId` to `testID` to be consistent with React Native conventions and so that it'll work with `accessibilityLabel`

add testID to avatar online status

---

src/helpers/AvatarHelper.js
test/spec/helpers/AvatarHelper.spec.js

fix(AvatarHelper): support in spaces at the begin/end of the name when get the initials.

support in spaces at the begin/end of the name when get the initials

---

src/components/card/CardImage.js

It seems, that the `CardImage` component supports `testID` from outside signature, but does not actually use the prop anywhere. :(
_edit: just noticed this is issue no. 42, sorry for squatting this for something so trivial :(_

Proxy testID inside CardImage

---

lib/android/src/main/java/com/wix/reactnativeuilib/textinput/TextInputDelKeyHandlerPackage.java

createJSModules was deprecated in RN 0.47, this fix is backwards compatible.

Deprecate createJSModules

---

src/components/connectionStatusBar/__tests__/index.spec.js
src/components/connectionStatusBar/index.js

replacing deprecated 'change' event and fetch() with their replacements

Migrate ConnectionStatusBar component to RN51

---

demo/src/screens/componentScreens/AvatarsScreen.js
src/components/avatar/index.js

@ethanshar @inbalTish this is needed in order to fix the transparent avatars problem with no initials. When image loading ends, we'll rerendering the avatar component *with* labels; if the avatar is transparent, they will show.

Add callback-props to Avatar component to bind image loading

---

src/components/image/__tests__/index.spec.js
src/components/image/index.js

This causes a warning in react-native: 'Error source.uri should not be an empty string'

Handle Image prop source.uri when it is an empty string.

---

demo/src/screens/componentScreens/FeatureHighlightScreen.js
src/components/featureHighlight/index.js

Feature highlight

---

README.md

The docs link as-is went to some "Coming Soon Page".
This link goes to the actual docs.

Fix Docs link to go somewhere with docs

---

src/assets/Assets.js
src/assets/__tests__/Assets.test.js
src/assets/__tests__/__snapshots__/Assets.test.js.snap
src/assets/icons/index.js
src/assets/images/index.js
src/assets/index.js

For more details see: https://github.com/wix-private/wix-react-native-ui-lib/issues/261
The problem is that [assets/index.js](https://github.com/wix-private/wix-react-native-ui-lib/blob/master/src/assets/index.js) there is reliant on the existing implementation of `Assets.loadAssetsGroup` which stands in my way if I want to rewrite most of the assets' key-values to ES5 getters.
The new implementation helps to avoid `require()` calls to the assets as long as it is possible. This is important for us because it eats up to 200ms of the loading time in WOA or possibly more.

feat: loadAssetsGroup() accepts ES5 getters to facilitate lazy assets requiring

---

src/assets/Assets.js
src/assets/__tests__/Assets.test.js
src/assets/__tests__/__snapshots__/Assets.test.js.snap
src/assets/icons/index.js
src/assets/images/index.js
src/assets/index.js

-------------
For more details see: https://github.com/wix-private/wix-react-native-ui-lib/issues/261
The problem is that [assets/index.js](https://github.com/wix-private/wix-react-native-ui-lib/blob/master/src/assets/index.js) there is reliant on the existing implementation of `Assets.loadAssetsGroup` which stands in my way if I want to rewrite most of the assets' key-values to ES5 getters.
The new implementation helps to avoid `require()` calls to the assets as long as it is possible. This is important for us because it eats up to 200ms of the loading time in WOA or possibly more.

[WIP]  feat: loadAssetsGroup() accepts ES5 getters to facilitate lazy assets requiring

---

src/components/button/index.js
typings/components/button/index.js

This function is throwing error on android api <= 17 because of getComponentDimensions scope.
What i did is bind this context to the function on constructor. Now there is no more error thrown.

Fixed this.setState error for android api under 17

---

index.js

The object spread `{ ...UILIB }` basically results in a full evaluation of all getters in the `./src/index` file.
Can we use an older but more efficient way or take another way to avoid the evaluation? It is quite heavy, about 240ms to execute.

perf: fix performance killer

---

src/components/toast/index.js

Hi there, this is a fantastic UI library that we just started using for our app and we've all been extremely happy with so thank you very much for putting so much care and effort into it!
I just started using the Toast component and came across a situation where I don't want it to be animated at all, so I set `animated={false}` but this results in the following error:
Took a look into the source code and came up with this small solution. The issue it seems is that when the `animated` prop is false, registering the animations is skipped, but then the unregistered animations are still attempted to be used in the `Animated.View` props.
According to [this issue comment](https://github.com/oblador/react-native-animatable/issues/129#issuecomment-352246126) over at react-native-animatible, you …

Fix Toast animated prop

---

demo/src/screens/componentScreens/HintsScreen.js
src/components/hint/index.js

- fix issue with ref's not ready to be measured, throwing an error
- fix issue with the pressable area of the overlay on Android. 
- support passing custom targetFrame instead of wrapping an element

fix issue with overlay not reacting to press on Android

---

demo/src/screens/componentScreens/CardsScreen.js
src/components/card/CardPresenter.js
src/components/card/index.js

I had to fix my recent change in Card component and to always allow overflow to be visible (for Android and iOS). this is in order to support the overflowing of the selection mode. 
regardless, I guess it makes sense to avoid hiding card's overflow content.

support selection mode in Card

---

src/components/tagsInput/index.js

Cloning tags from props to avoid array manipulations by ref that affect the original array (this.props.tags)

Cloning props.tags

---

src/components/inputs/TextField.js

'Failed prop type: Invalid prop 'error' of type 'string' supplied to 'TextArea', expected 'boolean'.

fix for warning:

---

src/components/inputs/TextField.js

Passing lineHeight to android only; Fix expandable maxHeight to display 3 lines max

TextField - Android - LineHeight

---

src/style/__tests__/colors.spec.js
src/style/colors.js

- Fixed exception where ui-lib Colors without tint variants returned original color instead of tinted one.
- Added test coverage

Bug/getColorTint support for single Ui-Lib colors

---

src/commons/modifiers.js
src/components/card/index.js
src/style/borderRadiuses.js
src/style/colors.js

- Refactored modifiers (saves up to 1ms per each base component)
- Do not render selection view on Card component if `selected` prop is undefined

Performance improvements

---

src/components/avatar/index.js

- Moved all props from StyleSheet to class

Fix/Avatar - Refactor to enable dynamic prop change

---

src/components/hint/index.js

this is for the tablet support

support passing screen width for the hint container

---

src/commons/baseComponent.js
src/commons/modifiers.js

`updateModifiers` and `getAlteredModifiersOptions` were doing deep comparisons with prop values, and `children` prop was not excluded, leading to really long execution times (in some cases, 500-5000ms per render).
I excluded children, forwardedRef, style and testID props, these are not required to extract modifiers.

Do not compare unnecessary prop values in modifiers

---

src/helpers/Constants.js

It seems like the value of **`StatusBarManager.HEIGHT`** inside 
> `/react-native-ui-lib/src/helpers/Constants.js`
is always resulting to **`undefined`** when called inside the container stylesheet of the following file: 
> `/react-native-ui-lib/src/screensComponents/modal/TopBar.js`
That's why it's showing up the error height: "NaN" as referenced by this #539 and #536 
You have a problem with the way you are exporting the **setStatusBarHeight** method inside the **Constants.js** file.
Fix: 
```
function setStatusBarHeight() {
let height = 0;
height = isIOS ? 20 : StatusBarManager.HEIGHT;
if (isIOS) {
// override guesstimate height with the actual height from StatusBarManager
StatusBarManager.getHeight(data => (height = data.height));
}
return height;
}
```

Bug Fix: Invariant Violation issue/Malformed calls from JS

---

demo/src/screens/componentScreens/ButtonsScreen.js
src/components/button/index.js

Adding onOrientationChange event to trigger re-render on tablets when 'fullWidth' is passed.

Button - onOrientationChange re-render

---

src/interactableComponents/drawer/Swipeable.js

This component should be deprecated soon. For now this will get rid of Reace lifecycle hooks warning

swipeable: mark componentWillUpdate as unsafe

---

src/interactableComponents/drawer/index.js

Fixes the following warning:
```
Warning: Failed prop type: Invalid prop `accessibilityActions[0]` of type `object` supplied to `View`, expected `string`.
in View (at drawer/index.js:322)
in Drawer (at list-item-drawer-manager.tsx:48)
```
Only `label` and `name` are allowed (as per https://facebook.github.io/react-native/docs/accessibility#accessibility-actions)

fix drawer prop warning

---

android/app/build.gradle
demo/src/screens/componentScreens/AvatarsScreen.js
src/components/image/index.js

Support rounded gif images (image with border-radius) on Android.

hide overflow for gif images on Android

---

demo/src/screens/incubatorScreens/TabControllerScreen/index.js
src/components/carousel/index.js
src/incubator/TabController/PageCarousel.js
src/incubator/TabController/TabPage.js
src/incubator/TabController/index.js

In general, I added the option for the user to wrap `TabPage`s with `PageCarousel` component.
this will change the behavior of the TabController to render the pages as carousel instead of single page each time.
I made some changes in `Carousel` component to allow it to accept `Animated.event` for `onScroll` instead of a function. This way I can intercept the carousel offset position to use in the TabController.

Adding carousel support to tab controller

---

demo/src/screens/MenuStructure.js
demo/src/screens/componentScreens/PanDismissibleScreen.js
demo/src/screens/componentScreens/index.js
src/components/panningViews/asPanViewConsumer.js
src/components/panningViews/panDismissibleView.js
src/components/panningViews/panListenerView.js

Re-introduce PanDismissibleView (add screen and make small improvement)
PanListenerView - now handles clickable view better (Android)

Re-introduce PanDismissibleView

---

src/components/inputs/TextField.js

Allow passing all Image source propTypes to rightButtonProps' iconSource prop (issue #615)

TextField - rightButtonProps's iconSource propTypes

---

src/components/button/index.js
src/components/inputs/TextField.js
src/components/inputs/__tests__/TextField.spec.js

We had some issues (only in public) with the TextField colors 
I went over it and decided to do a little refactor there (also refactor the tests) 
In general, the logic should make more sense now and follows closely are UX guidelines

Fix TextField color by state logic

---

src/components/dateTimePicker/index.js

Issues fixed: 
- iOS: Component used to trigger onChange for each change before pressing done
- Both: Component did not trigger onChange when pressing done
- Both: onChange did not contain the selected date argument
After fixes the component sends only one event onChange for both platforms containing the selected date when the selection is confirmed by pressing done/checkmark.

Fix/DateTimePicker onChange

---

src/components/dateTimePicker/index.js

add @react-native-community/datetimepicker specific Props for DateTimePicker

add @react-native-community/datetimepicker specific Props for DateTimePicker

---

jest-setup.js
package.json
src/components/connectionStatusBar/index.js

Since `NetInfo` moved from `react-native` to `@react-native-community/netinfo`, the component `ConnectionStatusBar` is not working anymore.

Fix ConnectionStatusBar NetInfo

---

src/components/inputs/TextField.js
src/components/slider/index.js
src/components/tabBar/TabBarItem.js

When the state (disable, selected etc.) of a component is changed dynamically the `accessibilityState` prop should change accordingly and not be set only once in the first render.

fix accessibilityState in case of dynamic state change

---

src/components/inputs/TextField.js

that caused the issue that made expandable input to not work (e.g Pickers)

avoid passing to TextField accessibilityStates on Android

---

generatedTypes/commons/new.d.ts
generatedTypes/components/view/index.d.ts
src/commons/asBaseComponent.tsx
src/commons/forwardRef.tsx
src/commons/new.ts
src/components/view/index.tsx

in order to import with destruct all `commons` components I created a a separate file with the relevant components (that were already migrated to ts)

create commons/new.ts for typescript migration

---

src/helpers/Constants.ts

Fix deprecated code
- RN 0.62.0
- `AccessibilityInfo.fetch` is deprecated, Changed to `AccessibilityInfo.isScreenReaderEnabled`
- https://reactnative.dev/blog/#deprecations

Fix deprecated code

---

src/commons/modifiers.ts
src/components/text/index.tsx

Changed the typings of the `Text` component from `interface` to `type`.
Changed the `CustomModifier` type to be strictly boolean and integrated it with `ColorsModifiers` and `TypographyModifiers` via `Union` type rather than `Intersection` type.

fix custom modifier types to be strictly boolean

---

demo/src/screens/componentScreens/TagsInputScreen.js
src/components/tagsInput/index.js

added new onTagNotValidate prop for the user to write is validation error message, and UI support as asked here: [https://app.zeplin.io/project/5934252871cf6fc586d47aeb/screen/5e41125dfaf8a8949a886bf8](url)

Added validation error feature to TagsInput

---

demo/src/screens/componentScreens/TextFieldScreen/BasicTextFieldScreen.js
src/components/inputs/TextField.js

Left some parts in comment on purpose.

Support rendering prefix in TextField

---

src/components/inputs/TextField.js

- Fixed floating placeholder iOS conditional Y interpolation value which caused ui misalignments within iOS TextFields. This deviation is not needed and is the cause of ui bugs. 
(Also, part of the solution for WOAUILIB-247)

Fix/TextField - Unneeded iOS multiline spacing

---

generatedTypes/components/radioButton/RadioButton.d.ts
src/components/radioButton/RadioButton.tsx
src/components/radioButton/asRadioGroupChild.tsx

I noticed that the recent change in RadioButton cause an issue with the generated typings of the component. 
So I reverted the order to the original order (the one that broke the theme) 
I fixed the theme issue by hoisting the static displayName member in asRadioGroupChild

hoist static members in asRadioGroupChild HOC

---

demo/src/screens/componentScreens/DateTimePickerScreen.js
src/components/inputs/TextField.js
src/components/picker/index.js

- Removed unneeded Picker value default typography. TextField defaults to that same typography.
In addition, this is a blocker for (WOAUILIB-816).
- Updated TextField's rightIcon bottom padding condition
- Updated DateTimePicker example screen.

Fix/Picker + TextField Ui fixes

---

src/components/picker/NativePicker.js

NativePicker - remove panning (it was enabled by mistake in the Dialog migration)

NativePicker - remove panning

---

generatedTypes/components/radioButton/RadioButton.d.ts
generatedTypes/components/radioButton/RadioGroup.d.ts
generatedTypes/components/radioButton/RadioGroupContext.d.ts
src/components/radioButton/RadioButton.tsx
src/components/radioButton/RadioGroup.tsx
src/components/radioButton/RadioGroupContext.ts
src/components/radioButton/asRadioGroupChild.tsx

- Adding number type to value prop (WOAUILIB-791)

Feat/RadioButton - value type update

---

src/components/inputs/BaseInput.js

* Passing `validate={[...]}`, makes that input **required** and adds and additional `*` to placeholder.
* Fixed wrong parentheses which always returned undefined and always made input **required**.

[Bug] Passing validate prop to input as array makes that input required

---

src/commons/__tests__/modifiers.spec.js
src/commons/modifiers.ts

The issue was that _.isEmpty returns true on numbers 
and the modifiers container also numbers values (for borderRadius for example)

fix issue with how we clean modifiers empty values

---

src/components/inputs/BaseInput.js

* Passing `validate={[undefined, undefined]}` throws red screen;
* When having feature toggles and code that looks like this:
```
validate={[
condition1 ? validateFunc1 : undefined,
condition2 ? validateFunc2 : undefined
]}
```
The only solution is to use `() => true`, instead of `undefined`
* Added handling of array of undefined;
**This only handles the situation where mutliple false returning values are the same**

[Feature] Added handling of array of undefined validations

---

demo/src/screens/componentScreens/DrawerScreen.js
src/components/drawer/Swipeable.tsx
src/components/drawer/index.js

Add a full swipe to the right.
Add actions (openLeft, openLeftFull, openRight, openRightFull) to Drawer component to achieve https://jira.wixpress.com/browse/RST-3534 functionallity

Swipeable drawer add open actions

---

eslint-rules/lib/rules/typography-deprecation.js

typography-deprecation - JSX should use short version (no Typography prefix) - fix

typography-deprecation - JSX should use short version

---

.eslintrc.js
package.json

See https://reactjs.org/docs/hooks-reference.html#usecallback.
See the "Note" at the end:
> We recommend using the exhaustive-deps rule as part of our eslint-plugin-react-hooks package. It warns when dependencies are specified incorrectly and suggests a fix.

Add eslint-plugin-react-hooks (per React's recommendation)

---

src/components/slider/index.js

`minimumTrackTintColor` from theme (default config) was not working properly.
Fixed `maximumTrackTintColor` as well, and changed from `this.styles` to `styles` since it was no longer needed.

Slider - fix track to properly bring theme (minimum\maximum) color

---

demo/src/screens/componentScreens/TextFieldScreen/BasicTextFieldScreen.js
src/components/inputs/TextField.js

- Support rendering `leadingIcon` prop
- Prevent rendering of `prefix` or `leadingIcon` with `floatingPlaceholder` 
(WOAUILIB-499)

Support rendering leading Icon to TextField 

---

src/commons/__tests__/baseComponent.spec.js
src/commons/__tests__/modifiers.spec.js
src/commons/modifiers.ts

This allows users to pass various typography modifiers together and get a combination of presets
For instance 
```
<Text text40 bold italic />
```

Fix #826 | Support merging multiple typography modifiers on a component

---

generatedTypes/commons/asBaseComponent.d.ts
generatedTypes/components/button/index.d.ts
generatedTypes/components/card/CardImage.d.ts
generatedTypes/components/card/CardSection.d.ts
generatedTypes/components/card/index.d.ts
generatedTypes/components/checkbox/index.d.ts
generatedTypes/components/image/index.d.ts
generatedTypes/components/radioButton/RadioButton.d.ts
generatedTypes/components/radioButton/RadioGroup.d.ts
generatedTypes/components/text/index.d.ts
generatedTypes/components/touchableOpacity/index.d.ts
generatedTypes/components/view/index.d.ts
generatedTypes/incubator/TouchableOpacity.d.ts
generatedTypes/index.d.ts
src/components/button/index.tsx
src/components/card/CardImage.tsx
src/index.ts
typings/commons/index.d.ts

Fix button static values and other small type fixes

---

generatedTypes/components/view/index.d.ts
src/components/view/index.tsx
typings/components/Carousel.d.ts

Add prop types:`backgroundColor` to `View` and `animate` to `Carousel`

---

src/components/animatedScanner/index.js

For Animated Scanner, there was an Animated method where useNativeDriver was not specified
Also, animating left is not supported natively so, I set useNativeDriver to be false

Animated Scanner - useNativeDriver required to be specified

---

lib/ios/reactnativeuilib.xcodeproj/project.pbxproj
lib/ios/reactnativeuilib/keyboardinput/rctcustomInputcontroller/RCTCustomInputControllerTemp.m
lib/ios/reactnativeuilib/keyboardinput/rctcustomInputcontroller/RCTCustomKeyboardViewControllerTemp.h
lib/ios/reactnativeuilib/keyboardinput/rctcustomInputcontroller/RCTCustomKeyboardViewControllerTemp.m
lib/package.json

We want to allow for the libs we imported to co-exist until we migrate fully to our internal keyboards (here), so we have to rename to temp, it seems this was missed (hopefully nothing else)

KeyboardInput - rename RCTCustomKeyboardViewController --> RCTCustomKeyboardViewControllerTemp

---

src/components/tabController/TabBar.js

Fix TabController issue on Android+RTL with focusing selected item

---

typings/components/Carousel.d.ts
typings/components/PageControl.d.ts

- 'limitShownPages' does not exist in type 'PageControlProps'
- 'key' does not exist in type 'PageControlProps'
- Property 'pageControlPositions' does not exist on type 'typeof Carousel'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wix/react-native-ui-lib/856)

TS/fix carousel-related typing errors

---

demo/src/screens/componentScreens/DrawerScreen.js
src/components/drawer/Swipeable.tsx
src/components/drawer/index.js

Fix for trigger event on release instead of just threshold

Drawer - trigger onToggleSwipeLeft on releases

---

demo/src/screens/MainScreen.js
demo/src/screens/SettingsScreen.js

Added support for the demo screen to have injected UI as extra settings.

Demo screen support injected ui

---

src/components/inputs/TextField.js

TextField's right element (icon and button) position fixed (center).
Behaviour changed - right element keeps the starting position on multiline TextField.

TextField element positioning to be centered with the TextField.

---

demo/src/screens/componentScreens/TextFieldScreen/InputsScreen.js
src/components/inputs/TextField.js

TextField component now accepts right button accessibilityLabel

Added accessibility prop to TextField's right button

---

src/components/hint/index.js
src/components/modal/index.js

add testID on the Modal that renders when onBackgroundPress prop sent in Hint

add testID

---

generatedTypes/components/button/index.d.ts
generatedTypes/components/card/index.d.ts
generatedTypes/components/touchableOpacity/index.d.ts
src/components/touchableOpacity/index.tsx

WOAUILIB-1006
Today our TouchableOpacity's `onPress` callback support passing back the props the user pass. 
This is very useful cause it helps avoid passing inline callback 
So instead of doing this 
```
<TouchableOpacity someValue={1}  onPress={(props) => doSomething(props.someValue)} />
```
You can do
```
<TouchableOpacity someValue={1}  onPress={doSomething} />
...
doSomething({someValue}) => {...}
```
After migrating to TS this pattern has become an issue, because when a user pass an arbitrary prop like `someValue` typescript throws an error. 
The new `customValue` prop purpose is to have a dedicate prop for passing these values.

Declare customValue type for passing an arbitrary value to touchables

---

src/components/textField/index.js

Fix overflow line break on special characters - ? ! / } - due to 'textAlign' attribute.
Tested with RTL text as well to confirm support.

TextField - Fix overflow line break

---

demo/src/screens/componentScreens/DrawerScreen.tsx
src/components/drawer/Swipeable.tsx

Passing the testID to the appropriate Drawer's subcomponent; Adding testIDs to demo screen

Drawer - testID

---

src/components/textField/index.js

*  Currently coming from a valid state to an error state replaced the top placeholder label with an error message, and moves the whole `TextField` down because topLabel receives padding that is 1 pixel higher than default.
* Reduced marginBottom height of topLabel by 1.

Reduce padding of top label margin bottom by 1 pixel

---

src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/button/index.tsx

Button is now support RTL which allows users to flip icon inside button.

Fix/button RTL support

---

src/components/tabBar/index.tsx

With the move to typescript, condition on an optional number type, like index, will fail when has the value of 0 (zero) since that is equal to false/undefined. 
Removing the optional for the number type will error if undefined is passed to it and remove the need for the value chack while passing when passing the value 0.

Fix - first item selection is not being updated

---

demo/src/screens/componentScreens/TextFieldScreen/InputsScreen.js
src/components/textField/index.js

Adding 'errorColor' prop to allow customizing the error message text color.
resolves #911

TextField - 'errorColor' prop

---

demo/src/screens/componentScreens/FloatingButtonScreen.tsx
src/components/floatingButton/index.tsx

FloatingButton - Turning component to a fully controlled component by removing state management.
No breaking changes!

FloatingButton - Remove UNSAFE method

---

generatedTypes/incubator/TextField/index.d.ts
generatedTypes/incubator/TextField/useFieldState.d.ts
src/incubator/TextField/index.tsx
src/incubator/TextField/useFieldState.ts

I realize we can accomplish the functionality of `withFieldState` HOC with a hook.
Since it doesn't affect directly the render output and it just provides logic and data and because the whole TextField is implemented using function components, there's no reason not to use hooks. 
Also, in this PR I declare the "validate" typings in the main component as well (even though it's repetitive) just for react-docgen

TextField - replace withFieldState HOC with useFieldState hook

---

demo/src/screens/componentScreens/PickerScreen.js
src/components/picker/__tests__/index.spec.js
src/components/picker/index.js

Removing UNSAFE method.
Wrapping with `asBaseComponent` HOC.
Changing to extend React's PureComponent.
Adding export for tests.
Fixing tests component import.
Fixing 'custom modal' example.

Picker - Remove UNSAFE method

---

src/components/radioButton/RadioGroup.tsx

Using now `getDerivedStateFromProps` instead of `UNSAFE_componentWillReceiveProps`

RadioGroup - Replace unsafe method with getDerivedStateFromProps

---

src/components/tabController/TabBarItem.js

Support passing custom style to TabController TabBarItem
Support passing custom `style` prop in TabController.TabBar `items`

Support passing custom style to TabController.TabBarItem

---

src/commons/modifiers.ts
src/components/picker/PickerDialog.android.js
src/components/picker/PickerDialog.ios.js

- There was an issue in PickerDialog components (ios and android) with the usage of `Dialog.extractOwnProps` due to the migration to `asBaseComponent` 
- I added a new methods in `Modifiers` class - `extractComponentProps` which should replace `extractOwnProps`
Fix issue with Picker when passing the `useNativePicker` prop an error was thrown.

Change how we extract a component props

---

demo/src/index.js
demo/src/screens/MenuStructure.js
demo/src/screens/componentScreens/ChipsInputScreen.js
demo/src/screens/componentScreens/index.js
eslint-rules/tests/component_deprecation.json
generatedTypes/index.d.ts
src/components/chipsInput/__tests__/index.spec.js
src/components/chipsInput/index.js
src/components/index.js
src/components/maskedInput/index.js
src/components/tagsInput/index.js
src/index.js
src/index.ts
typings/components/ChipsInput.d.ts
typings/components/index.d.ts

Renaming TagsInput to ChipsInput
Renaming TagsInput to ChipsInput

Renaming TagsInput to ChipsInput

---

generatedTypes/index.d.ts
src/index.ts

There was an issue with `Constants` typings because how we exported it
Fix `Constants` typings

Fix Constants typings by exporting it correctly

---

demo/src/screens/componentScreens/CardScannerScreen.js
src/components/animatedScanner/index.js

AnimatedScanner - adding 'containerStyle' prop.
In preparation for the ProgressBar style change, this will allow using AnimatedScanner to achieve the old ProgressBar style.
AnimatedScanner - adding 'containerStyle' prop.

AnimatedScanner - adding 'containerStyle' prop

---

demo/src/demoApp.js
demo/src/screens/animationScreens/ListAnimationsScreen.js
demo/src/screens/componentScreens/BasicListScreen.js
demo/src/screens/componentScreens/ContactsListScreen.js
demo/src/screens/componentScreens/ConversationListScreen.js
src/components/badge/index.tsx
src/components/button/index.tsx
src/components/image/__tests__/index.spec.js
src/components/loaderScreen/index.js
src/components/picker/PickerItem.js
src/components/stateScreen/index.js
src/components/stepper/style.js
src/components/tagsInput/index.js
src/components/toast/index.js
src/components/touchableOpacity/index.tsx
src/style/colors.ts
src/style/colorsPalette.ts
src/style/themeManager.ts
uilib-docs/src/pages/index.js

ThemeManager - Adding deprecation warning for 'setTheme()' to start the deprecation process before removing the method on the next major version.
Removing all usages of ThemeManager global constants - 'primaryColor', 'CTA', 'titleColor' etc.
ThemeManager - Starting deprecation process for 'setTheme()' method.

ThemeManager - Adding deprecation warning for 'setTheme()'.

---

src/helpers/Constants.ts

I Simplified the logic for setting statusBarHeight constants. 
I noticed that the previous logic created flakiness with the layout of `Modal.TopBar` component. 
My guess is that in earlier versions of react-native it was more complicated to extract this value, but now
It seems like `NativeModules.StatusBarManager` initially return the correct value for all platforms (checked iPhoneX, 8, iPad and Android) 
Anyway, kept the old logic in a comment in case I missed something and in case we'll get a weird issue in the near future. 
Fix statusBarHeight constant value and how it affect Modal.TopBar layout.

Update statusBarHeight calculation

---

demo/src/screens/componentScreens/PickerScreen.js
src/components/picker/PickerItem.js
src/components/picker/index.js

- Added migration warning for stop using object for Picker's value prop. 
- Added migration warning for passing value and label props separately for Picker.Item
- Added an example for a migrated picker in PickerScreen to verify we support correctly the new API and still doesn't break the old API (by keeping the old examples) 
Migrate Picker component's API. Should pass only string|number for `value` prop 
Migrate Picker.Item component's API. Should pass value and label props separately.

Add appropriate deprecate warnings for picker API

---

package.json
tsconfig.build.json

Currently our JS files that are generated from TS files are creates with ES5 syntax which makes it very painful when investigating issues in private uilib when from node_modules. 
This PR fix how we generate the JS files and use `tcs` for that instead of `babel`. 
Change generated JS files from TS to have ES6 syntax.

Use TS compiler to generate JS files

---

typings/components/ProgressBar.d.ts

There's no `progress` type in [ProgressBar.d.ts](https://github.com/wix/react-native-ui-lib/blob/7a4627c757359b9fced5d361b197c1f257d18357/typings/components/ProgressBar.d.ts#L6). This PR fixes this issue.
Add `progress` type for ProgressBar component

Add progress type for ProgressBarProps

---

src/components/carousel/index.js

Do not notify the user (`onPageChange`) for the fake page, affects `autoscroll={true}` (on Android)
Fix autoscroll on Android notifies (onPageChange) on a page that does not exist.

Do not notify the user for the fake page (autoscroll on Android)

---

demo/src/screens/componentScreens/KeyboardAwareScrollViewScreen.js
src/components/KeyboardAwareScrollView/KeyboardAwareBase.js
src/components/KeyboardAwareScrollView/KeyboardAwareFlatList.js
src/components/KeyboardAwareScrollView/KeyboardAwareListView.js
src/components/KeyboardAwareScrollView/KeyboardAwareScrollView.js
src/components/KeyboardAwareScrollView/index.js
src/components/index.js
src/index.js

KeyboardAwareFlatList - add new type to the KeyboardAware view and deprecate KeyboardAwareListView
I think we need to do some more refactoring around this (fix warnings and code duplications), but maybe in another task\PR.
Move from KeyboardAwareListView to KeyboardAwareFlatList

Move from KeyboardAwareListView to KeyboardAwareFlatList

---

generatedTypes/index.d.ts
src/index.ts

Export all common infra typings
Export all common infra typings

Export all modifiers and other common typings

---

src/components/floatingButton/index.tsx

Bug: floatingButton component shows briefly when visible=false.
Fix: update the firstLoad logic to keep `this.firstLoad` as true, until the first time that `visible` is set to true
Fix floatingButton visibility bug when visible is initialised to false

fix firstLoad logic in floatingButton

---

generatedTypes/components/dialog/OverlayFadingBackground.d.ts
src/components/dialog/OverlayFadingBackground.tsx
src/components/dialog/index.tsx

Dialog - RN63 broke Modal's onDismiss method, this fixes our API
We're somewhat relying here on the fact that the fade animation takes longer (400) than the dismiss animation (300), although when I've tested it seemed to work with the same length on animation.
Dialog - RN63 broke Modal's onDismiss method, this fixes our API

Dialog - RN63 broke Modal's onDismiss method, this fixes our API

---

src/components/dateTimePicker/index.js

Add dateFormatter prop to dateTimePicker
Add dateFormatter prop to dateTimePicker

add dateFormatter prop to dateTimePicker

---

demo/src/screens/componentScreens/ChipsInputScreen.js
src/components/chipsInput/__tests__/index.spec.js
src/components/chipsInput/index.js

ChipsInput - Moving to 'asBaseComponent' HOC and removing UNSAFE method.
ChipsInput - Removing UNSAFE method.

ChipsInput - Removing UNSAFE method

---

src/commons/asBaseComponent.tsx

Stop using `getDerivedStateFromProp` in asBaseComponent to calculate modifiers. 
Move modifiers calculation to the render method where we can access the component's context
Fix issue with modifiers support based on context

Calc modifiers in render methods so we can access context

---

generatedTypes/services/LogService.d.ts
src/services/LogService.ts

LogService - fix typings
LogService - fix typings

LogService - fix typings

---

demo/src/screens/componentScreens/CardsScreen.tsx
demo/src/screens/componentScreens/EmptyStateScreen.js
demo/src/screens/componentScreens/ExpandableSectionScreen.tsx
demo/src/screens/componentScreens/OverlaysScreen.tsx
generatedTypes/commons/new.d.ts
generatedTypes/components/card/CardImage.d.ts
generatedTypes/components/card/CardSection.d.ts
generatedTypes/components/floatingButton/index.d.ts
generatedTypes/hooks/index.d.ts
generatedTypes/hooks/useToggleValue/index.d.ts
src/components/card/CardImage.tsx
src/components/card/CardSection.tsx
src/components/stateScreen/index.js
typings/components/StateScreen.d.ts

Starting deprecation process for CardImage, CardSection, StateScreen with deprecation warning and support for old and new props.
CardImage, CardSection, StateScreen - Adding props deprecation warnings.

Props deprecations - CardImage, CardSection, StateScreen

---

src/components/checkbox/index.tsx

render checkbox container only if there's label.
I didn't add `containerStyle` to the checkbox style itself since it apply the styling twice
fix checkbox alignment bug

render checkbox container only if there's label

---

src/components/animatedImage/index.js

This will fire the onLoad prop on the Image onLoad
Fire onLoad event for AnimatedImage

Invoke onLoad prop on onLoad

---

demo/src/screens/componentScreens/PickerScreen.js
src/components/picker/PickerItem.js
src/components/picker/index.js

Add a migrate prop to allow migrating manually to the new Picker API
Add a migrate prop to allow migrating manually to the new Picker API

Add a migrate prop to Picker component for migrating to the new API

---

src/components/picker/PickerItem.js

Fix issue with `Picker.Item` ignores `renderItem` prop
Fix issue with `Picker.Item` ignores `renderItem` prop

Fix issue #1052 - PickerItem ignore renderItem prop

---

src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/image/index.tsx

Fix issue for Android on rn63 - when passing null as tintColor to an Image, the image is not displayed
Fix issue for Android on rn63 - when passing null as tintColor to an Image, the image is not displayed

Image's tintColor with null value doesn't display on Android RN63

---

generatedTypes/commons/UIComponent.d.ts
src/commons/UIComponent.ts
src/commons/asBaseComponent.tsx

Support ErrorBoundary in asBaseComponent
Support ErrorBoundary in asBaseComponent

support ErrorBoundary in asBaseComponent

---

generatedTypes/components/drawer/index.d.ts
generatedTypes/components/floatingButton/index.d.ts
src/components/drawer/index.tsx
src/components/floatingButton/index.tsx

add testID prop to Drawer & FloatingButton
add testID prop to Drawer & FloatingButton

add testID prop to Drawer & FloatingButton

---

demo/src/screens/componentScreens/TabBarScreen.tsx
src/components/tabBar/TabBarItem.tsx
src/components/tabBar/index.tsx

Reverts wix/react-native-ui-lib#1040
@Inbal-Tish 
Please re-submit this PR after fixing TS errors

Revert "TabBar refactor"

---

uilib-docs/src/components/navbar/item.js

Docs - make some groups (i.e. Incubator) not clickable (not links) since they have no docs
Docs - make some groups (i.e. Incubator) not clickable (not links) since they have no docs (fixes #1042)

Docs - make some groups (i.e. Incubator) not clickable (not links) since they have no docs

---

generatedTypes/components/checkbox/index.d.ts
src/components/checkbox/index.tsx

Alternative style for checkbox that wasn't possible with basic styling and theming alone.
Added optional boolean outline prop.  The checkbox acts normal when false and by default.

checkbox variant - outline

---

.eslintrc.js

configure 'max-len'; turn off 'jsx-no-bind'
eslint - configure 'max-len'; turn off 'jsx-no-bind'

configure 'max-len'; turn off 'jsx-no-bind'

---

generatedTypes/components/scrollBar/index.d.ts
generatedTypes/index.d.ts
src/components/scrollBar/index.tsx
src/index.ts

ScrollBar - migrate to TS.
ScrollBar - migrate to TS.

ScrollBar - TS migration

---

demo/src/screens/componentScreens/BadgesScreen.tsx

Fix icon size in the badges example screen
Fix icon size in the badges example screen

Fix icon size in badges example screen

---

demo/src/screens/componentScreens/ScrollBarScreen.tsx
generatedTypes/components/scrollBar/index.d.ts
src/components/scrollBar/index.tsx
src/components/tabBar/index.tsx

Fix refactor bugs.
TabBar - fix refactor bugs

bug fixes for TabBar refactor

---

generatedTypes/components/textField/TextFieldMigrator.d.ts
src/components/textField/TextFieldMigrator.tsx
src/index.js

Create TextFieldMigrator to migrate users from the old TextField implementation to the new. 
Start migrating to our new TextField implementation by passing the `migrate` prop.

Create a middleware TextField migrator

---

src/components/dateTimePicker/index.js

DateTimePicker - adding 'headerStyle' prop to adjust iOS dialog header style.
Solves issue #1014 
DateTimePicker - adding 'headerStyle' prop to adjust iOS dialog header style.

DateTimePicker - adding 'headerStyle' prop

---

demo/src/screens/componentScreens/IncubatorTextFieldScreen.tsx
generatedTypes/incubator/TextField/index.d.ts
generatedTypes/incubator/TextField/useFieldState.d.ts
generatedTypes/incubator/TextField/usePreset.d.ts
src/incubator/TextField/index.tsx
src/incubator/TextField/useFieldState.ts

Add missing functionality for Incubator.TextField that we had in TextField - onChangeValidity
Incubator.TextField now supports `onChangeValidity` callback for when field valid state has changed.

Add missing functionality for Incubator.TextField

---

demo/src/screens/componentScreens/CardsScreen.tsx

CardsScreen - fix backgrounds and remove obsolete examples
CardsScreen - fix backgrounds and remove obsolete examples

CardsScreen - fix backgrounds and remove obsolete examples

---

src/components/hint/index.js

- Remove usage of AniamtableManger from our Hint component
- Use Colors.primary instead of Colors.blue30 
* Replace usage of `react-native-animatable` from our Hint component with our own implementation

Stop using AnimatableManager in Hint

---

src/components/floatingButton/index.tsx

Remove react-native-animatable usage in FloatingButton component, replace with regular animation using Animated
Remove dependency of `react-native-animatable` in our FloatingButton component

Remove animatable from FloatingButton component

---

typings/components/ChipsInput.d.ts

*Enter description to help the reviewer understand what's the change about...*
Fix typing of `ChipsInputProps` by extending `TextInputProps`
*Add a quick message for our users about this change*
Fix `ChipsInput` prop typings

fix prop types for ChipsInput props

---

src/components/featureHighlight/index.js

FeatureHighlight was missing the useNativeDriver prop which now is mandatory by react-native
Fix issue with FeatureHighlight component not using useNativeDriver flag

Fix #1133 - FeatureHighlight component doesn't use useNativeDriver

---

generatedTypes/components/radioButton/RadioGroup.d.ts
src/components/radioButton/RadioGroup.tsx

typescript - RadioGroup - support testID (and other View props)
typescript - RadioGroup - support testID

typescript - RadioGroup - support testID

---

generatedTypes/components/actionBar/index.d.ts
generatedTypes/components/avatar/index.d.ts
generatedTypes/components/badge/index.d.ts
generatedTypes/components/carousel/index.d.ts
generatedTypes/components/modal/index.d.ts
generatedTypes/components/tabController/PageCarousel.d.ts
generatedTypes/components/tabController/TabBarItem.d.ts
generatedTypes/components/tabController/TabPage.d.ts
generatedTypes/components/tabController/index.d.ts
src/components/actionBar/index.tsx
src/components/avatar/index.tsx
src/components/badge/index.tsx
src/components/card/CardImage.tsx
src/components/card/CardSection.tsx
src/components/card/index.tsx
src/components/carousel/index.tsx
src/components/floatingButton/index.tsx
src/components/modal/TopBar.tsx
src/components/modal/index.tsx
src/components/pageControl/index.tsx
src/components/panningViews/panListenerView.tsx
src/components/panningViews/panResponderView.tsx
src/components/tabController/PageCarousel.tsx
src/components/tabController/TabBar.tsx
src/components/tabController/TabBarItem.tsx
src/components/tabController/TabPage.tsx
src/components/tabController/index.tsx

Fix various broken example screen links in our docs 
Fix various broken example screen links in our docs

Fix broken example screens links

---

generatedTypes/hooks/useScrollToItem/index.d.ts
src/components/tabController/TabBar.tsx
src/hooks/useScrollToItem/index.ts

useScrollToItem - add offsetType to statics
Fix dynamic focusing when there's inner/outer spacing
useScrollToItem - add offsetType to statics + fix dynamic focusing when there's inner/outer spacing

useScrollToItem - add offsetType to statics

---

src/components/chipsInput/__tests__/index.spec.js
src/components/chipsInput/index.js

There is an issue in react-native lib.  https://github.com/facebook/react-native/issues/29689 
onChangeText is called before onKeyPress on Android - state.input are empty when deleting last character. Debounce fixes execution order.
onKeyPress is called properly for backspace button. No need additional event listener.
`DeviceEventEmitter.addListener('onBackspacePress', this.onKeyPress);	` 
Found out this caused double onKeyPress events.
Fixed ChipsInput backspace tag removal issue on Android.

ChispInput backspase fix for Android

---

lib/components/Keyboard/KeyboardTracking/KeyboardAwareInsetsView.js
markdowns/foundation/modifiers.md
markdowns/getting-started/v5.md
src/components/animatedScanner/index.js
src/components/slider/ColorSliderGroup.js
src/components/slider/GradientSlider.js
src/components/slider/index.js
src/components/stackAggregator/index.js
src/components/stepper/index.js

Fix some broken links in docs
Fix some broken links in docs

Fix broken links in docs

---

generatedTypes/style/shadows.d.ts
src/style/shadows.ts

There's a mismatch between our private and publish shadows presets. 
It create issues with tests in private modules and also we can't use the right presets in our public components
Update Shadows presets with `Shadows.sh10`, `Shadows.sh20`, `Shadows.sh30`

Add our private shadows presets in OS

---

generatedTypes/components/carousel/index.d.ts
src/components/carousel/index.tsx

*Whilst browsing the documentation I noticed there was a typo on the following page: https://wix.github.io/react-native-ui-lib/docs/Carousel/
* Updating the typo of `"screed"` and correcting it to `"screen"`

[Typo] "screed" should be "screen"

---

demo/src/screens/componentScreens/BadgesScreen.tsx
generatedTypes/components/badge/index.d.ts
src/components/badge/index.tsx

Support passing custom element to Badge component.
Add examples to the Badge example screen.
Support passing custom element to Badge component.

Feat/support customElement in Badge

---

src/components/avatar/index.tsx

Add missing accessibility typing to `Avatar` component. 
Fix accessibility typings to `Avatar` component

Add accessibility props to avatar component

---

src/components/textField/TextFieldMigrator.tsx

Show migration warning only on mount
Fix TextField migration to show warnings only once, on mount

Show migration warning only on mount

---

demo/src/screens/nativeComponentScreens/keyboardInput/KeyboardInputViewScreen.js
lib/components/Keyboard/KeyboardInput/CustomKeyboardView.ios.js
lib/components/Keyboard/KeyboardTracking/KeyboardTrackingView.ios.js

CustomKeyboard had a fix some time ago, to remove the safe area (annoying grey part at the bottom).
In order to avoid migration back at the time, I've set `useSafeArea` default value to `true` although other UILib components set it to `false` by default. 
In this PR it fixed, and moved to be `false` by default
When using `KeyboardAccessoryView`, `useSafeArea` default value has changed from `true` to `false`, to match all other UILib's api that by default it is `false`.

Changed `useSafeArea` default value

---

demo/src/index.js
demo/src/screens/MenuStructure.js
demo/src/screens/componentScreens/CarouselVerticalScreen.tsx
demo/src/screens/componentScreens/index.js
generatedTypes/components/carousel/CarouselPresenter.d.ts
generatedTypes/components/carousel/index.d.ts
generatedTypes/components/carousel/types.d.ts
src/components/carousel/CarouselPresenter.ts
src/components/carousel/__tests__/CarouselPresenter.spec.js
src/components/carousel/index.tsx
src/components/carousel/types.ts

This adds vertical scroll ability to the `Carousel` component as requested on #1163 
Add vertical mode to Carousel component (horizontal prop)

Add vertical scroll to Carousel component

---

src/components/card/CardSection.tsx

Avoid passing overlayContent to Card.Section's Image when not needed
This leads to use `ImageBackground` instead of `Image` which works a little different
Avoid passing overlayContent to Card.Section's Image when not needed

Avoid passing overlayContent in CardSecion

---

src/helpers/Constants.ts

On web there is no `StatusBarManager` so we simply catch it if it's undefined.
catch undefined StatusBarManager

fix: catch undefined StatusBarManager

---

src/incubator/TextField/index.tsx

The "Code Example" link at https://wix.github.io/react-native-ui-lib/docs/Incubator.TextField/ went to an outdated folder in the repo. Updated link to use the correct path to the component in the repo.
Update docs for Incubator.TextFIeld link to example code so it opens the correct url and doesn't 404.

Update Incubator.TextField Code Example link url to correct path

---

generatedTypes/components/fader/index.d.ts
lib/components/SafeArea/SafeAreaSpacerView.js
src/components/dialog/DialogDismissibleView.tsx
src/components/fader/index.tsx
src/components/sharedTransition/SharedArea.js
src/components/sharedTransition/SourceElement.js
src/components/sharedTransition/TargetElement.js
src/components/tabController/FadedScrollView.tsx

Add IGNORE to some internal components or components that should haven not been in docs
Fix missing docs info and remove irrelevant components

Ignore irrelevant components

---

src/style/typographyPresets.ts

The bold typography only works on IOS. This patch will make it works for both android and iOS
Fix  bold typography for Android

bug on android for Bold typography

---

src/commons/asBaseComponent.tsx

Invoke ErrorBoundary's onError function only if the function exists.
Invoke ErrorBoundary's onError function only if the function exists.

Fix/Invoke onError only if exists

---

demo/src/screens/componentScreens/CarouselVerticalScreen.tsx
generatedTypes/components/carousel/index.d.ts
generatedTypes/components/carousel/types.d.ts
src/components/carousel/index.tsx
src/components/carousel/types.tsx

Support passing Animated.Value to attach to Carousel's ScrollView's onScroll event. 
This way, our users can animate elements based on the Carousel scroll offset. 
Support passing Animate.ValueXY to attach to Carousel's onScroll event

Support attaching animated value to Carousel scroll animated event

---

uilib-docs/configurations/plugins.js

I noticed the issue we had with building our docs out of TS files has been fixed. 
So now can build our docs (`npm run docs:deploy`) like before without having to compile the TS files into JS. 
This also fix some issues we had with missing props
Fix missing props in components docs

Stop ignoring TS files when building docs

---

src/components/dialog/DialogDismissibleView.tsx

DialogDismissibleView - fix bug with delayed insets (we have await in our private repo)
BTW, I think that code can probably be moved to public.
DialogDismissibleView - fix bug with delayed insets

DialogDismissibleView - fix bug with delayed insets

---

generatedTypes/components/badge/index.d.ts
src/components/avatar/index.tsx
src/components/badge/index.tsx

There was an issue with Badge's defaultProps that contained a default value for `size` prop. 
Because we have a default value, we declare the prop to **not** be optional. 
But it causes issues in other places that depends on `BadgeProps`
for example, an Avatar component has `badge` prop and its type is `BadgeProps`, but it doesn't know that size has a default value and it throws TS error that it is required (even though it's not)
Fix Badge's size default prop and make it optional

Fix Badge's size default prop

---

generatedTypes/index.d.ts
src/components/picker/index.js

Picker - fix not responding to external value change when renderPicker is used.
This does not solve this issue when using `useNativePicker`, that requires a bigger change.
Can be tested with the following PlaygroundScreen:
```
import _ from 'lodash';
import {StyleSheet} from 'react-native';
import {View, Text, Card, TextField, Button, Picker, PickerItemValue} from 'react-native-ui-lib'; //eslint-disable-line
render() {
return (
<View bg-dark80 flex padding-20 center>
<View marginT-20>
<TextField placeholder="Placeholder" />
</View>
<Card height={100} center padding-20>
<Text text50>Playground Screen</Text>
</Card>
<View flex center>
<Button marginV-20 label="Button"/>
</View>
<PickerBug/> …
```

Picker - fix not responding to external value change when renderPicker is used

---

src/components/card/index.tsx
src/components/connectionStatusBar/index.js
src/components/picker/index.js
uilib-docs/src/templates/component.js

Add notes for component that has dependency on an optional dependency
Add notes in our docs for component that has dependency on an optional dependency

Add notes for component that has dependency on an optional dependency

---

src/components/carousel/CarouselPresenter.ts
src/components/carousel/__tests__/CarouselPresenter.spec.js

A fix for #1218
Replaced `children.length` with Reacts children count helper.

fix #1218 where carousel is not calculating children correctly

---

demo/src/screens/componentScreens/MaskedInputScreen.js
src/components/maskedInput/index.js

Added proper clear method (override what's in BaseInput) that also clears the internal value state. 
Also replaced View container with Touchable one to catch better touch events that focus the input
Fix support for clearing MaskedInput value programmatically using ref `clear` method

Fix #1231 - Support clearing MaskedInput and make it more responsive to touch

---

generatedTypes/components/card/index.d.ts
generatedTypes/components/modal/TopBar.d.ts
generatedTypes/components/touchableOpacity/index.d.ts
src/components/card/index.tsx
src/components/modal/TopBar.tsx
src/components/touchableOpacity/index.tsx

Fix callback props typings in components like: TouchableOpacity, Card and Modal.TopBar
Fix callback props typings in components like: TouchableOpacity, Card and Modal.TopBar

Fix callback props typings in various components

---

demo/src/screens/incubatorScreens/WheelPickerScreen.tsx
generatedTypes/incubator/WheelPicker/index.d.ts
src/incubator/WheelPicker/index.tsx

Add right label to the wheelPicker selected value
Add right label to the wheelPicker selected value

Feat/add label to wheelPicker

---

src/components/dateTimePicker/index.js

See https://github.com/react-native-datetimepicker/datetimepicker/issues/285 for more details
Set the display mode of the DateTimePicker to 'inline' on iOS to fit the previous native style for date and time pickers, when built with Xcode 12 for iOS 14.
Fixes DateTimePicker component style for apps built with Xcode 12 running on iOS 14.

Update dateTimePicker to support Xcode 12 and iOS 14

---

demo/src/screens/componentScreens/DialogScreen.js
generatedTypes/components/dialog/index.d.ts
src/components/dialog/index.tsx

Add IgnoreBackgroundPress prop to Dialog component to support not dismissing the dialog on background press 
Add example in DialogScreen
relevant issue - https://github.com/wix/react-native-ui-lib/issues/1262
Add IgnoreBackgroundPress prop to Dialog component

Feat/add IgnoreBackgroundPress prop

---

eslint-rules/lib/utils/generalUtils.js
eslint-rules/package.json
eslint-rules/tests/lib/rules/no-hard-coded-color.js

Fix eslint util - `findValueNodeOfIdentifier()`
JIRA 1678
Fix eslint util - `findValueNodeOfIdentifier()`

Fix/eslint findValueNodeOfIdentifier util

---

eslint-rules/lib/rules/function-deprecation.js
eslint-rules/package.json
eslint-rules/tests/function_deprecation.json
eslint-rules/tests/lib/rules/function-deprecation.js

ESLint - add support for class or inherited functions
ESLint - add support for class or inherited functions

ESLint - add support for class or inherited functions

---

demo/src/screens/componentScreens/PickerScreen.js
src/components/picker/PickerItem.js
src/components/picker/index.js

Add selectionLimit prop to the Picker component to support limiting the number of the selected items.
Jira 1702
Add selectionLimit prop to the Picker component to support limiting the number of the selected items.

Feat/Picker selectionLimit prop

---

generatedTypes/components/segmentedControl/index.d.ts
generatedTypes/components/segmentedControl/segment.d.ts
src/components/segmentedControl/index.tsx
src/components/segmentedControl/segment.tsx
src/index.ts

Export SegmentedControlItemProps
Export SegmentedControlItemProps

Infra/export SegmentedControlItemProps

---

src/components/card/index.tsx

Fix issue with Card's backgroundColor prop not working
Fix issue with Card's backgroundColor prop not working

Fix issue with Card's backgroundColor not working

---

generatedTypes/components/carousel/CarouselPresenter.d.ts
src/components/carousel/CarouselPresenter.ts

This is not a fix, just a small refactor.
React provides `PropsWithChildren` to decorate any interface with the `children` type
use PropsWithChildren in Carousel

use PropsWithChildren in Carousel

---

demo/src/screens/componentScreens/HapticScreen.tsx
generatedTypes/services/HapticService.d.ts
generatedTypes/services/index.d.ts
src/index.ts
src/services/HapticService.ts
src/services/index.ts

Export enum HapticType instead of hapticMethods
Export enum HapticType instead of hapticMethods

Add HapticType

---

src/index.js

I'm just enabling here something we prepare some time ago. 
The TextFieldMigrator is a middleware that responsible for migrating our users from the old implementation of TextField to the new one
Enable TextFieldMigrator for migrating from old TextField API to the new one

Enable back our TextFieldMigrator

---

generatedTypes/components/text/index.d.ts
generatedTypes/components/view/index.d.ts
src/.babelrc.json
src/components/button/index.tsx
src/components/text/index.tsx
src/components/view/index.tsx
src/incubator/TextField/useFieldState.ts
src/services/HapticService.ts
tsconfig.json

Add more paths aliases for: services, hooks, commons, etc.. 
Add more paths aliases for: services, hooks, commons, etc..

Add more paths aliases

---

demo/src/screens/componentScreens/CarouselVerticalScreen.tsx
src/components/carousel/index.tsx

Fix support for auto height layout for vertical carousel pages
Fix support for auto height layout for vertical carousel pages

Support auto height layout for vertical carousel

---

generatedTypes/style/colors.d.ts
src/style/colors.ts

Fixes #1282 - Update color presets according to scheme when scheme chanages
Fixes #1282 - Update color presets according to scheme when scheme chanages

Update color presets when scheme changes

---

src/incubator/WheelPicker/index.tsx

`onMomentumScrollEnd` not being called in Android - https://github.com/facebook/react-native/issues/26661
Add a call for the `onChange()` callback manually.
Fix inconsistent between iOS and Android by calling the `onChange()` function manually

Fix/ WheelPicker onChange in Android

---

demo/src/screens/componentScreens/ChipScreen.tsx
generatedTypes/components/chip/index.d.ts
src/components/chip/index.tsx

Support adding a custom element to Chip component with rightElement and LeftElement Props.
Related issue: https://github.com/wix/react-native-ui-lib/issues/895
Chip component now supports passing leftElement and rightElement

Feat/ Add custom elements to Chip

---

src/incubator/WheelPicker/index.tsx

Use `getNode()` in WheelPicker's FlatList to support reanimated v1
Use `getNode()` in WheelPicker's FlatList to support reanimated v1

Infra/use getNode in WheelPicker's FlatList

---

eslint-rules/lib/rules/component-prop-deprecation.js
eslint-rules/tests/component_prop_deprecation.json
eslint-rules/tests/lib/rules/component-prop-deprecation.js

Add support to our `component-prop-deprecation` rule to verify required props
Add support to our `component-prop-deprecation` rule to verify required props

Support checking for required props in a component

---

src/components/button/ButtonTypes.tsx
uilib-docs/package.json
uilib-docs/src/templates/component.js
uilib-docs/src/templates/components.scss

Show docs showcase on mobile and use carousel for showcase
Fix missing docs components showcase on mobile and use carousel to present the showcase

Show docs showcase on mobile and use carousel for showcase

---

demo/src/screens/componentScreens/HintsScreen.tsx
generatedTypes/components/hint/index.d.ts
src/components/hint/index.tsx

Support passing custom content to the Hint component.
Related issue: #895 
Hint component now supports passing customContent prop.

Feat/ Add custom content to Hint

---

src/components/radioButton/RadioGroup.tsx

RadioGroup - fix handling of a constant initial value.
It seems that we're handling no `initialValue` and `initialValue={this.state.value}`, but not a constant one, this fixes that.
RadioGroup - fix handling of a constant initial value
Resolves #1169

RadioGroup - fix handling of a constant initial value

---

src/components/picker/index.js

Picker item was undefined
- add optional chaining 
- change getLabel() to be arrow function
Jira 1825
Fix issue with getting the picker item label

Fix/ Picker item undefined value

---

typings/components/Toast.d.ts

Toast - fix typings
Toast - fix typings
Resolves #1249

Toast - fix typings

---

demo/src/screens/componentScreens/EmptyStateScreen.js
src/components/stateScreen/index.js

Fix https://github.com/wix/react-native-ui-lib/issues/1305
Fix StateScreen source deprecation

Fix/ StateScreen source deprecation

---

demo/src/screens/componentScreens/TabControllerScreen/index.tsx
generatedTypes/components/tabController/TabBar.d.ts
src/components/tabController/TabBar.tsx

Resolves https://github.com/wix/react-native-ui-lib/issues/1263
Add `wideIndicator` prop to make the indicator wider
Add `spreadItems` prop to make the items spread (default is true).
Add `wideIndicator` and `spreadItems` props to TabController.TabBar

Feat/ TabController.TabBar style

---

eslint-rules/lib/rules/assets-deprecation.js
eslint-rules/lib/rules/component-deprecation.js
eslint-rules/lib/rules/component-prop-deprecation.js
eslint-rules/lib/rules/function-deprecation.js
eslint-rules/lib/rules/no-direct-import.js
eslint-rules/lib/rules/no-hard-coded-color.js
eslint-rules/lib/rules/prop-value-shape-deprecation.js
eslint-rules/lib/rules/typography-deprecation.js
eslint-rules/lib/utils/generalUtils.js
eslint-rules/lib/utils/index.js
eslint-rules/package.json

Improve error handling - add more details to errors
Improve error handling - add more details to errors

Improve error handling - add more details to errors

---

src/components/tabController/TabBarItem.tsx

Added prop to disable icon's tint color on `TabController.TabBarItem` as per #1156
- added `disableIconTintColor` prop to TabController.TabBarItem

added `disableIconTintColor` prop to TabController.TabBarItem

---

demo/src/screens/componentScreens/TabControllerScreen/index.tsx
generatedTypes/components/tabController/TabBar.d.ts
src/components/tabController/TabBar.tsx

Following this PR - https://github.com/wix/react-native-ui-lib/pull/1331#pullrequestreview-678097843
Change `wideIndicator` (boolean) prop to `indicatorInsets` (number).
Move style to styleSheet
Change `wideIndicator` prop to `indicatorInsets`.

Fix/ tabController_tabBar

---

src/components/slider/index.js

onSeekStart was missing from event-cycle when tapping to seek (as oppose to slide to seek), added so users will be able to have same events called when sliding and when tapping to seek.
Added missing `onSeekStart` event call, when tapping on track to seek.

add missing event when tapping on track

---

generatedTypes/components/segmentedControl/segment.d.ts
src/components/segmentedControl/index.tsx
src/components/segmentedControl/segment.tsx

Add testID to SegmentedControl component
Fix animation leap
Add testID to SegmentedControl component and fix animation

Fix/ SegmentedControl fixes

---

demo/src/screens/componentScreens/PickerScreen.js
src/components/picker/NativePicker.js
src/components/picker/PickerDialog.android.js
src/components/picker/PickerDialog.ios.js

Unify the code that renders the inner WheelPicker inside the the dialog of the Picker (when passing `useNativePicker`). 
We have a different implementation of the dialog per each platform but the content should be the same. 
This PR is a preparation for JIRA WOAUILIB-1843
Unify internal code of native picker (wheel picker)

Unify some code in the native picker dialog implementation

---

src/components/dateTimePicker/index.js

`DateTimePicker` renders white on white text when Dark theme is enabled on iOS device. `react-native-datetimepicker` has an override prop for this called `themeVariant`. This change is to Implement this prop in `react-native-ui-lib` `DateTimePicker`.
Add `themeVariant` prop to `DateTimePicker`.

DateTimePicker - Implement themeVariant prop

---

demo/src/screens/componentScreens/DateTimePickerScreen.js
src/components/dateTimePicker/index.js

Fix render prop misnamed, used `renderExpandableInput` from `TextField` prop, to use `DateTimePicker` right prop name `renderInput`
DateTimePicker to use `renderInput` instead of `renderExpandableInput` to pass a custom input component.

using renderInput instead renderExpandableInput was left out

---

generatedTypes/components/hint/index.d.ts
src/components/hint/index.tsx

Fix missing Hint bubble fade-out animation
Added missing hide animation for `Hint` bubble

fix hint animation

---

eslint-rules/lib/rules/no-hard-coded-color.js

Our hard-coded-color rule threw the following exception in our report 
`Error: TypeError: Cannot read property 'toLowerCase' of undefined`
this PR fix the issue
Fix our eslint plugin hard-coded-color rule not handling undefined colors

Fix an exception with hard coded color rule

---

demo/src/screens/componentScreens/TabBarScreen.tsx
generatedTypes/components/tabBar/TabBarItem.d.ts
src/components/tabBar/TabBarItem.tsx

Support adding custom elements to TabBarItem with leadingAccessory and trailingAccessory Props.
Related issue: #895
TabBarItem now supports passing leadingAccessory and trailingAccessory Props

Feat/ Add custom elements to TabBarItem

---

demo/src/screens/componentScreens/TabControllerScreen/index.tsx
generatedTypes/components/tabController/TabBarItem.d.ts
generatedTypes/components/tabController2/TabBarItem.d.ts
src/components/tabController/TabBarItem.tsx
src/components/tabController2/TabBarItem.tsx

Support adding custom elements to TabController's TabBarItem with leadingAccessory and trailingAccessory Props.
(Supported on TabController and on TabController2)
Related issue: #895
TabController's TabBarItem now supports passing leadingAccessory and trailingAccessory Props

Feat/ TabController's TabBarItem custom elements

---

src/components/segmentedControl/index.tsx
src/components/segmentedControl/segment.tsx

Fix segmentedControl vertical paddings to increase segments touch area 
Fix segmentedControl vertical paddings to increase segments touch area

Fix/ segmentedControl paddings 

---

generatedTypes/components/drawer/index.d.ts
src/components/drawer/index.tsx

Support passing customElement to Drawer items.
Related issue: #895
Support passing customElement to Drawer items.

Feat/ Add customElement prop to Drawer

---

src/incubator/WheelPicker/index.tsx

WheelPicker - fix warning about getNode
WheelPicker - fix warning about getNode

WheelPicker - fix warning about getNode

---

generatedTypes/components/floatingButton/index.d.ts
src/components/floatingButton/index.tsx

Add testID to floatingButton component
Add testID to floatingButton component

Fix/ FloatingButton testID

---

src/components/picker/index.js

We didn't forward the ref in the picker component but did wrap It with forwardRef HOC which resulted in a null ref. 
This fix issue #1274
Fix issue with Picker component ref not being forwarded

Fix forwarded ref in Picker

---

generatedTypes/components/avatar/index.d.ts
generatedTypes/components/carousel/index.d.ts
generatedTypes/components/featureHighlight/index.d.ts
generatedTypes/components/image/index.d.ts
generatedTypes/components/modal/index.d.ts
generatedTypes/components/overlay/index.d.ts
generatedTypes/components/text/index.d.ts
src/components/avatar/index.tsx
src/components/button/ButtonTypes.tsx
src/components/card/index.tsx
src/components/carousel/index.tsx
src/components/checkbox/index.tsx
src/components/chip/index.tsx
src/components/colorPicker/ColorSwatch.tsx
src/components/featureHighlight/index.tsx
src/components/image/index.tsx
src/components/listItem/index.js
src/components/modal/index.tsx
src/components/overlay/index.tsx
src/components/picker/PickerItem.js
src/components/tabBar/TabBarItem.tsx
src/components/text/index.tsx
src/components/textField/index.js
src/components/touchableOpacity/index.tsx
src/components/view/index.tsx
uilib-docs/package.json
uilib-docs/src/pages/sections/IntroSection.jsx
uilib-docs/src/templates/component.js

Fix docs issue with external extend link to some component not working (for example: in Carousel's link to ScrollView)
Fix docs links

Fix issues with docs extend links for various components

---

demo/src/screens/componentScreens/TabControllerScreen/index.tsx
generatedTypes/components/tabController2/index.d.ts
src/components/tabController2/TabBar.tsx
src/components/tabController2/TabBarItem.tsx
src/components/tabController2/index.tsx

This PR fix two issues with new implementation of TabController (2)
- Fix issue with "ignored" tab item not being ignored
- Fix issue when items size change, the TabBar didn't rebuild itself with the new items
- Fix backward compatibility for passing items prop directly to TabController.TabBar (instead of TabController)
Fix TabController2 issue with rebuilding TabBar items when their count changes

Fix issue with TabController not handling dynamic items size

---

demo/src/screens/incubatorScreens/TouchableOpacityScreen.js
generatedTypes/incubator/TouchableOpacity2.d.ts
generatedTypes/incubator/index.d.ts
package.json
src/incubator/TouchableOpacity2.tsx
src/incubator/index.ts

Reimplement Incubator.TouchableOpacity with Reanimated v2
The component is currently exported as `Incubator.TouchableOpacity2`
eventually, we'll replace it with `Incubator.TouchableOpacity` (without a migration, since the API is the same)
Reimplement Incubator.TouchableOpacity with Reanimated v2 as Incubator.TouchableOpacity2

Reimplement Incubator.TouchableOpacity with reanimatedv2

---

src/components/picker/index.js

Fix how we handle internal picker value change for custom picker in multi mode
Fix #1387 
Fix issue with Picker with custom renderPicker in multi-select mode not reacting to value change

Fix picker value issue

---

src/components/tabController/TabBarItem.tsx

Use interpolateColors instead of interpolateColor.
I've added this comment to the code, partly so we can find it when removing reanimated1 code.
```
Unlike const interpolate = interpolateNode || _interpolate;
interpolateColors has a different API (outputColorRange instead of outputRange)
```
Use interpolateColors instead of interpolateColor (fix warning about interpolate)

Use interpolateColors instead of interpolateColor

---

demo/src/screens/ExampleScreenPresenter.js
demo/src/screens/componentScreens/ViewScreen.js

Fix renderSliderOption function - fixes broken slider in few screens.
WOAUILIB-1907
Fix renderSliderOption function - fixes broken slider in few screens.

Fix/ renderSliderOption method

---

CONTRIBUTING.md

Adding a guide for contributors 
Adding a guide for contributors

Adding a guide for contributors 

---

src/components/dateTimePicker/index.js

Apparently someone in One App already use the custom render feature in DateTimePicker, just they used the TextField renderExpandableInput prop and we recently declared an explicit prop in DateTimePicker as `renderInput`. 
Support passing TextField's `renderExpandableInput` to DateTimePicker alongside `renderInput`

pass renderInput efore passing TextField props

---

demo/src/configurations.js
demo/src/screens/incubatorScreens/WheelPickerScreen.tsx
generatedTypes/incubator/WheelPicker/index.d.ts
generatedTypes/incubator/WheelPicker/usePresenter.d.ts
src/incubator/WheelPicker/index.tsx
src/incubator/WheelPicker/usePresenter.ts

I added a new prop `initialValue` to Incubator.WheelPicker. 
`initialValue` doesn't work together with `selectedValue` prop
The first (initialValue) makes the picker uncontrolled in a way the user doesn't need to pass it on every change. 
The second (selectedValue) is completely controlled 
Notice that passing a new `initialValue` will reset the value and index of the picker. 
Add `initialValue` prop to Incubator.WheelPicker

Add support to initialValue in WheelPicker

---

generatedTypes/index.d.ts
src/index.ts

Export missing components' typings 
Export missing components' typings

Export missing typings

---

generatedTypes/components/slider/GradientSlider.d.ts
src/components/slider/GradientSlider.tsx

Fix issue with GradientSlider thumb moving incorrectly 
Fix issue #1441 
Fix issue with GradientSlider thumb moving incorrectly

In GradientSlider - make sure to pass only initialValue to Slider

---

demo/src/screens/incubatorScreens/IncubatorTextFieldScreen.tsx
generatedTypes/incubator/TextField/FieldContext.d.ts
generatedTypes/incubator/TextField/useFieldState.d.ts
generatedTypes/incubator/TextField/useImperativeInputHandle.d.ts
src/incubator/TextField/FieldContext.ts
src/incubator/TextField/Input.tsx
src/incubator/TextField/index.tsx
src/incubator/TextField/useFieldState.ts
src/incubator/TextField/useImperativeInputHandle.ts

Expose an imperative `validate`  method on Incubator.TextField
feature request #1418
Expose an imperative `validate`  method on Incubator.TextField

expose an imperative validate method on Incubator.TextField component

---

src/components/button/ButtonConstants.ts
src/components/button/__tests__/__snapshots__/index.spec.js.snap

Update Button disabled color to grey50
(WOAUILIB-1990)
Update Button disabled color to grey50

Update Button disabled color to grey50 according to guidelines

---

src/components/drawer/index.tsx

Fix issue with swiping drawer in RTL mode when there are items only on one side
issue - WOAUILIB-1965
Fix RTL bug in drawer

Fix/ drawer RTL bug

---

demo/src/screens/MenuStructure.js
demo/src/screens/componentScreens/GridViewScreen.tsx
demo/src/screens/componentScreens/index.js
src/components/GridListItem/index.tsx
src/components/GridView/index.tsx
src/helpers/FormattingPresenter.ts

New GridView and GridListItem component
Add GridView and GridListItem component. Implement example GridViewScreen.tsx and add to demo app
GridView.tsx
GridListItem.tsx
FormattingPresenter.ts

Add GridView and GridListItem component

---

demo/src/index.js
demo/src/screens/MenuStructure.js
demo/src/screens/componentScreens/ActionSheetScreen.tsx
demo/src/screens/realExamples/ProductPage/index.tsx
demo/src/screens/realExamples/Twitter/index.tsx
demo/src/screens/realExamples/index.js

Created Demo Screens in Inspiration Screens section
```
demo/src/index.js
demo/src/screens/MenuStructure.js
demo/src/screens/realExamples/ProductPage/index.tsx - new one
demo/src/screens/realExamples/Twitter/index.tsx - new one
demo/src/screens/realExamples/index.js
```

[Inspiration screens]: Product Page & Twitter screens

---

src/components/hint/index.tsx

Hint - fix target frame update when toggling visibility in case of target frame change (due to scroll, for example).
fix issue #1471 
Hint - fix target frame update when toggling visibility in case of target frame change (due to scroll, for example).

Hint - fix target frame update

---

demo/src/screens/incubatorScreens/PanViewScreen.tsx
generatedTypes/components/modal/index.d.ts
src/components/modal/index.tsx

Add useGestureHandler to Modal
Add useGestureHandler to Modal

Add useGestureHandler to Modal

---

src/components/skeletonView/index.tsx

Avoid rendering SkeletonView component when its dependencies are missing and add proper warnings to the user
Avoid rendering SkeletonView component when its dependencies are missing and add proper warnings to the user

SkeletonView optional deps warnings

---

generatedTypes/src/hooks/useDidUpdate/index.d.ts
src/hooks/useDidUpdate/index.ts

Fix useDidUpdate dependencies type - you can see the bug when there's more than one dep in the array.
Fix useDidUpdate dependencies type

Fix useDidUpdate dependencies type

---

generatedTypes/src/commons/modifiers.d.ts
src/commons/__tests__/modifiers.spec.js
src/commons/modifiers.ts

Support combining multiple `abs` modifiers
So far we have `abs` modifiers to quickly position views in an absolute position. We have: absT, absR, absB, absL, etc...
This PR add support for combining multiple abs modifiers, so basically we can do this
```
<View absB absR>
<Text>xxxx </Text>
</View>
```
to position a view at the right bottom of the screen 
Support passing multiple abs modifiers (e.g absR and absB together)

Support combining multiple abs modifiers

---

eslint-rules/lib/rules/component-prop-deprecation.js
eslint-rules/package.json
eslint-rules/tests/lib/rules/component-prop-deprecation.js

prop-deprecation - required prop - support method and member
prop-deprecation - required prop - support method and member

prop-deprecation - required prop - support method and member

---

generatedTypes/src/components/slider/GradientSlider.d.ts
src/components/slider/GradientSlider.tsx

Pass on Slider props in GradientSlider
Fix #1461
Pass on Slider props in GradientSlider

Pass on slider props in GradientSlider

---

src/incubator/TextField/index.tsx

set TextField initial width to be as the placeholder width
set TextField initial width to be as the placeholder width

Feat/ TextField initial width

---

src/commons/asBaseComponent.tsx
src/components/tagsInput/index.js

Use subscription objects to remove subscriptions. This prevents deprecation warnings in RN65
Use subscription objects to remove subscriptions

Use subscription objects to remove subscriptions

---

generatedTypes/src/components/listItem/index.d.ts
src/components/listItem/index.tsx

Fixed issue that caused ListItem.Part to be missing when using Typescript
- Added Part to neccesary parts of src/components/listitem/index.tsx

Fixed issue, that caused Part to be missing from ListItem (ts)

---

generatedTypes/src/style/themeManager.d.ts
src/style/themeManager.ts

ThemeManager - removing 'setTheme'
ThemeManager - removing 'setTheme'

ThemeManager - removing 'setTheme'

---

generatedTypes/src/components/card/CardImage.d.ts
src/components/card/CardImage.tsx

CardImage - remove deprecated props
CardImage - remove deprecated props

CardImage - remove deprecated props

---

lib/components/Keyboard/KeyboardTracking/KeyboardTrackingView/KeyboardTrackingView.ios.tsx

KeyboardTrackingView - change 'useSafeArea' default to 'false'.
KeyboardTrackingView - change 'useSafeArea' default to 'false'.

KeyboardTrackingView - change 'useSafeArea' default to 'false'

---

demo/src/screens/componentScreens/AvatarsScreen.tsx
demo/src/screens/componentScreens/BadgesScreen.tsx
demo/src/screens/componentScreens/DrawerScreen.tsx
demo/src/screens/componentScreens/TabBarScreen.tsx
generatedTypes/src/components/avatar/index.d.ts
generatedTypes/src/components/badge/index.d.ts
src/components/avatar/__tests__/index.spec.js
src/components/avatar/index.tsx
src/components/badge/index.tsx
src/components/chip/index.tsx
src/components/tabBar/TabBarItem.tsx
src/components/tabController/TabBarItem.tsx
src/components/tabController2/TabBarItem.tsx
src/incubator/TabController/TabBarItem.js

Avatar and Badge - props deprecation.
Avatar and Badge - props deprecation.

Avatar and Badge - props deprecation

---

demo/src/screens/componentScreens/BasicListScreen.tsx
demo/src/screens/componentScreens/ContactsListScreen.js
generatedTypes/lib/components/Keyboard/KeyboardTracking/KeyboardTrackingView/KeyboardTrackingView.ios.d.ts
package.json

react-native-animatable - remove dependency.
react-native-animatable - remove dependency.

react-native-animatable  - remove dep

---

generatedTypes/lib/components/Keyboard/KeyboardTracking/KeyboardTrackingView/index.d.ts
generatedTypes/lib/components/Keyboard/index.d.ts
lib/components/Keyboard/KeyboardTracking/KeyboardTrackingView/index.tsx

Pass forward ref in KeyboardTrackingView component
Fix issue with KeyboardTrackingView not passing forward ref

make sure to pass forward ref in KeyboardTrackingView component

---

generatedTypes/src/components/tabBar/TabBarItem.d.ts
src/components/tabBar/TabBarItem.tsx

TabBarItem - remove deprecated prop.
TabBarItem - remove deprecated prop.

TabBarItem - remove deprecated prop

---

src/components/stateScreen/index.tsx

StateScreen - remove deprecated props.
StateScreen - remove deprecated props.

StateScreen - remove deprecated props

---

demo/src/screens/componentScreens/ChipScreen.tsx
demo/src/screens/componentScreens/DialogScreen.js
demo/src/screens/componentScreens/PickerScreen.js
generatedTypes/src/components/actionSheet/index.d.ts
generatedTypes/src/components/dialog/index.d.ts
src/components/actionSheet/index.tsx
src/components/dateTimePicker/index.js
src/components/dialog/index.tsx
src/components/picker/PickerDialog.android.js
src/components/picker/PickerDialog.ios.js

Dialog - remove 'onModalDismissed' (use 'onDialogDismissed' instead).
Dialog - remove 'onModalDismissed' (use 'onDialogDismissed' instead).

Dialog remove deprecated prop

---

generatedTypes/src/components/card/CardSection.d.ts
src/components/card/CardSection.tsx

CardSection - remove deprecated prop: 'sorce' (use 'imageSource').
CardSection - remove deprecated prop: 'sorce' (use 'imageSource').

Card section remove deprecated prop

---

markdowns/getting-started/v6.md

Prepare a migration guide for v6
Prepare a migration guide for v6

V6 migration guide

---

generatedTypes/src/incubator/WheelPicker/Item.d.ts
generatedTypes/src/incubator/WheelPicker/index.d.ts
src/incubator/WheelPicker/Item.tsx
src/incubator/WheelPicker/index.tsx

WheelPicker (Incubator) - add support for theme
WheelPicker (Incubator) - add support for theme

WheelPicker (Incubator) - add support for theme

---

demo/src/configurations.js
demo/src/screens/foundationScreens/DarkModeScreen.tsx
generatedTypes/src/components/connectionStatusBar/index.d.ts
generatedTypes/src/style/colors.d.ts
generatedTypes/src/style/index.d.ts
generatedTypes/src/style/scheme.d.ts
src/commons/asBaseComponent.tsx
src/commons/modifiers.ts
src/style/__tests__/scheme.spec.js
src/style/colors.ts
src/style/index.ts
src/style/scheme.ts

Fix support for setting color scheme manually (Fix #1548)
- Created Scheme class to handle all schemes logic 
- Move relevant logic from Colors class to Scheme class
- Change appearance change registration in asBaseComponent with scheme change registration
- Update DarkModeScreen example to showcase a scenario of manual scheme change
Fix support for setting color scheme manually

Fix support for setting color scheme manually 

---

src/components/picker/PickerModal.js
src/components/picker/index.js

*Able to change the background of the Picker's default modal. To fully support dark mode, I added also the ability to change the search icon.*
* 2 new props; *overlayBackground* and *searchStyle={{(...), icon: ""}}* 
* fixes #1371

Add overlayBackground and able to change search Icon.

---

markdowns/foundation/assets.md
markdowns/foundation/colors.md
markdowns/foundation/modifiers.md
markdowns/foundation/style.md
markdowns/foundation/theme-manager.md
markdowns/getting-started/setup.md
markdowns/getting-started/usage.md
markdowns/getting-started/v5.md
markdowns/getting-started/v6.md

*This PR contains a set of commits, all containing copy-editing changes for the following sections of the documentation:*
- Setup
- Usage
- v4 -> v5
- v5 -> v6
- Style
- Modifiers
- Assets
- Theme Manager
- Colors
It only contains changes to `.md` files.
N.B. This PR includes a [commit](https://github.com/wix/react-native-ui-lib/commit/a5405e5f8f7474211c23ae032b07723ac5e8d5a8) with an in-line comment ([see here](https://github.com/wix/react-native-ui-lib/commit/a5405e5f8f7474211c23ae032b07723ac5e8d5a8#diff-4843d71e2b6e127d36203d6655b804cf006a5699baa6762e7e4353d4ec321b9b)) , which should be removed from the docs before or at some point after this PR is merged.
*No changes to actual source code, as this only contains copy-editing for a portion of the docs*

Copy-editing of the docs

---

src/components/tabController/TabBar.tsx
src/components/tabController/index.tsx
src/components/tabController/useScrollToItem.ts

Fix exception when passing a single item to TabController 
Fix exception when passing a single item to TabController

Fix error when passing a signle item to TabController

---

src/incubator/WheelPicker/index.tsx

Fix WheelPicker issue with RTL on iOS
Fix WheelPicker issue with RTL on iOS

Fix WheelPicker issue with RTL on iOS

---

generatedTypes/src/components/avatar/index.d.ts
generatedTypes/src/components/badge/index.d.ts
src/components/avatar/index.tsx
src/components/badge/index.tsx

Temporarily support string for Badge size
Once we'll migrate our one app users from passing strings, we'll remove this type 
Temporarily support string for Badge size for gradual migration after v6

Temporarily support string for Badge size

---

demo/src/screens/componentScreens/SectionsWheelPickerScreen.tsx
src/incubator/WheelPicker/index.tsx

Fix uncontrolled mode of wheelPicker (incubator)
Fix uncontrolled mode of wheelPicker (incubator)

Fix/ wheelPicker - uncontrolled mode

---

scripts/buildPackages.js

I got errors when trying to use Scheme, e.g. `import { Scheme } from 'react-native-ui-lib/style'`
```
TypeError: undefined is not an object (evaluating '_style.Scheme.schemes')
```
If I am using this incorrectly let me know but I believe this will fix the issue.
Add `Scheme` to be accessible from the style package

Fix/add Scheme to style package

---

demo/src/screens/componentScreens/SkeletonViewScreen.tsx
generatedTypes/src/components/skeletonView/index.d.ts
src/components/skeletonView/index.tsx

Skeleton - add new features + refactor
We still have a problem to replace the private version, because here `renderContent` sends `customValue` and in private it sends `props` (all of them), but for now I did not find any usages in private, so I'm hoping it will be a non-issue.
Skeleton - add new features + refactor

Skeleton - add new features (align to private)

---

demo/src/screens/incubatorScreens/IncubatorTextFieldScreen.tsx
generatedTypes/src/incubator/TextField/index.d.ts
generatedTypes/src/incubator/TextField/usePreset.d.ts
src/incubator/TextField/index.tsx

- Support passing custom preset to TextField
- Pass on preset to `fieldStyle` callback so users can react to different presets
TextField - Support custom preset and pass it on to fieldStyle callback for custom preset styles

TextField - Support passing custom preset and use it in fieldStyle callback

---

src/components/dateTimePicker/index.js

On Android, dismissing the DateTimePicker dialog by clicking Cancel or by clicking on the background overlay will cause a bug whereby you have to press the DateTimePicker input twice into to launch the DateTimePicker dialog again. This is because the expandable overlay is still in the expanded state after dismissing the dialog. This commit fixes this bug by toggling the expandable overlay when the DateTimePicker dialog is dismissed.
https://user-images.githubusercontent.com/1888212/139923766-601be1fe-5447-44fe-a204-e08f5592bf7a.mp4
https://user-images.githubusercontent.com/1888212/139923851-aa70e361-e191-4244-9392-f835971b66e3.mp4
Fix Android double press bug after dismissing DateTimePicker dialog

Fix Android double press bug after dismissing DateTimePicker dialog

---

src/components/drawer/Swipeable.tsx

Drawer - block frame update for missing items.
Drawer - block frame update for missing items.

Drawer - block frame update for missing items

---

src/components/text/text.api.json
src/components/touchableOpacity/touchableOpacity.api.json
src/components/view/view.api.json
src/components/wizard/wizard.api.json
src/components/wizard/wizardStep.api.json

Add docs for t-z components
Add docs for t-z components

Add docs for t-z components

---

src/components/gridListItem/gridListItem.api.json
src/components/gridView/gridView.api.json
src/components/hint/hint.api.json
src/components/icon/icon.api.json
src/components/image/image.api.json
src/components/listItem/listItem.api.json
src/components/listItem/listItemPart.api.json
src/components/loaderScreen/loaderScreen.api.json

API files for G-L components 
API files for G-L components

Add api files

---

src/hooks/useOrientation/index.ts

Fix misuse of new event emitter API in useOrientation hook
Fix event emitter warning coming from useOrientation hook

Fix misuse of new event emitter API in useOrientation hook

---

generatedTypes/src/incubator/TextField/Presenter.d.ts
generatedTypes/src/incubator/TextField/usePreset.d.ts
src/incubator/TextField/Presenter.ts
src/incubator/TextField/__tests__/Presenter.spec.js
src/incubator/TextField/index.tsx

Fix an issue where TextField hint prop didn't show because it conflicted with the floating placeholder. 
Now it should work when the users pass floatingPlaceholder only if they also pass floatOnFocus
These examples can show the different variations 
```
<Incubator.TextField placeholder="Placeholder"/>
<Incubator.TextField useCustomTheme floatingPlaceholder={false} placeholder="Placeholder" hint="Helper"/>
<Incubator.TextField useCustomTheme floatingPlaceholder _floatOnFocus placeholder="Placeholder" hint="Helper"/>
<Incubator.TextField useCustomTheme floatingPlaceholder floatOnFocus placeholder="Placeholder" hint="Helper"/>
```
Fix issue with TextField hint is missing when using floatingPlaceholder (still requires to pass `floatOnFocus`)

Fix issue with TextField hint is missing when using floatingPlaceholder

---

generatedTypes/src/incubator/WheelPicker/index.d.ts
src/incubator/WheelPicker/index.tsx

WheelPicker - omitting 'color' from 'textStyle' to alert user that passing the 'color' here will not work.
WheelPicker - omitting 'color' from textStyle

WheelPicker - omitting 'color' from textStyle

---

demo/src/screens/componentScreens/ButtonsScreen.tsx
generatedTypes/src/components/button/ButtonTypes.d.ts
generatedTypes/src/components/button/index.d.ts
src/components/button/ButtonTypes.tsx
src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/button/__tests__/index.spec.js
src/components/button/button.api.json
src/components/button/index.tsx

Button - add hyperlink
Button - add hyperlink

Button - add hyperlink

---

demo/src/screens/incubatorScreens/IncubatorTextFieldScreen.tsx
generatedTypes/src/incubator/TextField/index.d.ts
generatedTypes/src/incubator/TextField/usePreset.d.ts
src/incubator/TextField/index.tsx

Support `dynamicFieldStyle` prop for Incubator.TextField
Support `dynamicFieldStyle` prop for Incubator.TextField (pass callback to `dynamicFieldStyle` instead of `fieldStyle` that now supports only static styles)

Support dynamicFieldStyle for Incubator.TextField

---

src/components/drawer/Swipeable.tsx

Drawer - fix leftToggle for RTL
Drawer - fix leftToggle for RTL

Drawer - fix leftToggle for RTL

---

generatedTypes/src/incubator/expandableOverlay/index.d.ts
src/components/picker/__tests__/index.spec.js
src/components/picker/index.js
src/incubator/expandableOverlay/index.tsx

- Fixed issue with editable prop not working on Picker component
- Added a render test to cover this bug
Fixed issue with `editable` prop not working on Picker component

Fix issue with editable prop not working on Picker component

---

src/incubator/WheelPicker/index.tsx
src/incubator/WheelPicker/usePresenter.ts

WheelPicker (incubator) - allow 'items' change; block 'onChange' call when 'initialValue' change.
WheelPicker (incubator) - allow 'items' change; block 'onChange' call when 'initialValue' change.

WheelPicker (incubator) - fix updates

---

demo/src/screens/incubatorScreens/IncubatorTextFieldScreen.tsx
generatedTypes/src/hooks/index.d.ts
generatedTypes/src/hooks/useMeasure/index.d.ts
generatedTypes/src/incubator/TextField/FloatingPlaceholder.d.ts
generatedTypes/src/incubator/TextField/usePreset.d.ts
src/hooks/index.ts
src/hooks/useMeasure/index.ts
src/incubator/TextField/FloatingPlaceholder.tsx
src/incubator/TextField/index.tsx

Fix issue with TextField floating placeholder offset when it includes a leading accessory 
Added a `useMeasure` hook to help with measurements of an element
Fix issue with TextField floating placeholder offset when it also has a leading accessory

Fix issue with TextField floating placeholder offset

---

src/incubator/TextField/index.tsx

Fix new ChipsInput broken layout by fixing how we render leadingAccessory in TextField
Im using clone element to avoid adding extra wrappers that breaks the layout
Fix new ChipsInput broken layout

Fix new ChipsInput broken layout

---

src/incubator/WheelPicker/__tests__/index.spec.js

WheelPicker - initialValue prop updates - adding render test
WheelPicker - initialValue prop updates - adding render test

WheelPicker - initialValue prop updates - adding render test

---

generatedTypes/src/incubator/TextField/useImperativeInputHandle.d.ts
src/incubator/TextField/Input.tsx
src/incubator/TextField/useImperativeInputHandle.ts

This is a hotfix for current release cycle 
Fix issue with RN TextInput's clear method doesn't trigger onChangeText
Fix issue with RN TextInput's clear method doesn't trigger onChangeText

Fix issue with RN TextInput clear doesn't trigger onChangeText

---

demo/src/screens/componentScreens/ImageScreen.tsx
generatedTypes/src/components/image/SvgImage.d.ts
src/components/image/SvgImage.tsx
src/components/image/index.tsx

Image - support SVG from uri
Ticket number: 2328
Image - support SVG from uri

Image - support SVG from uri

---

src/components/progressBar/index.tsx

This feature has been missed when we migrate to the public's ProgressBar
reference PR - https://github.com/wix-private/wix-react-native-ui-lib/pull/1936
WOAUILIB-2360
Fix RTL in ProgressBar

Fix/ ProgressBar RTL

---

generatedTypes/src/incubator/WheelPicker/index.d.ts
generatedTypes/src/incubator/index.d.ts
src/incubator/WheelPicker/index.tsx
src/incubator/WheelPicker/wheelPicker.api.json
src/incubator/index.ts

Add api json to Incubator.WheelPicker component
Also expose missing WheelPicker typings 
Add missing docs of Incubator.WheelPicker component and expose missing WheelPicker typings (WheelPickerItemProps, WheelPickerAlign)

Add api json to Incubator.WheelPicker component

---

src/incubator/TextField/Input.tsx

Add flexGrow to textField to keep it flexed even when in a row layout. 
Because elements lose their flexness when their are in a row layout, we must add the flexGrow
Fix TextField press area by keeping the input width flexed

Add flexGrow to textField to keep it flexed even when in a row layout

---

generatedTypes/src/components/slider/GradientSlider.d.ts
generatedTypes/src/components/slider/index.d.ts
src/components/slider/index.tsx

Add thumbHitSlop prop to Slider component (required for the AudioPlayer component)  
Only the first commit is a real change, the two others are for formatting and typings.
Add thumbHitSlop prop to Slider component

Feat/slider thumbHitSlop prop

---

README.md

Found more broken links and fixed them.
Fix more broken links in the main readme file

Fixed more broken links

---

demo/src/screens/incubatorScreens/IncubatorTextFieldScreen.tsx
generatedTypes/src/incubator/TextField/index.d.ts
generatedTypes/src/incubator/TextField/usePreset.d.ts
src/incubator/TextField/index.tsx

Support rendering a bottomAccessory (custom element) in Incubator.TextField
WOAUILIB-2355
Support rendering a bottomAccessory (custom element) in Incubator.TextField

Support rendering a bottomAccessory in TextField

---

src/components/gridView/index.tsx

In `GridView` the `rowCount` calculations are taken without the ceiling op. This in turn affects the `isLastRow` constant which applies the bottom margin. Without the change, bottom margin is incorrectly applied in some cases, see screenshots below.
GridView - Applied ceiling op to `rowCount` calculation

fix/ GridView - incorrect rowCount implies wrong margin

---

src/components/carousel/index.tsx

We found a rare issue where the Carousel component re-trigger an onLayout event (when being rendered inside a TabController page). 
The second onLayout event has containerWidth of `0` which break the functionality of Carousel's `snapToOffsets` feature. 
**This issue only happen on Android! ** 
MMV-232
Fix rare issue with Carousel on Android that can cause an exception

Fix issue with Carousel's containerWidth being reset

---

typings/components/Picker.d.ts

TypeScript currently warns that labelStyle is not a prop when used in Picker.Item, so this fixes that with the proper type.
**TypeScript:** Add proper `labelStyle` prop type for Picker.Item

TypeScript: Add labelStyle type for Picker.Item

---

demo/src/screens/MainScreen.js
demo/src/screens/componentScreens/ImageScreen.tsx
demo/src/screens/componentScreens/PickerScreen.js
demo/src/screens/componentScreens/SliderScreen.tsx
demo/src/screens/componentScreens/ToastsScreen.js
demo/src/screens/incubatorScreens/PanViewScreen.tsx
demo/src/screens/realExamples/ProductPage/index.tsx
expoDemo/MainScreen.tsx
generatedTypes/src/components/chip/index.d.ts
generatedTypes/src/components/icon/index.d.ts
src/components/card/index.tsx
src/components/chip/index.tsx
src/components/chipsInput/index.tsx
src/components/icon/icon.api.json
src/components/icon/index.tsx
src/components/picker/PickerModal.js
src/components/toast/index.js

Migrate to Icon component - WOAUILIB-2432
Migrate to Icon component

Infra/ Use Icon component for icons

---

generatedTypes/src/components/gridView/index.d.ts
src/components/gridView/gridView.api.json
src/components/gridView/index.tsx

Support renderCustomItem in GridView
Support  renderCustomItem prop in GridView

Support custom item render in GridView

---

src/components/tabController/TabPage.tsx

Remove TabController react-freeze optimization due to issues
Remove TabController react-freeze optimization due to issues

Remove optimization attempt with react-freeze in TabController.TabPage

---

generatedTypes/lib/components/Keyboard/KeyboardTracking/KeyboardTrackingView/index.d.ts
generatedTypes/src/incubator/ChipsInput/index.d.ts
lib/components/Keyboard/KeyboardTracking/KeyboardTrackingView/index.tsx
src/components/button/__tests__/index.driver.spec.js
src/incubator/ChipsInput/index.tsx

move `forwardRef` to wrap the component itself 
WOAUILIB-2242
Fix `forwardRef` warning

Fix/ forwardRef warning

---

generatedTypes/src/incubator/TextField/CharCounter.d.ts
generatedTypes/src/incubator/TextField/FloatingPlaceholder.d.ts
generatedTypes/src/incubator/TextField/TextField.driver.d.ts
generatedTypes/src/incubator/TextField/usePreset.d.ts
src/incubator/TextField/CharCounter.tsx
src/incubator/TextField/FloatingPlaceholder.tsx
src/incubator/TextField/TextField.driver.ts
src/incubator/TextField/__tests__/index.driver.spec.js
src/incubator/TextField/index.tsx
src/index.js
src/index.ts

Create test kit for TextField component using react-native/testing-library.
Use it to write tests for the TextField component
expose testkit for TextField

Create text field testkit

---

demo/src/screens/incubatorScreens/WheelPickerScreen.tsx
generatedTypes/src/incubator/WheelPicker/index.d.ts
generatedTypes/src/incubator/WheelPicker/usePresenter.d.ts
src/incubator/WheelPicker/__tests__/usePresenter.spec.js
src/incubator/WheelPicker/index.tsx
src/incubator/WheelPicker/usePresenter.ts

Deprecate Incubator.WheelPicker `selectedValue` prop in favor of `initialValue`
(All the relevant changes are in the first commit, the second is only about formatting) 
WOAUILIB-2308
BREAKING CHANGE - Deprecate Incubator.WheelPicker `selectedValue` prop in favor of `initialValue`

Infra/ Incubator.WheelPicker selectedValue

---

generatedTypes/src/components/svgImage/index.d.ts
generatedTypes/src/utils/imageUtils.d.ts
src/components/icon/index.tsx
src/components/image/index.tsx
src/components/svgImage/index.tsx
src/utils/imageUtils.ts

Add imageUtils file and use it in Image and Icon components
WOAUILIB-2456
Add imageUtils file and use it in Image and Icon components

Infra/ imageUtils

---

generatedTypes/src/components/skeletonView/index.d.ts
src/components/skeletonView/index.tsx
src/components/skeletonView/skeletonView.api.json

Support margin modifiers in SkeletonView
WOAUILIB-2175
Support margin modifiers in SkeletonView Component

support margin modifiers in SkeletonView

---

src/incubator/TouchableOpacity.tsx

Reanimated 2.4 - fix error in Incubator.TouchableOpacity
`Error: Interpolation input and output should contain at least two values.`
The user does not `have` to pass any color, and reanimated requires values in the interpolation, instead of skipping the interpolation I chose to initialize with `transparent`.
Reanimated 2.4 - fix error in Incubator.TouchableOpacity

Reanimated 2.4 - fix error in Incubator.TouchableOpacity

---

generatedTypes/src/incubator/TextField/usePreset.d.ts
generatedTypes/src/style/colors.d.ts
generatedTypes/src/style/colorsPalette.d.ts
generatedTypes/src/style/designTokensDM.d.ts
src/style/colors.ts
src/style/colorsPalette.ts
src/style/designTokens.ts
src/style/designTokensDM.ts

Move all colors and DesignTokens to public
Add `supportDarkMode` method to `Colors` class to allow enabling the dark mode tokens from private when the appearance changes 
WOAUILIB-2534
Move all colors and DesignTokens to public

Infra/ Move all colors and DesignTokens to public

---

src/components/tabController/TabBarItem.tsx

Avoid blocking TabBarItem re-onLayout callback
To reproduce (copy in playground) 
```
const twoItems = [
{label: 'February', key: 'feb'},
{label: 'April', key: 'apr'}
];
const threeItems = [
{label: 'February', key: 'feb'},
{label: 'March', key: 'mar'},
{label: 'April', key: 'apr'}
];
state = {
items: twoItems
};
onPress = () => {
this.setState({
items: this.state.items.length === 2 ? threeItems : twoItems
});
};
render() {
return (
<View bg-grey80 flex>
<View center padding-page>
<Button label="Change items" onPress={this.onPress}/>
</View>
<TabController items={this.state.items}>
<TabController.TabBar/>
</TabController>
</View>
);
}
}
```
Fix issue with TabController items not calculating their layout after change in items

Avoid blocking TabBarItem re-onLayout callback

---

eslint-rules/lib/rules/no-hard-coded-color.js
eslint-rules/package.json

eslint no-hard-coded-colors allow null
This is relevant for the `Icon Component Migration`
eslint no-hard-coded-colors allow null

eslint no-hard-coded-colors allow null

---

src/components/picker/new.tsx

Picker - spread others props to TextField instead of extracting manually
Picker - spread others props to TextField instead of extracting manually

Picker - spread others props to TextField instead of extracting manually

---

demo/src/screens/componentScreens/GridViewScreen.tsx
generatedTypes/src/components/gridView/index.d.ts
src/components/gridView/gridView.api.json
src/components/gridView/index.tsx

Fix issue #1879
- GridView throws an error when passing underfed to lastItemOverlayColor but still passing `lastItemLabel`
- I also removed old code that was copied from private that shouldn't be in the public version 
Fix issue #1879 - Fix error thrown by GridView when passing passing `lastItemLabel` but not `lastItemOverlayColor`

Fix issue with GridView lastItemOverlayColor error when undefined

---

src/utils/imageUtils.ts

SvgImage - add missing optional chaining
Should fix #1809
Fix #1809 - SvgImage - add missing optional chaining

SvgImage - add missing optional chaining

---

README.md
docuilib/docusaurus.config.js
docuilib/src/components/CustomLayout.tsx
docuilib/src/components/StandWithUkraine.module.scss
docuilib/src/components/StandWithUkraine.tsx
docuilib/src/pages/index.tsx

In this pull request, I have added a StandWithUkraine banner.
This PR is agreed with @guyca and @margalitis.

StandWithUkraine

---

generatedTypes/src/components/skeletonView/index.d.ts
src/components/skeletonView/index.tsx
src/components/skeletonView/skeletonView.api.json

Support passing colors to SkeletonView - https://github.com/wix/react-native-ui-lib/discussions/1762 
Support passing colors to SkeletonView

Feat/ support passing colors to skeletonView

---

generatedTypes/src/incubator/WheelPicker/index.d.ts
src/incubator/WheelPicker/index.tsx
src/incubator/WheelPicker/wheelPicker.api.json

Support `separatorsStyle` in WheelPicker - https://github.com/wix/react-native-ui-lib/discussions/1878
Support `separatorsStyle` in WheelPicker

Feat/ support separatorsStyle in WheelPicker

---

generatedTypes/src/components/hint/index.d.ts
generatedTypes/src/components/slider/context/asSliderGroupChild.d.ts
generatedTypes/src/components/slider/index.d.ts
src/components/hint/index.tsx
src/components/slider/context/asSliderGroupChild.tsx
src/components/slider/index.tsx

Migrate callback refs to object, to resolve TS errors
Migrate callback refs to object, to resolve TS errors

Fix/ migrate callback refs to object

---

generatedTypes/src/incubator/TextField/usePreset.d.ts
generatedTypes/src/style/colors.d.ts
generatedTypes/src/style/designTokens.d.ts
generatedTypes/src/style/designTokensDM.d.ts
src/style/designTokens.ts
src/style/designTokensDM.ts

Design Tokens - add backgroundInverted
This is for the Banner
Design Tokens - add backgroundInverted

Design Tokens - add backgroundInverted

---

generatedTypes/src/components/tabController/TabPage.d.ts
src/components/tabController/TabPage.tsx

We probably broke this prop during one of the component refactor and it stopped doing anything, so I reimplemented it
Support lazyLoadTime for TabController.TabPage component (useful for loading heavy pages)

Support old prop in TabPage - lazyLoadTime

---

eslint-rules/lib/rules/no-hard-coded-color.js

Colors lint rule - handle undefined context.options[0]
Colors lint rule - handle undefined context.options[0]

Fix/ colors lint rule

---

src/components/tabController/TabBar.tsx

Fix the fader color in dark mode TabBar 
Fix the fader color in dark mode TabBar

Fix/ add tintColor to tabbar gradient

---

demo/src/screens/componentScreens/BadgesScreen.tsx
src/components/badge/index.tsx

Badge - to design tokens
Badge - to design tokens

Badge - to design tokens

---

demo/src/screens/componentScreens/CheckboxScreen.tsx
src/components/checkbox/index.tsx

Checkbox - to design tokens
Checkbox - to design tokens

Checkbox - to design tokens

---

demo/src/screens/componentScreens/CardsScreen.tsx
src/components/card/index.tsx

Migrate Card component to designTokens
WOAUILIB-2594
Migrate Card component to designTokens

Infra/ migrate Card to designTokens

---

src/incubator/TextField/CharCounter.tsx
src/incubator/TextField/FieldContext.ts
src/incubator/TextField/FloatingPlaceholder.tsx
src/incubator/TextField/Input.tsx
src/incubator/TextField/Label.tsx
src/incubator/TextField/Presenter.ts
src/incubator/TextField/ValidationMessage.tsx
src/incubator/TextField/index.tsx
src/incubator/TextField/types.ts
src/incubator/TextField/useFieldState.ts
src/incubator/TextField/usePreset.ts

centralized all textfield types in a single file
centralized all textfield types

centralized all textfield types in a single file

---

demo/src/screens/componentScreens/ChipScreen.tsx
src/components/chip/index.tsx

migrate chip to designTokens
migrate chip to designTokens

Infra/ migrate chip to designTokens

---

demo/src/screens/componentScreens/DialogScreen.js
demo/src/screens/incubatorScreens/IncubatorDialogScreen.tsx
src/components/dialog/index.tsx
src/incubator/Dialog/DialogHeader.tsx
src/incubator/Dialog/HeaderContent.tsx
src/incubator/Dialog/helpers/useFadeView.tsx
src/incubator/Dialog/index.tsx
src/style/dividers.ts

Dialog - design tokens
Dialog - design tokens

Dialog - design tokens

---

demo/src/screens/componentScreens/HintsScreen.tsx
demo/src/screens/incubatorScreens/IncubatorToastScreen.tsx
src/components/hint/index.tsx

Hint and Toast - design tokens
Hint and Toast - design tokens

Hint and Toast - design tokens

---

src/style/colors.ts
src/style/scheme.ts

I added support for reading native colors using RN PlatfomColor API for loaded design tokens. 
This will only work when the user purposely enable this feature by calling `Colors.enabledPlatformColors`
The reason for that is that the users must load the relevant colors in their native code. 
For now, this will be false in the public code. 
We will enable this and load the platform colors in native only in private for now. 
Unfortunately, PlatformColor API is not so flexible, for instance I can't try/catch it and return the original JS color, like this
```
try {
return PlatformColor('$myToken');
} catch (error) {
return actualTokenValue;
}
```
Support using RN PlatformColor API for loaded design tokens

Support using PlatformColor for designTokens

---

src/components/tabController/TabBarItem.tsx

There's a bug when using a color that connected to a PlatformColor in useAnimatedStyle hook. 
I opened a issue here that explain it better https://github.com/software-mansion/react-native-reanimated/issues/3164
Anyway, for now, in order to resolve it, I clone the colors in the TabBarItem code. 
Fix usages of PlatformColor in TabController TabBaritem

Fix PlatfromColor issue in TabController.TabBarItem

---

src/style/colors.ts
src/style/scheme.ts

Support retrieving the original string value of color by its key
Good for need to make calculate on the color hex string and want to get it instead of the native platformColor
Added Colors.getColorValue - Support retrieving the original string value of color by its key

Support retrieving color JS value

---

demo/src/screens/componentScreens/AvatarsScreen.tsx
demo/src/screens/componentScreens/SliderScreen.tsx
demo/src/screens/incubatorScreens/IncubatorToastScreen.tsx
src/components/dateTimePicker/index.tsx
src/components/picker/PickerItem.tsx
src/components/picker/PickerItemsList.tsx
src/incubator/Dialog/DialogHeader.tsx
src/incubator/TextField/presets/default.ts
src/incubator/WheelPicker/index.tsx
src/style/designTokens.ts
src/style/designTokensDM.ts

Update outline design tokens
Update outline design tokens

Infra/ update outline design tokens

---

src/style/colors.ts
src/style/scheme.ts

I override the design token platform colors `toString` method to return the original string hex value. 
This way I can use it in the various color utils methods we have 
What's nice about it that a string variable always returns its string value when calling `toString` 
So for example if we call `Colors.getColorTint` with either a string or platfrom color object, we can call their `toString` to get the string hex value 
Fix how we handle platfrom color strings values

Override toString on our design token color

---

demo/src/screens/incubatorScreens/IncubatorTextFieldScreen.tsx
src/incubator/TextField/presets/default.ts

Handle borderColor styles of TextField in Android
This should solve error thrown in Android when passing a native platform color to TextInput's border color style
Handle borderColor styles of TextField in Android related to Platform Colors

Handle borderColor styles of TextField in Android

---

package.json
src/.babelrc.json

Remove babel plugin responsible for transforming TS types to React prop types. 
We needed that for the extractOwnProps which now we only use on the TextField component and TextField is the last component that still has prop types. 
So we don't need plugin anymore. 
Remove babel plugin responsible for transforming TS types to React prop types.

Remove babel plugin for prop types

---

demo/src/screens/incubatorScreens/IncubatorTextFieldScreen.tsx
src/incubator/TextField/presets/default.ts

Reverts wix/react-native-ui-lib#1961
Since the problem with platform colors and borderColor style prop is bigger than we thought there's no reason to fix it only here, so it's better reverting this change 
Reverts wix/react-native-ui-lib#1961

Revert - Handle borderColor styles of TextField in Android

---

src/incubator/WheelPicker/Item.tsx

Passing `platformColors` to reanimated `interpolateColors` resulting a bug (Incubator.WheelPicker)
Fix interpolateColor bug in Incubator.WheelPicker

Fix/ interpolateColor with platformColors

---

demo/src/screens/componentScreens/ActionBarScreen.tsx
demo/src/screens/componentScreens/SegmentedControlScreen.tsx
src/components/actionBar/index.tsx
src/components/segmentedControl/index.tsx
src/components/segmentedControl/segment.tsx

Migrate button components to design tokens
This is a new PR instead of https://github.com/wix/react-native-ui-lib/pull/1957
About your comments from the old PR: 
1. fixed.
2. we want the icon and the text to be in the same color, also I don't think it is worth adding a prop for that at that time.
3. fixed
4. it's because of the new scheme configuration, please set `currentScheme` to `'default'` in `scheme.ts` (line 11)
Migrate button components to design tokens

Infra/ migrate buttons to designTokens

---

lib/components/Keyboard/KeyboardInput/KeyboardAccessoryView.tsx

KeyboardAccessoryViewProps - fix 'onItemSelected' params for types.
KeyboardAccessoryViewProps - fix 'onItemSelected' params for types

KeyboardAccessoryViewProps - fix 'onItemSelected' params for types

---

src/components/image/index.tsx

Image - support size (width, height) modifiers on Android.
We should lookout for overflow bugs in the next release.
WOAUILIB-2310
Image - support size (width, height) modifiers on Android

Image - support size (width, height) modifiers on Android

---

src/incubator/TextField/index.tsx

In the case when the user pass `floatingPlaceholder` as false, empty `label` and validationMessagePosition as top 
The TextField "jumps" when it shows the validation message 
This PR fix it by retaining a space for this use case (we already doing it for the bottom validation message) 
WOAUILIB-2471
Fix TextField jumping issue when passing there's no label or floating placeholder and the validation message positioned at top

Retain TextField top validation message when needed

---

src/components/button/index.tsx

Button - support paddings modifier
WOAUILIB-2005
The original ticket was on `paddingH`, I don't see how this is useful since if the button is full width paddingH should not matter and with fixed width the only thing it can do is cut the text (unless it's some custom usage which I cannot think about ATM).
However vertical part can be supported, so I'll fix the modifier.
Button - support paddings modifier

Button - support paddings modifier

---

src/commons/withScrollEnabler.tsx

should prevent situations where a friction of pixel enables scroll and hence causes the scrollview-fader appear for no reason

not enable scroll if content is less than 1 pixel than it container

---

src/components/tabController/TabBar.tsx

TabController - allow sending faderProps
Fixes #1617
TabController - allow sending faderProps

TabController - allow sending faderProps

---

src/incubator/TextField/index.tsx
src/incubator/TextField/presets/default.ts
src/incubator/TextField/types.ts

Fix Incubator TextField placeholder's disabled color (when floating is also disabled).
There are 4 examples below, the 4th has a wrong color for the placeholder, this happens when both `floatingPlaceholder={false}` and  `editable={false}`.
Snippet:
```
<TextField migrate floatingPlaceholder editable placeholder="Placeholder"/>
<TextField migrate floatingPlaceholder editable={false} placeholder="Placeholder"/>
<TextField migrate floatingPlaceholder={false} editable placeholder="Placeholder"/>
<TextField migrate floatingPlaceholder={false} editable={false} placeholder="Placeholder"/>
```
Fix Incubator TextField placeholder's disabled color (when floating is also disabled).

Fix Incubator TextField placeholder's disabled color

---

demo/src/screens/componentScreens/ModalScreen.tsx
src/components/modal/TopBar.tsx
src/components/modal/api/modalTopBar.api.json

Support multiple buttons on Modal.TopBar
Add example to ModalScreen
WOAUILIB-2227
Support multiple buttons on Modal.TopBar

Feat/ support multiple buttons on Modal.TopBar

---

src/components/tabController/TabBar.tsx
src/components/tabController/TabBarItem.tsx
src/components/tabController/apis/tabBarItem.api.json

Fix TabBar backgroundColor
Fix TabBar backgroundColor

Fix/ TabBar backgroundColor

---

eslint-rules/lib/rules/function-deprecation.js
eslint-rules/tests/function_deprecation.json
eslint-rules/tests/lib/rules/function-deprecation.js
eslint-rules/tests/lib/rules/prop-value-shape-deprecation.js

eslint - function deprecation - fix usage from source
WOAUILIB-2588
eslint - function deprecation - fix usage from source

eslint - function deprecation - fix usage from source

---

src/components/carousel/CarouselPresenter.ts
src/components/carousel/index.tsx

Carousel - fix initial page offset (contentOffset)
WOAUILIB-2668
Generally I'd like to replace all `calcOffset` usages to the new `getContentOffset` (since `snapToOffsets` seem to have the correct data) but I fear of edge cases and bugs.
TBH, I think we should rewrite this component as a function component.
Testing snippet:
```
<Carousel
onChangePage={this.onChangePage}
pageWidth={249 + (Spacings.s5 * 2)}
itemSpacings={Spacings.s5}
initialPage={1}
containerStyle={{height: 160}}
>
{_.map([...Array(numberOfPagesShown)], (item, index) => (
<Page style={{backgroundColor: BACKGROUND_COLORS[index]}} key={index}>
<Text margin-15>CARD {index}</Text>
</Page>
))}
</Carousel>
...
page: {
flex: 1,
width: 249,
borderWidth: 1,
borderRadius: 8
}
```
Carousel - fix initial page offset (contentOffset)

Carousel - fix initial page offset (contentOffset)

---

demo/src/screens/nativeComponentScreens/keyboardAccessory/demoKeyboards.js
lib/components/Keyboard/KeyboardInput/KeyboardAccessoryView.tsx
lib/components/Keyboard/KeyboardInput/keyboardAccessoryView.api.json
lib/components/Keyboard/KeyboardTracking/KeyboardTrackingView/index.tsx
lib/components/Keyboard/KeyboardTracking/KeyboardTrackingView/keyboardTrackingView.api.json

KeyboardAccessoryView - 'iosScrollBehavior' prop deprecation
KeyboardAccessoryView - 'iosScrollBehavior' prop deprecation

KeyboardAccessoryView - 'iosScrollBehavior' prop deprecation

---

demo/src/screens/incubatorScreens/IncubatorDialogScreen.tsx
src/components/modal/index.tsx

Modal - support - KeyboardAvoidingView
It seems that there is a limitation for `KeyboardAvoidingView` in a `Modal` see this [SO answer](https://stackoverflow.com/a/65029356/4759619).
WOAUILIB-2719
This will allow using this in the `Incubator.Dialog`, not sure if we want to add support in the current `Dialog` or perhaps tell the user to use the new one.
Modal - support - KeyboardAvoidingView

Modal - support - KeyboardAvoidingView

---

src/services/LogService.ts

Add error support to LogService
Add error support to LogService

Add error support to LogService

---

src/components/wizard/WizardStates.ts
src/components/wizard/WizardStep.tsx
src/components/wizard/index.tsx

Design Tokens - Wizard
WOAUILIB-2724
Design Tokens - Wizard

Design Tokens - Wizard

---

src/components/sectionsWheelPicker/sectionsWheelPicker.api.json
src/incubator/WheelPicker/index.tsx

`Incubator.WheelPicker` did not allow changing the fader tint. Which makes it hard to style for Dark mode 
This PR allows users to pass in `tintColor` to the `Incubator.WheelPicker` and forward it to the `<Fader />` component.
- Allows to pass in `tintColor` to the `Incubator.WheelPicker` and forward it to the `<Fader />` component.

enh: allow Incubator.WheelPicker to take custom properties for the Fader

---

src/components/slider/index.tsx

Fix disabled slider border color - design tokens
Fix disabled slider border color - design tokens

Infra/ designTokens disabled Slider

---

demo/src/screens/nativeComponentScreens/keyboardAccessory/KeyboardAccessoryViewScreen.js
lib/components/Keyboard/KeyboardInput/KeyboardAccessoryView.tsx

KeyboardAccessoryView - fix 'addBottomView' not working ('useSafeArea' not passed to KeyboardTrackingView).
Solves issue #2034 
KeyboardAccessoryView - fix 'addBottomView' not working

KeyboardAccessoryView - fix 'addBottomView' not working

---

src/incubator/TextField/FieldContext.ts
src/incubator/TextField/index.tsx
src/incubator/TextField/types.ts
src/incubator/TextField/useFieldState.ts
src/incubator/TextField/useImperativeInputHandle.ts

Allow to call isValid on TextField ref to check if it's valid. 
Unlike the `validate` method, the `isValid` doesn't validate the field (which makes the validation message appear)
WOAUILIB-2757
Allow to call `isValid` on TextField ref to check if it's valid without triggering field validation

TextField - Support isValid ref method

---

demo/src/screens/componentScreens/TabControllerScreen/index.tsx
src/components/tabController/TabBarItem.tsx

This is a small improvement for performance in TabController component. 
In TabBarItem I replaced the `TouchableOpacity` with gesture-handler `Gesture` component. 
Instead of having a round trip (Native side -> JS side) to invoke the `onPress` callback in order to change the `currIndex` shared value, I now use the Gesture API to do that, this way we avoid the round trip. 
Small performance improvement in TabController transitions

Use Gesture to handle TabBarItem presses

---

lib/components/Keyboard/KeyboardInput/KeyboardAccessoryView.tsx
lib/components/Keyboard/KeyboardInput/KeyboardRegistry.ts
lib/components/Keyboard/KeyboardInput/keyboardAccessoryView.api.json
lib/components/Keyboard/KeyboardInput/keyboardRegistry.api.json
src/components/chipsInput/chipsInput.api.json
src/components/dateTimePicker/dateTimePicker.api.json
src/components/dateTimePicker/index.tsx
src/components/maskedInput/maskedInput.api.json
src/components/maskedInput/new.tsx
src/components/maskedInput/old.js
src/components/picker/PickerItem.tsx
src/components/picker/api/picker.api.json
src/components/picker/api/pickerItem.api.json
src/components/progressBar/index.tsx
src/components/progressBar/progressBar.api.json
src/components/text/index.tsx
src/components/text/text.api.json
src/incubator/Dialog/dialog.api.json

Some components in the docs have a broken link when clicking "code example"
- KeyboardAccessoryView
- KeyboardRegistry
- ChipsInput
- DateTimePicker
- MaskedInput
- Picker
- ProgressBar
- Text
- Incubator.Dialog

Docs - fix broken links

---

lib/package.json

Native lib - bumping version to reflect last fix (https://github.com/wix/react-native-ui-lib/pull/2045)
Native lib - bumping version to 3.0.8

Native lib - bumping version to 3.0.8

---

src/incubator/TextField/useFieldState.ts

Incubator.TextField - fix initial validity
In private `Form`, fields were starting with validity `true` although they are not valid, thus making the `Form` not change validity to `true` and notifying about it.
This change fixes the issue while still keeping visual validity to "true" unless `validateOnStart` is sent.
WOAUILIB-2835
Incubator.TextField - fix initial validity

Incubator.TextField - fix initial validity

---

src/components/chipsInput/index.tsx

Allow migration of ChipsInput's TextField
WOAUILIB-2818 (SearchInput uses the old ChipsInput which in turn uses the old TextField 🤷‍♂️)
Allow migration of ChipsInput's TextField

Allow migration of ChipsInput's TextField

---

src/components/picker/helpers/useImperativePickerHandle.ts

Handle Picker internal undefined ref when user pass custom `renderPicker`
Handle Picker internal undefined ref when user pass custom `renderPicker`

Handle undefined ref when user use renderPicker

---

src/commons/asBaseComponent.tsx
src/commons/modifiers.ts
src/components/view/index.tsx

Support passing asBaseComponent options to allow ignoring theme/modifiers support
It also allow passing modifier options so each component can decide which modifiers to calculate
Add support for passing options to asBaseComponent for optimizations

Support passing asBaseComponent options

---

src/helpers/Profiler.tsx
src/index.ts

Add Profiler
Usage:
```
<Profiler id={'TextField'}>
<TextField
migrate
placeholder={'Placeholder'}
floatingPlaceholder
enableError={false}
value={'Initial value'}
/>
</Profiler>
```
You'll get a log:
```
GROUP    mount
LOG    TextField : 69 69   // Actual Cumulative
GROUP    update              // render
LOG    TextField : 17 86   // Actual Cumulative
```
None

Add Profiler

---

src/components/colorSwatch/index.tsx
src/style/colorNameMap.ts

Add `accessibilityInfo` only if the accessibility mode is on
improves performance by ~71%
ColorSwatch - add `accessibilityInfo` only if the accessibility mode is on

Infra/ colorSwatch perf improvements 

---

lib/components/WheelPicker/index.tsx
src/components/wheelPickerDialog/index.js

WheelPicker - optionalDependencies error should only show on usage (only `WheelPickerDialog` uses the native `WheelPicker`)
WOAUILIB-2838
WheelPicker - optionalDependencies error should only show on usage

WheelPicker - fix optionalDependencies

---

src/incubator/TextField/FloatingPlaceholder.tsx
src/incubator/TextField/Label.tsx
src/incubator/TextField/ValidationMessage.tsx
src/incubator/TextField/index.tsx

memoize TextField inner components' style to avoid redundant renders
memoize TextField inner components' style to avoid redundant renders

memoize TextField inner components style to avoid redundant renders

---

src/components/image/index.tsx

Image - fix Android crash related to changing views while animating
WOAUILIB-2972
Relates to #1735
Image - fix potential Android crash related to changing views while animating (send useBackgroundContainer)

Image - fix Android crash related to changing views while animating

---

src/components/timeline/timeline.api.json

edited the timeline example url
fix timeline example url

Update timeline.api.json example url

---

src/components/colorPalette/index.tsx
src/components/colorPicker/index.tsx
src/components/colorSwatch/index.tsx

remove asBaseComponent from color components
Remove asBaseComponent from ColorSwatch, ColorPalette and ColorPicker

Infra/ remove asBaseComponent from color components

---

src/components/touchableOpacity/index.tsx

Avoid redundant setState in TouchableOpacity. 
We currently call setState to keep an "active" state for the color logic of activeBackgroundColor. 
I added a condition on this setState 
Avoid redundant setState in TouchableOpacity.

Avoid redundant setState in TouchableOpacity

---

src/components/colorPalette/index.tsx

The issues:
1. ColorPalette renders all the swatches on every swatch selection because it creates new refs every time.
2. The scrolling to the selected Swatch doesn't work (both for existing palettes with many colors and for the added color in a ColorPicker)
This PR fixes the two issues.
I used a hack for the scrolling - the offset of the last added color is bad (always 10) , so I calculate the one before the last and add the extra offset.
Let me know I you have any ideas (setTimeout doesn't fix anything),
Fix ColorPalette scrolling and extra renders

Fix/ ColorPalette scrolling and extra renders 

---

src/components/avatar/index.tsx

Fixed customRibbon props render in Avatar component
Fixed customRibbon props render in Avatar component

Split the renderRibbon to 2 render functions changed the logic

---

demo/src/screens/__tests__/AvatarScreen.spec.js
demo/src/screens/__tests__/__snapshots__/AvatarScreen.spec.js.snap
jest-setup.js
src/components/avatar/__tests__/index.spec.js
src/components/avatar/index.tsx
src/helpers/AvatarHelper.ts

Avatar - to function (performance)
I've added a snapshot test for the screen to verify I did not break anything, I figured we can keep it, WDYT?
I saw a significant performance improvement (15-20%) with my tests, please verify you see it too.
WOAUILIB-2913
Avatar - to function (performance)

Avatar - to function (performance)

---

src/incubator/TextField/FloatingPlaceholder.tsx

Fix initial animation state of TextField floating placeholder
When passing to TextField a value and enabling `floatingPlaceholder` you will see a bug where the placeholder animate on mount. 
This PR fix this issue by initializing the floating placeholder correctly. 
WOAUILIB-2905
Fix initial animation state of TextField floating placeholder

Fix initial animation state of TextField floating placeholder

---

src/components/view/index.tsx

require('react-native-reanimated') is not cheap, so it should be done only when necessary
Improve performance by avoiding optional import
Make View component slightly faster when not using `reanimated` prop

Only import 'react-native-reanimated' library when requested

---

.github/pull_request_template.md
CONTRIBUTING.md
demo/src/screens/MainScreen.js
package.json
src/components/animatedScanner/index.js
src/components/baseInput/index.tsx
src/components/carousel/types.tsx
src/components/image/index.tsx
src/components/maskedInput/old.js
src/components/picker/PickerDialog.android.js
src/components/textArea/index.js
src/components/textField/index.tsx
src/components/wheelPickerDialog/index.js

Since version 0.68 React Native started to warn that prop types will be removed from the core and in the latest 0.69 version (see [breaking change in the release notes](https://reactnative.dev/blog/2022/06/21/version-069#breaking-changes)) it happened. Which made ui-lib incompatible with latest RN.
In this PR I migrated all imports of prop types from RN to imports from `deprecated-react-native-prop-types`. This package doesn't provide typings and there seem to be no `@types/` version of it available, so I went with `// @ts-expect-error` for imports, let me know if you prefer some other alternative (writing proper custom types seemed to be quite a huge effort).
And I fixed 2 typos in markdown files.
resolves #2126 
resolves #2094 
* Migrate PropTypes imports to …

Migrate to deprecated-react-native-prop-types package

---

scripts/buildPackages.js

Typescript `.d.ts` files are no longer generated in the `generatedTypes` directory, but are generated alongside the source files since #1927 was merged.
This resulted in standalone components not being typed properly as the types it is attempting to import no longer exists.
This PR changes the import directory for the generated `.d.ts` files for standalone components to `./src` to fix this issue.
Tested the changes by running `yarn build` and ensuring the generated `.d.ts` files for standalone components now actually resolve correctly.
Fix typing issue for standalone components

Fix typing issue for standalone components

---

demo/src/screens/componentScreens/TabControllerScreen/index.tsx
src/components/tabController/index.tsx
src/components/tabController/useImperativeTabControllerHandle.ts
src/index.ts

Create an imperative API for TabController for setting tab imperatively
Create an imperative API for TabController for setting tab imperatively

Create an imperative API for TabController for setting tab imperatively

---

docuilib/package.json
docuilib/src/components/MainSection.tsx
docuilib/src/pages/index.tsx

We set our stars count in our docs manually (through the docs config)
I changed it to fetch stars count from repo info
Docs - get stars count from github repo info

Fetch stars count from repo

---

demo/src/screens/__tests__/__snapshots__/AvatarScreen.spec.js.snap
src/components/animatedImage/index.tsx

AnimatedImage - move from LayoutAnimation to AnimationStyle
This is done so we can stop the animation when we choose to (i.e. remove the loader).
AnimatedImage - move from LayoutAnimation to AnimationStyle

AnimatedImage - move from LayoutAnimation to AnimationStyle

---

demo/src/demoApp.js

Fix demo app colors for dark mode
Fix demo app colors for dark mode

Fix/ demo app colors

---

src/components/picker/types.tsx

Fix missing useCustomTheme type in Picker after Picker refactor (removing asBaseComponent)
N/A

Fix missing useCustomTheme type in Picker

---

src/style/shadows.ts

Shadows in dark mode
Shadows in dark mode

shadows in dark mode

---

demo/src/screens/componentScreens/SliderScreen.tsx
src/components/slider/GradientSlider.tsx
src/components/slider/Thumb.tsx
src/components/slider/index.tsx
src/components/slider/slider.api.json

Slider - Adding 'reset' function with callback 'onReset', initial values to range slider, 'useGap' prop.
Slider - Adding 'reset' function with callback 'onReset', initial values to range slider, 'useGap' prop.

Slider - new features

---

src/components/card/index.tsx

Fix selected card iconColor (set tintColor to ignore the default coloring of the private Icon config)
to test it you should run private on the `darkMode` branch
WOAUILIB-3064
Fix selected card iconColor

Fix selected card iconColor

---

.gitignore
package.json
scripts/createLocalPackage.sh

Add a script to build changes locally.
Usage:
1. `npm run build:local`
2. Extract `react-native-ui-lib-5.0.0.tgz` (preferably in another location).
3. Replace `react-native-ui-lib` in your `node_modules` (probably backup or delete your current `node_modules/react-native-ui-lib`).
4. Delete `react-native-ui-lib-5.0.0.tgz`.
5. `package.json` will change, take extra care if you have changes there.
Note: I've added a warning if the user has untracked files (which will be deleted without this).
CC @Inbal-Tish @lidord-wix @adids1221 
None

Add build:local script

---

src/components/dateTimePicker/index.tsx

DateTimePicker - add default `themeVariant` for dark mode support
to check that toggle between dark mode and light mode without changing the scheme in the `Config.ts` file 
DateTimePicker - add default `themeVariant` for dark mode support

set default themeVariant in DateTimePicker

---

src/components/modal/index.tsx
src/incubator/expandableOverlay/index.tsx

Fix modal bg color
Fix modal bg color

fix modal bg color

---

src/components/expandableSection/expandableSection.api.json
src/components/expandableSection/index.tsx

ExpandableSection support using a separator when expanded, feature for List.CollapsableItem
ExpandableSection support using a separator when expanded, feature for List.CollapsableItem

ExpandableSection support using separator when expanded

---

src/incubator/TextField/Presenter.ts

TextField presenter now supports design tokens.
TextField presenter now supports design tokens.

Fixed textField placeholder color, support in design token

---

src/style/__tests__/colors.spec.js
src/style/colors.ts
typings/generatedTypes/colors.d.ts

* My current guild week task is to [create a util for generating design tokens](https://jira.wixpress.com/browse/WOAUILIB-2550). Added a util method to `Colors` class, since that method depends mostly on other `Colors` class method.
* Added `generateTokens` method for generating design tokens based on chosen color.

[Guild Week] Added generator for basic design tokens

---

src/components/view/index.tsx

View - prioritize backgroundColor prop over bg modifiers
This change is required for WOAUILIB-2781:
Assume that the user renders `<View bg-$backgroundPrimaryHeavy/>`  inside a theme context, we calculate the theme color (in the config) and pass it as a background prop from the config, but it's overridden by the `bg-$backgroundPrimaryHeavy` so it won't get the theme color but the blue primary. 
View - prioritize backgroundColor prop over bg modifiers

Feat/ prioritize backgroundColor prop over bg modifiers

---

src/incubator/TextField/Presenter.ts
src/style/__tests__/colors.spec.js
src/style/colors.ts

TextFiled Presenter getColorByState fix, new util function isDesignToken.
TextFiled Presenter getColorByState fix, new util function isDesignToken.

TextFiled Presenter getColorByState fix

---

package.json

Lock RNN to 7.29.0 to fix Android build
Lock RNN to 7.29.0 to fix Android build

Lock RNN to 7.29.0 to fix Android build

---

src/style/__tests__/colors.spec.js
src/style/colors.ts

Fix Colors.loadDesignTokens API
@Effanuel FYI - we decided to change the API a bit to support adding features in the future easily  
Fix Colors.loadDesignTokens API

Fix/ loadDesignTokens API

---

src/components/dash/dash.api.json
src/components/dash/index.tsx
src/components/timeline/Line.tsx

Dash - change props names and add api json. Instead of prop names dashXXX I removed the prefix dash and kept the prop name clean.
Dash - change props names and add api json.

Dash - change props names and add api json

---

src/incubator/Dialog/index.tsx

Incubator.Dialog - do not show header if no `headerProps` are sent
Incubator.Dialog - do not show empty header (with only knob and divider)

Incubator.Dialog - do not show empty header

---

src/components/expandableSection/expandableSection.api.json
src/components/expandableSection/index.tsx

ExpandableSection revert, removed useSeparator prop.
The old [PR](https://github.com/wix/react-native-ui-lib/pull/2279/files).
ExpandableSection revert, removed useSeparator prop.

revert ExpandableSection, removed useSeparator prop

---

src/incubator/Dialog/index.tsx

Incubator.Dialog - allow changing pointerEvents in children
This is for the CustomDialog's `Close` button.
Incubator.Dialog - allow changing pointerEvents in children

Incubator.Dialog - allow changing pointerEvents in children

---

src/incubator/TextField/CharCounter.tsx

Incubator.TextField - fix short text when wrapped with a centered container
Code example:
```
import _ from 'lodash';
import {StyleSheet} from 'react-native';
import {View, Text, Card, TextField, Button} from 'react-native-ui-lib'; //eslint-disable-line
render() {
return (
<View bg-grey80 padding-20 center>
<TextField
migrate
marginT-16
placeholder="Enter confirmation code"
floatingPlaceholder={false}
showCharacterCounter
centered
validate={'number'}
validationMessage={'Blaaa blaa bla'}
validateOnChange
maxLength={6}
/>
</View>
);
}
}
const styles = StyleSheet.create({
container: {}
});
```
Incubator.TextField - fix short text when wrapped with a centered container

Fix short text when wrapped with a centered container

---

demo/src/screens/componentScreens/PickerScreen.tsx
src/components/picker/helpers/usePickerMigrationWarnings.tsx
src/components/picker/types.tsx

useNativePicker prop leads to using our old TextField and we want to deprecate it and use `useWheelPicker` prop instead
I also added this deprecation in our v7 sheet
Start deprecation of useNativePicker in favor of useWheelPicker

Start deprecation of Picker useNativePicker prop

---

src/style/colors.ts

getTintColor support options object with should reverse on dark prop.
getTintColor support options object with should reverse on dark prop for the new Loader logic - Theme preset.

getTintColor support options, should reverse on dark prop

---

demo/src/screens/componentScreens/MarqueeScreen.tsx

Marquee screen now has a scroll view.
Marquee screen now has a scroll view.
The screen does not fit the private demo app.

Fix marquee screen now have scroll view

---

demo/src/screens/componentScreens/GridViewScreen.tsx
lib/components/WheelPicker/index.tsx
src/components/chipsInput/Presenter.ts
src/components/chipsInput/index.tsx
src/components/drawer/index.tsx
src/components/hint/__tests__/index.spec.tsx
src/components/hint/index.tsx
src/components/loaderScreen/index.tsx
src/components/modal/TopBar.tsx
src/components/modal/api/modalTopBar.api.json
src/components/pageControl/index.tsx
src/components/pageControl/pageControl.api.json
src/components/radioButton/radioButton.api.json
src/components/stateScreen/index.tsx
src/components/tabBar/TabBarItem.tsx
src/components/tabController/apis/tabBarItem.api.json
src/components/textField/index.tsx
src/components/toast/index.js
src/components/wheelPickerDialog/index.js
src/style/componentsColors.ts
src/style/themeManager.ts

Remove `Colors.primary` usage
WOAUILIB-2547
Remove `Colors.primary` usage

Infra/ remove Colors.primary usage

---

demo/src/screens/componentScreens/ColorPickerScreen.tsx
src/components/colorPalette/index.tsx
src/components/colorPicker/index.tsx

ColorPicker now supports backgroundColor prop.
ColorPicker now supports backgroundColor prop.

ColorPicker now support backgroundColor prop

---

src/components/floatingButton/index.tsx

Fix the FloatingButton outline mode background color on Android.
In Android, the shadows style painted the background using FloatingButton in outline mode.
Fix the FloatingButton outline mode background color on Android.

Fix floating button outline background color android issue

---

src/components/picker/index.tsx
src/incubator/TextField/index.tsx

Fix how we render `children` in TextField component. 
This should fix an issue we have in Picker (filter fieldType) that use TextField's children prop. 
This replace the Input container so there's weird flex behaviors
Fix Picker's filter fieldType layout by fixing how we render `children` prop in TextField

Fix how we render TextField children

---

src/incubator/TextField/FloatingPlaceholder.tsx
src/incubator/TextField/Presenter.ts
src/incubator/TextField/index.tsx
src/incubator/TextField/types.ts

Incubator.TextField - FloatingPlaceholder should float with defaultValue
Adding `shouldFloat` and fixing its logic
WOAUILIB-3123
Handling edge cases, using the below `PlaygroundScreen`:
1. Switching between `TextField`s should:
a. float\un-float if both are empty
b. float\un-float on an empty one and remain un-floated on one with a `value` \ `defaultValue`
2. Changing `defaultValue` should affect the floating status
3. Deleting the `defaultValue` (to an empty `value`) should un-float
```
import {View, Text, Card, Incubator, Button} from 'react-native-ui-lib';
state = {
defaultValue: 'initial value'
};
render() {
return (
<View bg-grey80 flex padding-20>
<View marginT-20>
<Incubator.TextField …
```

Incubator.TextField - should float with defaultValue

---

src/style/__tests__/colors.spec.js
src/style/colors.ts

getSystemColorByHex now has options object with validColors
getSystemColorByHex now has options object with validColors instead of passing validColors array.

getSystemColorByHex now have options object with validColors

---

demo/src/screens/componentScreens/SectionsWheelPickerScreen.tsx
src/components/sectionsWheelPicker/index.tsx
src/incubator/WheelPicker/Item.tsx
src/incubator/WheelPicker/index.tsx

Add RTL support (and disableRTL support) to WheelPicker and SectionsWheelPicker.
Also added an example to the SectionsWheelPicker example screen to show this new feature on RTL. (and to make sure it works 😇) 
This PR is an infrastructure to support WOAUILIB-3027
Add RTL support (and disableRTL support) to WheelPicker and SectionsWheelPicker.

WheelPicker + SectionsWheelPicker - RTL support

---

src/commons/asBaseComponent.tsx
src/commons/modifiers.ts
src/components/avatar/index.tsx
src/components/numberInput/index.tsx
src/components/picker/index.tsx
src/hooks/useThemeProps/index.ts

NumberInput - support theme and generify useThemeProps
When adding `useThemeProps` to `NumberInput` I've noticed that the props are not being used (I had a ` // @ts-expect-error` which was supposedly fixed when it should not have been), so I added generics to `useThemeProps`; I've fixed some errors and ignored one in `asBaseComponent`.
⚠️ NumberInput - support theme and generify useThemeProps

NumberInput - support theme and generify useThemeProps

---

demo/src/screens/incubatorScreens/IncubatorTextFieldScreen.tsx
src/components/numberInput/index.tsx
src/incubator/TextField/index.tsx
src/incubator/TextField/textField.api.json
src/incubator/TextField/types.ts

Fix flex issue of TextField when rendered by passing flexG to the input container. 
I added a note there that this will bring back a known issue with trailing accessory being pushed, but the flex issue is worse. 
Fix #2389 2389
Fix flex issues with TextField when rendered in a row container

Fix flex issue of TextField when rendered

---

webDemo/webpack.config.js

webDemo app error fix.
webDemo app `react-native-colors` error fix by adding the repo path to the `webpack` config file.

Fix react-native-colors error when start the webDemo app

---

src/incubator/TextField/Input.tsx

TextField - fix web style 
TextField - fix web style

Fix/ add webStyle to TextField

---

src/incubator/TextField/index.tsx

When passing `centered` to TextField it flexes the validation message element and in some layouts it stretches the whole field
Fix flex issue in TextField validation message when passing centered

Remove flex from TextField validation message in centered mode

---

src/components/avatar/index.tsx

Avatar - don't render ribbon when there's a custom ribbon
(the bug is visible on the private's avatar screen, on master, and on production) 
Avatar - don't render ribbon when there's a custom ribbon

Fix/ Avatar renderRibbon

---

package.json
src/incubator/TextField/useFieldState.ts
webDemo/src/App.tsx

Fix bug: validatingOnChange executed on start when providing defaultValue
Fix: validatingOnChange executed on start when providing defaultValue

fix: TextField validateOnChange with defaultValue executed on start

---

package.json

Version bump fixes transparent SVG's paths. Currently paths without **fill** property are rendered transparent instead of black (browsers fallbacks to black in this case). In updated version this bug has been fixed with this PR: https://github.com/software-mansion/react-native-svg/pull/1947
Bumped react-native-svg package

Bump SVG package

---

src/components/touchableOpacity/index.tsx

When pressing on TouchableOpacity it ignores the event and pass only the props.
Fix: Don't ignore the event passed to TouchableOpacity onPress

fix: touchable opacity ignores event on press

---

src/components/picker/helpers/usePickerLabel.tsx
src/components/picker/index.tsx

Currently `usePickerLabel` is ignoring accessibility props supplied by the user.
WOAUILIB-3351
Picker - do not ignore accessibility props

Picker - do not ignore accessibility props

---

src/components/sortableList/SortableList.api.json

SortableList - add note to docs about missing items
Relates to WOAUILIB-3327
SortableList - add note to docs about missing items

SortableList - add note to docs about missing items

---

src/services/LogService.ts

I refactored our LogService to be a Class 
And also added support to inject a generic BI logger. This is order to support BI events in our components 
Support injecting a BI logger in our LogService

Add support to inject BI logger to our LogService

---

jest-setup.js
src/incubator/Dialog/__tests__/index.spec.tsx
src/incubator/Dialog/index.tsx
src/incubator/hooks/useHiddenLocation.ts
src/testkit/drivers/TestingLibraryDriver.tsx
typings/global.d.ts

All changed in this PR are required for this to work except this one:
```
if (!modalVisibility) {
return null;
}
```
Added `typings/global.d.ts` to solve a TS error (it is not exported); we can add an ignore if you prefer.
Incubator.Dialog - support headless tests

Incubator.Dialog - allow headless testing mocking

---

src/components/touchableOpacity/index.tsx
webDemo/src/examples/Picker.tsx

touchable opacity `onLongPress` handler pass also event, and `onPressIn` & `onPressOut` also pass it when no customValue.
fix TouchableOpacity press handlers typing

fix: touchable opacity press handlers typing

---

src/components/checkbox/index.tsx
src/components/radioButton/index.tsx

Checkbox + RadioButton - fix long labels are stretching outside their container
Checkbox + RadioButton - fix long labels are stretching outside their container

Checkbox + RadioButton - fix long labels are stretching outside

---

scripts/buildPackages.js
scripts/buildPackages/buildComponentsPackages.js
scripts/buildPackages/buildCustomPackages.js
scripts/buildPackages/index.js

TextField package should `TextFieldMigrator` instead of `index.ts`
TextField package exports TextFieldMigrator instead of index

fix: TextField package exports TextFieldMigrator

---

src/incubator/TextField/ValidationMessage.tsx

Incubator.TextField - handle long validationMessage with char count
Use the following example to reproduce:
```
<TextField
placeholder={'bla'}
migrate
showCharCounter
maxLength={100}
validateOnStart
validate={['required']}
validationMessage={['Really long validation message with character counter nearby it']}
/>
```
WOAUILIB-3387
Incubator.TextField - handle long validationMessage with char count

Incubator.TextField - handle long validationMessage with char count

---

src/components/drawer/index.tsx

A broken link to [React Native Gesture Handler](https://docs.swmansion.com/react-native-gesture-handler/) is fixed.
Drawer component
---------
Before:
After:

Fixes broken link :: React Native Gesture Handler

---

src/components/touchableOpacity/index.tsx
src/components/touchableOpacity/touchableOpacity.api.json

change the way we forward the event to onPress and onLongPress handler to send event along with props, instead spreading the event together with props
refactor TouchableOpacity forwarding event on onPress and onLongPress

refactor TouchableOpacity forwarding event on onPress and onLongPress

---

demo/src/screens/incubatorScreens/IncubatorTextFieldScreen.tsx
src/incubator/TextField/FieldContext.ts
src/incubator/TextField/Input.tsx
src/incubator/TextField/Label.tsx
src/incubator/TextField/Presenter.ts
src/incubator/TextField/TextField.driver.ts
src/incubator/TextField/__tests__/index.driver.spec.tsx
src/incubator/TextField/index.tsx
src/incubator/TextField/presets/default.ts
src/incubator/TextField/textField.api.json
src/incubator/TextField/types.ts

Incubator.TextField - add readonly state
Main PR for WOAUILIB-3345
Incubator.TextField - add readonly state

Incubator.TextField - add readonly state

---

src/components/drawer/drawer.api.json
src/components/drawer/index.tsx

Drawer - remove leftToggleHapticTrigger prop
Please review by commits, the second one is only formatting
Drawer - remove leftToggleHapticTrigger prop

V7/ remove leftToggleHapticTrigger drawer

---

src/testkit/UniDriver.ts
src/testkit/drivers/TestingLibraryDriver.tsx

`press` is actually a synchronous and not asynchronous function.
To see the errors run:
`jest -- src/incubator/Dialog/__tests__/index.spec.tsx`
None

Press is actually sync

---

src/components/colorPicker/index.tsx

ColorPicker - deprecate 'style' prop.
ColorPicker - deprecate 'style' prop.

Remove 'style' prop from ColorPicker

---

src/incubator/toast/index.tsx

Incubator Toast  - zIndex set to 100 as default when using Android
Incubator Toast  - zIndex set to 100 as default when using Android

Incubator Toast zIndex set to 100 as default when using Android

---

src/style/__tests__/colors.spec.js
src/style/colors.ts
src/style/colorsPalette.ts

Deprecate `Colors.primary`
Colors - `Colors.primary` is deprecated. please use the primary tokens instead

V7 primary colors

---

demo/src/screens/componentScreens/TabControllerScreen/index.tsx
src/components/tabController/TabBar.tsx
src/components/tabController/TabBarContext.ts
src/components/tabController/apis/tabController.api.json
src/components/tabController/index.tsx
typings/incubator/index.d.ts

TabController - remove 'selectedIndex' prop
TabController - remove 'selectedIndex' prop (use 'initialIndex' instead)

V7_TabController - remove 'selectedIndex' prop

---

src/components/radioButton/index.tsx
src/components/radioButton/radioButton.api.json

RadioButton - deprecate contentOnRight prop
RadioButton - deprecate contentOnRight prop

V7/ radio button content on right

---

src/components/avatar/index.tsx

Avatar - deprecate `imageSource` prop (new prop is `source`)
Avatar - deprecate `imageSource` prop (new prop is `source`)

V7/ deprecate imageSource of Avatar

---

src/components/skeletonView/index.tsx

Remove some Skeleton props
Remove some (deprecated) Skeleton props

Remove some Skeleton props

---

src/components/dateTimePicker/index.tsx

Enable text field migration by default in DateTimePicker
Enable text field migration by default in DateTimePicker

V7 date time picker

---

lib/components/Keyboard/KeyboardInput/KeyboardAccessoryView.tsx

V7_KeyboardAccessoryView - remove 'iOSScrollBehavior' prop and 'iosScrollBehaviors' enum
V7_KeyboardAccessoryView - remove 'iOSScrollBehavior' prop and 'iosScrollBehaviors' enum (use 'scrollBehavior' prop instead and pass it 'Keyboard.KeyboardAccessoryView.scrollBehaviors' )

V7_KeyboardAccessoryView - remove 'iOSScrollBehavior' prop

---

docs/foundation/colors.md

Docs - update Colors page
Docs - update Colors page

V7/ update colors docs

---

src/components/textField/TextFieldMigrator.tsx
src/incubator/TextField/index.tsx
src/incubator/TextField/types.ts
src/incubator/index.ts
src/index.ts

Fix migration of TextField errorMessage prop
Fix validationMessagePosition type to support literal strings
Add migration to TextField errorMessage and fix validationMessagePosition type

Add migration to TextField errorMessage and fix validationMessagePosition type

---

demo/src/screens/incubatorScreens/IncubatorSliderScreen.tsx
src/incubator/Slider/Thumb.tsx
src/incubator/Slider/index.tsx

Incubator.Slider - fix active track when thumb overlapping.
Incubator.Slider - fix active track when thumb overlapping.

Incubator slider - fix overlapping thumbs

---

README.md
demo/package.json
demo/src/index.js
demo/src/screens/realExamples/ProductPage/index.tsx
expoDemo/app.json
expoDemo/metro.config.js
expoDemo/package.json

- Update dependence for expoExample
- Update make some example ready
+  Update dependence for expoExample for compatible with the last expo (v48)
> - Update to make some screen available in example
> - DarkMode
> - ScrollBar
> - Marquee
> - NumberInput
> - WheelPicker
> - GridList]
> - SortableGridList
> - IncubatorSlider
> - IncubatorDialog
> - IncubatorToast
> - IncubatorExpandableOverlay
> - Modal
> - Timeline
> - WithScrollEnabler
> - WithScrollReached
> - Fader
> - GridView
> - Playground
> - KeyboardAwareScrollView
+ Fix warning when upgrade to v7 in Product Page

Chore/upgrade demo sdk 48.0.4 #2306

---

src/style/colors.ts

We have a use case where we want to check if a color is (very) dark. 
So I add a new argument for Colors.isDark to pass the dark threshold 
Support passing dark threshold to Colors.isDark

Support passing dark threshold for Colors.isDark

---

src/incubator/Dialog/DialogHeader.tsx

There's an error when passing both the `title` and `subtitle` and one of them is an empty string
to reproduce, change the `headerProps` in the `incubatorDialogScreen` to `{title: 'Title (swipe here)', subtitle: ''};`
Fix new DialogHeader titles

Fix/ New DialogHeader conditions

---

src/components/skeletonView/index.tsx

ShimmerPlaceholder and the View wrapper now have different testID's.
ShimmerPlaceholder and the View wrapper now have different testID's.

Change the View wrapper testID

---

demo/src/demoApp.js
demo/src/screens/MainScreen.js
demo/src/screens/SettingsScreen.js
demo/src/storage.ts
package.json
src/commons/Config.ts
src/optionalDependencies/AsyncStoragePackage.ts
src/optionalDependencies/index.ts
src/optionalDependencies/index.web.ts

Move to react-native-mmkv (version `2.6.1` is required for RN71).
Also fixes `SettingsScreen` - it seems setting the screen from there does not work ATM
WOAUILIB-3450
⚠️ Move to react-native-mmkv (BREAKING CHANGE - remove some functionality from `Config`).

Move to react-native-mmkv

---

src/components/text/index.tsx
src/incubator/TextField/Input.tsx

Fix crash on Android following RN71 (flex shadow node)
This currently breaks at least one screen (NumberInputScreen)
⚠️ Fix crash on Android following RN71 (flex shadow node)

Fix crash on Android following RN71 (flex shadow node)

---

src/components/picker/PickerItem.tsx
src/components/picker/types.tsx

`PickerItem` in multi mode - send selected to `onPress`
Part of WOAUILIB-3429
`PickerItem` in multi mode - send selected to `onPress`

PickerItem in multi mode - send selected to onPress

---

src/components/text/index.tsx
src/incubator/TextField/Input.tsx

Temporarily omit alignment props (top, left, right, bottom) from being passed on to Text and TextInput components. 
This is due an issue with Android crashing when these props are passed. 
The ideal solution is to remove these typings all together, unfortunately because of how we handle modifiers typings, we allow all boolean props
Omit alignment props (top, left, right, bottom) from being passed on to Text and TextInput components to avoid a crash on Android (RN71)

Omit alignment props from passing forward to Text and TextInput components

---

docs/getting-started/v7.md

Both TextField and Wheelpicker have wrong links on docs, this PR fixes it
Fixed Paths on migrating guide: TextField and WheelPicker

Fix: Paths on migrating guide: text input and wheel picker

---

src/components/chip/index.tsx

Changed `marginHorizontally` to `marginHorizontal` to fix warning: 
> Failed %s type: %s%s, prop, Invalid props.style key `marginHorizontally` supplied to `Text`
Fixed margin for Chip component when both leftElement and rightElement are provided.

Fix/Chip - typo in src/components/chip/index.ts

---

src/components/sortableList/SortableListItem.tsx
src/incubator/Slider/SliderPresenter.ts
src/incubator/Slider/index.tsx
src/utils/index.ts
src/utils/styleUtils.ts

Use unpack style util for SortableListItem component. 
We spread the shadow object inside useAnimatedStyle which usually throw errors from Reanimated. 
Using the unpack logic fix that (we already use it in the new Slider component)
Use unpack style util for SortableListItem component shadows issue.

Use unpack style for SortableListItem component

---

src/components/dateTimePicker/index.tsx

Added testID to DateTimePicker components.
Added testID to DateTimePicker components.

Added testID to DateTimePicker

---

src/components/card/CardSection.tsx

This "extra shadow" can be seen in the `CardsScreen` if the following line is removed from `Card.index` (see image below):
```
return this.styles.containerShadow;
```
WOAUILIB-3427
Remove Card.Section extra (visible) border

Remove Card.Section extra (visible) border

---

src/components/actionSheet/index.tsx

Support labelStyle in ActionSheet options
resolves https://github.com/wix/react-native-ui-lib/issues/2550
Support labelStyle in ActionSheet options

Feat/ support labelStyle in ActionSheet options

---

GestureDetectorMock.tsx
jest-setup.js
src/components/button/Button.driver.ts
src/components/sortableList/SortableListItem.driver.ts
src/components/sortableList/__tests__/index.spec.tsx
src/incubator/Dialog/__tests__/index.spec.tsx
src/testkit/Component.driver.ts
src/testkit/UniDriver.ts
src/testkit/drivers/TestingLibraryDriver.tsx
src/testkit/index.ts

SortableList - add driver and test
WOAUILIB-3444
SortableList - add driver and test

SortableList - add driver and test

---

demo/src/screens/componentScreens/SegmentedControlScreen.tsx
src/components/segmentedControl/index.tsx
src/components/segmentedControl/segment.tsx
src/components/segmentedControl/segmentedControl.api.json

SegmentedControl - add segmentStyle prop (and update example)
https://github.com/wix/react-native-ui-lib/discussions/2495
SegmentedControl - add segmentStyle prop

Add segmentStyle prop to SegmentedControl

---

src/components/sortableList/index.tsx

mobile mocks has a mock to trigger on layout, but it has no data so we're ending up with a `NaN` here.
SortableList - newHeight in tests

SortableList - newHeight in tests

---

src/incubator/Dialog/__tests__/index.spec.tsx
src/incubator/Dialog/index.tsx

Incubator.Dialog - fix RN Modal native calls on RN71
Incubator.Dialog - fix RN Modal native calls on RN71

Incubator.Dialog - fix RN Modal native calls on RN71

---

src/components/WheelPicker/index.tsx
src/components/WheelPicker/wheelPicker.api.json

WheelPicker missing data in Android bug fix, passing `maxToRenderPerBatch` to the `FlatList` when using Android.
WheelPicker missing data in Android bug fix, passing `maxToRenderPerBatch` to the `FlatList` when using Android.
Solve [RN FlastList issue](https://github.com/facebook/react-native/issues/15990).
`WOAUILIB-3440`

fix wheelpicker in android

---

demo/src/screens/componentScreens/SortableListScreen.tsx
demo/src/screens/incubatorScreens/IncubatorToastScreen.tsx
package.json
src/components/picker/NativePicker.js
src/components/sharedTransition/SharedArea.js

Upgrade reanimated to 2.17
Mostly TODOs
Upgrade reanimated to 2.17

Upgrade reanimated to 2.17

---

demo/src/screens/componentScreens/HintsScreen.tsx

HintsScreen - allow configuration
HintsScreen - allow configuration

HintsScreen - allow configuration

---

android/app/src/main/java/com/rnuilib/MainApplication.java
demo/src/screens/incubatorScreens/IncubatorToastScreen.tsx
demo/src/screens/incubatorScreens/TouchableOpacityScreen.js
package.json
src/components/sortableList/SortableListItem.tsx

Move to reanimated 3
Move to reanimated 3

Move to reanimated 3

---

src/commons/Constants.ts
src/commons/__tests__/constants.spec.ts

Add setBreakpoints and getPageMargins
Relates to WOAUILIB-3451
Add setBreakpoints and getPageMargins

Add setBreakpoints and getPageMargins

---

demo/src/screens/componentScreens/SliderScreen.tsx
demo/src/screens/incubatorScreens/IncubatorSliderScreen.tsx
src/components/slider/ColorSliderGroup.tsx
src/components/slider/GradientSlider.tsx
src/components/slider/context/SliderGroup.tsx
src/components/slider/index.tsx
src/components/slider/slider.api.json
src/incubator/Slider/index.tsx

Slider, GradientSlider, ColorSliderGroup - adding 'migrate' prop to allow using Incubator Silder instead of the old implementation.
Included: a fix for 'thumbTintColor' in the Incubator Slider to match old implementation.
Slider, GradientSlider, ColorSliderGroup - adding 'migrate' prop to allow using Incubator Silder instead of the old implementation. NO breaking changes.

Slider - adding 'migrate' prop to allow using Incubator.Silder

---

ios/rnuilib.xcodeproj/project.pbxproj

iOS - set demo's min deployment to iOS 13.0 and change bundle id to allow running on iOS device
Note: It will create a new app on the device the first time you run it, in case you have the old one still installed.
iOS - set demo's min deployment to iOS 13.0 and change bundle id to allow running on iOS device

iOS - change bundle id and set min deployment to iOS 13.0

---

src/components/switch/index.tsx
src/components/switch/switch.api.json
src/incubator/TextField/index.tsx
src/incubator/TextField/textField.api.json
src/incubator/TextField/types.ts

we need to be able to pass `id` prop to the TextField container.
currently `id` is typed but passed to the `Input` component, so we declared new prop `containerId` in order to not break anyone.
TextField - add `containerProps` prop
Switch - add `id` prop

TextField and Switch/ forward id prop

---

src/components/svgImage/index.web.tsx

Fix how we handle style in our Svg image component for web
There was a potential issue with how we merge the incoming style prop that can be either an object or an array 
SvgImage (web) - fix issue with style being passed as object

Fix how we handle style in our Svg image component for web

---

src/components/switch/index.tsx

Switch props passed on to TouchableOpacity component but typing wise didn't support TouchableOpacity props
Switch - fix props types to include TouchableOpacity props

Include TouchableOpacityProps in SwitchProps

---

demo/src/screens/incubatorScreens/IncubatorSliderScreen.tsx
src/incubator/Slider/SliderPresenter.ts
src/incubator/Slider/Thumb.tsx
src/incubator/Slider/index.tsx

Incubator.Slider - fix types
Incubator.Slider - fix types

Incubator.Slider - fix types

---

src/components/WheelPicker/index.tsx

WheelPicker - Android - fix missing values when initialValue is sent
We think that this was broken again in RN71
WheelPicker - Android - fix missing values when initialValue is sent
None

WheelPicker - Android - fix missing values when initialValue is sent

---

src/components/KeyboardAwareScrollView/KeyboardAwareBase.js
src/components/panningViews/panDismissibleView.tsx
src/components/panningViews/panResponderView.tsx
src/components/slider/Thumb.tsx
src/components/slider/index.tsx
src/components/tabController/TabBarItem.tsx

`setNativeProps` has been fully deprecated from `react-native-web ^0.19.0`.
this causing serious issues, for example can't open dialog picker.
fix: setNativeProps not supported on web
https://github.com/necolas/react-native-web/releases/tag/0.19.0

fix: setNativeProps not supported on web

---

src/incubator/TextField/index.tsx

Incubator.TextField - fix iOS - the context menu not showing in a centered and empty input
**iOS only**
Try this with and without the fix
`          <Incubator.TextField centered onChangeText={(text) => this.setState({text})} placeholder={'UILIB text field centered'}/>
`
1) Copy a value from some input (marking it, long press for context menu, press 'copy').
2) Long press on the text field when it is empty to display the context menu (for 'paste' action) - without the fix you'll see only the magnifying glass but the context menu will not show. With the fix, you'll see the context menu with a 'paste' action.
Incubator.TextField - fix iOS - the context menu not showing in a centered and empty input
WOAUILIB-3585

Incubator.TextField - fix context menu not showing in centered and empty input

---

src/incubator/Dialog/DialogHeader.tsx
src/incubator/Dialog/dialogHeader.api.json
src/incubator/Dialog/types.ts

IncubatorDialog - add topAccessory
IncubatorDialog - add topAccessory
WOAUILIB-3610

IncubatorDialog - add topAccessory

---

demo/src/screens/componentScreens/DateTimePickerScreen.tsx
package.json
src/components/dateTimePicker/dateTimePicker.api.json
src/components/dateTimePicker/index.tsx
src/components/dateTimePicker/useOldApi.ts
src/index.ts

DateTimePicker - start deprecation of moment props
I did not test this yet in private, but since the screen is working with an updated example I do not expect issues.
DateTimePicker - start deprecation of moment props (generifying with `dateTimeFormatter`)
#1805 #2544

DateTimePicker - start deprecation of moment props

---

src/components/tabController/TabBar.tsx

TabBar selectedIndex changed to the currentPage instead of initialIndex.
When the items sent to the TabController change the selectedIndex will stay on the current page.
TabBar stays on the selected index when items change.

Fixed TabBar scroll when there is selected index

---

src/incubator/TextField/ValidationMessage.tsx
src/incubator/TextField/index.tsx
src/incubator/TextField/textField.api.json
src/incubator/TextField/types.ts

Incubator.TextField - expose retainValidationSpace
Incubator.TextField - expose retainValidationSpace
WOAUILIB-3589

Incubator.TextField - expose retainValidationSpace

---

src/incubator/expandableOverlay/index.tsx

ExpandableOverlay - add migrateDialog prop
ExpandableOverlay - add migrateDialog prop
None

ExpandableOverlay - add migrateDialog prop

---

webDemo/package.json
webDemo/src/App.tsx

`react-native-gesture-handler` version upgrade in the webDemo.
Fix Slider example, changed to Incubator Slider.
`react-native-gesture-handler` version upgrade in the webDemo.

webDemo react-native-gesture-handler version upgrade

---

demo/src/screens/ExampleScreenPresenter.tsx
src/components/dateTimePicker/index.tsx
src/components/stepper/index.tsx

useCustomTheme - remove leftovers
useCustomTheme - remove leftovers

Infra/ remove useCustomTheme leftovers

---

src/components/svgImage/index.web.tsx
webDemo/src/App.tsx

Add web support for `tintColor` on svg tag data
Add web support for `tintColor` on svg tag data

feat: [MAW-257] svgImage support tintColor on web

---

src/commons/asBaseComponent.tsx

Fix Scheme change when bringing the app from background to foreground 
Verified on Owner version 2.78021.0 
Resolves https://github.com/wix/react-native-ui-lib/issues/2552#issuecomment-1562429297 
Scheme - fix color changing

Scheme - fix color changing

---

demo/src/screens/__tests__/__snapshots__/AvatarScreen.spec.js.snap
src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/text/index.tsx

Text - remove default textAlign style to fix iOS child Text not inheriting from its parent.
⚠️ Note: on Android, the Text will not align to the right on RTL if the actual language is not RTL language (back to its default behavior in RN)
Text - remove default textAlign style to fix iOS child Text not inheriting from its parent.
Solves #2457

Text - default alignment

---

src/incubator/expandableOverlay/index.tsx

ExpandableOverlay - fix dialog props
Note: you must have the `migrateDialog` in both types to prevent error.
ExpandableOverlay - fix dialog props
None

ExpandableOverlay - fix dialog props

---

src/components/picker/index.tsx
src/components/picker/types.tsx

Picker - ExpandableOverlay had ts error over the dialogProps.
We had the same error inside ExpandableOverlay `renderDialog`, it's coming from the `null` type for `height` prop in the old `Dialog` props.
Picker ts error fix.

fixed the ts error on ExpandableOverlay dialogProps in Picker.

---

src/components/picker/helpers/usePickerLabel.tsx

Fix Picker label not updating when items prop changes
Fx Picker label not updating when items prop changes

fix: Picker label not updating when items prop changes

---

src/components/chip/index.tsx

Using a margin cause a cut in the chip in some cases. moving to padding keeps the same UI without this bug.
Fix cut chips 
WOAUILIB-3665

Chip - change margin to padding

---

src/components/scrollBar/index.tsx

import ScrollView and FlatList from `react-native-gesture-handler`
**Please review only the first commit, the second one is formatting**
ScrollBar - fix scrolling inside Dialog on Android
WOAUILIB-3683

ScrollBar - fix scrolling inside Dialog on Android

---

src/incubator/Calendar/Day.tsx
src/incubator/Calendar/Day_OLD.tsx
src/incubator/Calendar/types.ts

Refactor Day component to not use animated styles
N/A

Refactor Day component to not use animated styles

---

src/components/view/index.tsx

View - add reanimated props for layout animation
View - add reanimated props for layout animation
WOAUILIB-3549

View - add reanimated props for layout animation

---

src/components/colorPicker/colorPicker.api.json
src/components/colorPicker/index.tsx
src/components/slider/ColorSliderGroup.tsx

We should avoid `defaultProps` that are localized and are directly assigned.
Deprecate `ColorPicker.accessibilityLabels` in favor of `ColorPicker.getAccessibilityLabels`
Deprecate `ColorSliderGroup.labels` in favor of `ColorSliderGroup.getLabels`
WOAUILIB-3659

No static locale infra

---

demo/src/index.js
demo/src/screens/MenuStructure.js
demo/src/screens/foundationScreens/RTLScreen.tsx
demo/src/screens/foundationScreens/index.js

Demo - adding RTL screen
Demo - adding RTL screen - Hebrew language

Demo - adding RTL screen

---

src/components/colorPicker/colorPicker.api.json
src/components/colorPicker/index.tsx
src/components/slider/ColorSliderGroup.tsx

This reverts commit 295e12e292afca9800786394a4365fd93c843a96.
Revert "No static locale infra (#2684)"
This reverts commit 295e12e292afca9800786394a4365fd93c843a96.
None
None

Revert "No static locale infra (#2684)"

---

src/components/WheelPicker/index.tsx

WheelPicker - `onLayout` is called more than once, replacing the `onLayout` function with `useEffect`.
WheelPicker with a long list of data jumps back to `initalValue` fix.

wheel picker onlayout fix

---

src/style/index.ts
src/style/typography.ts
src/style/typographyPresets.ts

Expose TypographyKeys
Expose TypographyKeys
WOAUILIB-3711

Expose TypographyKeys

---

src/components/view/index.tsx

Make picked reanimated type partial so they won't be mandatory
(For some reason we don't get an issue on this, but modules do)
Make picked reanimated type partial so they won't be mandatory
https://wix.slack.com/archives/C3B1EMVF0/p1693122291216409

Fix picked reanimated typings

---

src/commons/asBaseComponent.tsx
src/components/picker/types.tsx
src/components/tabController/index.tsx
src/components/view/index.tsx
src/typings/common.d.ts

ThemeComponent - clean leftovers
ThemeComponent - clean leftovers

ThemeComponent - clean leftovers

---

src/components/svgImage/index.web.tsx
webDemo/src/App.tsx

This PR is fixing 3 bugs in web svg component:
1. when rendering more than 1 svg, the style of the last one will override all of them
2. the style is initialized once, and doesn't been updated
3. the height of the svg wrapper bigger than the svg's height - caused an offest inside the button. the svg took too much space
**changes:**
1. add component to the web demo with `IconButton` that changes size
2. add unique id to each svg component
3. apply style also on the div wrapper
4. update the css when the style changes
fix: [WEB] Svg image unique style tag and update styles

fix: [WEB] SvgImage update styles

---

src/components/picker/PickerItemsList.tsx

Picker in WheelPicker mode supports `topBarProps`.
Picker in WheelPicker mode supports `topBarProps`.
https://github.com/wix/react-native-ui-lib/issues/2557

Picker in wheel picker mode supports top bar props

---

src/components/button/ButtonTypes.tsx
src/components/button/button.api.json
src/components/button/index.tsx
src/components/svgImage/index.tsx

allow SVG to infer size from the style object
Now SVG can infer size from style

chore: infer SVG size from style

---

src/style/colors.ts

Colors - generate palette - pass options object
Colors - generate palette - pass options object

Colors - generate palette - pass options object

---

src/components/icon/index.tsx
src/components/svgImage/index.web.tsx
webDemo/src/App.tsx

on web, SvgImage didn't respect `width` & `height` props.
currently we need to provide the `width` & `height` as props and also in style, so it would be respected both in web and mobile.
SvgImage now respects `width` & `height` props on web
in order to see the changes in the web demo you need to apply the changes manually in node_modules of the web-demo
instead of #2748

chore: [WEB] SvgImage respect width & height props

---

lib/components/DynamicFonts/PermissionsAcquirer.android.ts

DynamicFonts - remove buttonNegative (since it doesn't seem to do anything)
From my recent testing this cannot be used to prevent the system dialog that comes after this dialog, which makes this option bad UX (both buttons have the same result).
None
None

DynamicFonts - remove buttonNegative

---

src/style/__tests__/colors.spec.js
src/style/colors.ts

Colors - generateColorPalette - add the option to avoid reversing on dark mode
Colors - generateColorPalette - add the option to avoid reversing on dark mode

Colors - generateColorPalette - avoid reversing on dark mode

---

lib/components/DynamicFonts/index.ts

DynamicFonts - add isFontFamilyDownloaded
None
None

DynamicFonts - add isFontFamilyDownloaded

---

docs/getting-started/setup.md

`react-native-reanimated` setup guide link seem to be invalid & leads to 404 page.
docs: fixed dead link of react-native-reanimated setup guide

docs: Updated dead link of Reanimated setup guide

---

demo/src/screens/MainScreen.js

Fixed bug where clicking on the chips wouldn't scroll to the appropriate section.
Tiny change in scrollToSection function

Fixed chips scroll on press

---

react-native.config.js

Fix react-native.config has wrong file for DynamicFont.
Unfortunately we use a different mechanism so we did not find this when testing in private...
Fixes #2764 
Fix react-native.config has wrong file for DynamicFont
https://github.com/wix/react-native-ui-lib/issues/2764

Fix react-native.config has wrong file for DynamicFont

---

src/components/picker/PickerItem.tsx
src/components/picker/types.tsx

PickerItem - support asynchronous and ignore selection
PickerItem - support asynchronous and ignore selection
Relates to the FontPicker
None

PickerItem - support asynchronous and ignore selection

---

demo/src/screens/componentScreens/ExpandableSectionScreen.tsx
ios/rnuilib/Info.plist
src/commons/Constants.ts
src/components/colorPalette/index.tsx
src/components/connectionStatusBar/index.tsx
src/components/gridList/useGridLayout.ts
src/components/gridView/index.tsx
src/components/hint/index.tsx
src/components/stackAggregator/index.tsx
src/components/wizard/index.tsx
src/incubator/Calendar/CalendarItem.tsx

Table sub windows (split view / slide over) - fix constants and components
Table sub windows (split view / slide over) - fix constants and components

Table sub windows - fix constants and compomponents

---

src/components/carousel/Carousel.driver.new.ts
src/components/carousel/__tests__/index.spec.tsx
src/testkit/new/useScrollable.driver.ts

`useScrollable` - a new driver to the testKit to support testing lists and lists-based components.
`useScrollable` - a new driver to the testKit to support testing lists and lists-based components.

testkit new useScrollabe driver, new Carousel driver for testings

---

src/components/colorPicker/ColorPickerDialog.tsx

add testids to color picker dialog
infra add testids to color picker dialog
https://wix.monday.com/boards/4315393198/pulses/5076627134

infra add testids to color picker dialog

---

src/style/colors.ts

Colors - expose shouldSupportDarkMode
We need it to know if we should flip to DM or not even if the Scheme is 'dark'
Colors - expose shouldSupportDarkMode

Colors - expose shouldSupportDarkMode

---

src/components/colorPicker/index.tsx

Reverted the migration to the new slider in the ColorPicker component.
ColorPicker - Removed migrate from ColorPickerDialog

Removed migrate to new slider in colorpicker.

---

src/components/textField/index.tsx

When rendering `TextField` with `value=undefined`, and updating the `defaultValue`, the new `defaultValue` doesn't being updated.
I managed to reproduce it only on web, not sure why.. probably because of the JS engine.
Fix TextField defaultValue on web when `value=undefined`
WOAUILIB-3867

fix: [WOAUILIB-3867] TextField default value

---

src/components/colorPicker/ColorPickerDialog.tsx
src/components/colorPicker/ColorPickerDialogHeader.tsx
src/components/colorPicker/ColorPickerDialogSliders.tsx
src/components/colorPicker/ColorPickerPresenter.ts
src/components/colorPicker/ColorPickerPreview.tsx

Changing the ColorPickerDialog to a FC.
ColorPickerDialog - Changed to FC

Moved ColorPickerDialog to FC.

---

demo/src/index.js
demo/src/screens/MenuStructure.js
demo/src/screens/componentScreens/HorizontalSortableListScreen.tsx
demo/src/screens/componentScreens/index.js
src/components/sortableList/SortableListContext.ts
src/components/sortableList/SortableListItem.driver.new.ts
src/components/sortableList/SortableListItem.tsx
src/components/sortableList/index.tsx
src/components/sortableList/usePresenter.ts

SortableList - support horizontal
Added a dedicated - HorizontalSortableListScreen
SortableList - support horizontal
WOAUILIB-3655

SortableList - support horizontal

---

src/components/slider/context/SliderGroup.tsx

Converted SliderGroup to FC.
SliderGroup - Moved to a FC.

Moved SliderGroup to FC.

---

src/style/__tests__/colors.spec.js
src/style/colors.ts

Avoid failing Colors.rgba API on invalid input to avoid app crashes
Avoid failing Colors.rgba API on invalid input to avoid app crashes

Avoid failing rgba API

---

src/components/dateTimePicker/dateTimePicker.api.json
src/components/dateTimePicker/index.tsx

Add display property to dateTimePicker component to be able to change it
Add display property to dateTimePicker component. Default value is **`spinner`** on iOS and **`default`** on Android. Previously,  `spinner` (iOS) and `undefined` (Android) was passed to `RNDateTimePicker`.

Add display property to dateTimePicker

---

src/components/radioButton/index.tsx

Our RadioButton didn't extend our ViewProps but ReactNative's 
For some reason only now we got a complaint about missing types 🤷 
Anyway, this PR should fix it
Fix RadioButton typings to extend ours ViewProps

Fix RadioButton typings to extend our ViewProps

---

src/components/tabController/TabBar.tsx

Remove TabBar's default static backgroundColor prop value to avoid race condition when loading design tokens
Remove TabBar's default static backgroundColor prop value to avoid race condition when loading design tokens

remove static default backgroundColor prop

---

src/components/timeline/Line.tsx
src/components/timeline/Point.tsx
src/components/timeline/types.ts

UX leans on reusing timeline component for activity log, so adding minimal required adjustments. Ideally, icon size would be equal to text line height and width of a line is one. This can be achieved with this PR.
Adding width prop to Line component & iconProps to Point component. This makes some of the previously static values dynamic
Required for activity log integration

Reuse timeline for activity log

---

src/components/slider/ColorSlider.tsx
src/components/slider/ColorSliderGroup.tsx

Moved ColorSliderGroup to FC.

---

demo/src/screens/foundationScreens/ColorsScreen.js
src/style/__tests__/colors.spec.js
src/style/colors.ts

Colors - adjust palette to steps of 9 when addDarkestTint is true
Colors - adjust palette to steps of 9 when addDarkestTint is true
WOAUILIB-3830

Colors - adjust palette to steps of 9 when addDarkestTint is true

---

src/components/carousel/index.tsx

On #2831 I fixed the jumping bugs on android. In order to do that I inverted the ScrollView so we wont have to deal with index calculations. Inverting the ScrollView caused the children to also be inverted so I inverted them back in that case.
Carousel - Fixed inversion on Android RTL.
None

[HOTFIX] Inverted child inner view on android RTL.

---

src/hooks/useCombinedRefs/index.ts

When sending more than two refs to the hook it will always create a new array on each call causing the useEffect to run every time. Until now this didn't happen because we didn't pass more than one ref.
useCombinedRef - Added handling for receiving more than one ref.
None

useCombinedRefs running effect on every call.

---

src/components/WheelPicker/Item.tsx
src/components/WheelPicker/index.tsx

There were labels near the values of the wheel picker. Because they were white they could only be seen on darker backgrounds. I added opacity = 0 because removing this label was causing the entire layout to change.
WheelPicker - fixed value labels showing near every label.
WOAUILIB-3875

Fixing phantom label on the wheel picker.

---

src/components/textField/types.ts

Fix ts error: 
```
Types of property 'ref' are incompatible.
Type 'Ref<TextInput> | undefined' is not assignable to type 'LegacyRef<Component<TextFieldProps, any, any>> | undefined'.
```
To reproduce add this code to playgroundScreen: 
```
export const ExpandableTextField = ({...textFieldProps}: TextFieldProps) => {
return <TextField {...textFieldProps}/>;
};
```
TextField - fix TS error: Types of property 'ref' are incompatible
Ticket 3899

TextFiled - fix incompatible ref types TS error

---

src/components/textField/Input.tsx
src/components/textField/textInput/index.tsx
src/components/textField/textInput/index.web.tsx
webDemo/src/App.tsx

There is a bug on react-native-web that multiline TextInput doesn't auto-expand
https://github.com/necolas/react-native-web/issues/795
Fix TextField multiline auto-expanding on web
WOAUILIB-3903

fix: [WOAUILIB-3903] TextField multiline auto-expanding on web

---

lib/android/src/main/java/com/wix/reactnativeuilib/keyboardinput/ReactScreenMonitor.java

Add an extra null check before adding the listener
Check getWindow() is not null before getDecorView()
#2875 Plz help check if this is the cause

fix: add null check for ReactScreenMonitor

---

src/hooks/useCombinedRefs/index.ts

Revert useCombinedRefs [PR](https://github.com/wix/react-native-ui-lib/pull/2852), solving ref issues in some components (ChipsInput issue with validate for example).
Revert useCombinedRefs.

revert useCombinedRefs

---

demo/src/screens/componentScreens/SliderScreen.tsx
demo/src/screens/componentScreens/TextFieldScreen.tsx
demo/src/screens/componentScreens/TextScreen.tsx
demo/src/screens/incubatorScreens/IncubatorSliderScreen.tsx
src/commons/asBaseComponent.tsx
src/commons/forwardRef.tsx
src/components/button/ButtonTypes.tsx
src/components/button/index.tsx
src/components/fadedScrollView/index.tsx
src/components/icon/index.tsx
src/components/pageControl/index.tsx
src/components/scrollBar/index.tsx
src/components/slider/GradientSlider.tsx
src/components/tabController/TabBar.tsx
src/components/text/index.tsx
src/components/textField/index.tsx
src/incubator/Slider/index.tsx
src/incubator/index.ts
src/incubator/toast/index.tsx
src/typings/common.d.ts

Added RefInterface to the our forwardRef function. Adding this generic sets the type of the ref to the specific interface so when passing ref to a one of our components it will show a ts error when passing an incompatible interface ref.
Added generic typings to the forwardRef and in the asBaseComponent usage.
None

Ref Typings

---

src/components/carousel/types.tsx
src/components/fader/index.tsx
src/components/floatingButton/index.tsx
src/components/gradient/index.tsx
src/components/marquee/types.ts
src/components/overlay/index.tsx
src/components/panningViews/panGestureView.tsx
src/components/panningViews/panningProvider.tsx
src/components/picker/types.tsx
src/components/skeletonView/index.tsx
src/components/slider/GradientSlider.tsx
src/components/tabController/useScrollToItem.ts
src/components/timeline/index.tsx
src/components/timeline/types.ts
src/components/wizard/types.tsx
src/hooks/useScrollToItem/index.ts
src/incubator/Calendar/Month.tsx
src/incubator/Calendar/types.ts
src/incubator/panView/panningUtil.ts

Literal enum typings in props.
TS - Enumerable props can now be use with string literals.
TS Effort

Literal enum typings

---

src/components/text/Text.driver.new.ts
src/components/textField/TextField.driver.new.ts
src/components/textField/__tests__/index.driver.spec.tsx
src/components/textField/__tests__/index.spec.tsx
src/testkit/index.ts

TextField - create new driver and refactor tests to it
TextField - create new driver and refactor tests to it
None

TextField - create new driver and refactor tests to it

---

src/components/button/Button.driver.new.ts
src/components/button/Button.new.driver.ts
src/components/button/__tests__/index.driver.spec.tsx
src/components/image/Image.driver.new.ts
src/testkit/index.ts

Button - create new driver and refactor tests to it
Button - create new driver and refactor tests to it

new button driver, image driver, testing

---

src/components/switch/__tests__/index.spec.tsx
src/components/switch/switch.driver.ts

Switch - refactor driver to use new implementation
Switch - refactor driver to use new implementation

Switch - refactor driver to use new implementation

---

src/incubator/Dialog/__tests__/index.new.spec.tsx

Modal exists even when not visible (automation gap - WOAUILIB-3606)
None
WOAUILIB-3606

Modal exists even when not visible (automation gap - WOAUILIB-3606)

---

src/components/text/__tests__/index.driver.spec.tsx
src/components/text/index.tsx

Added automation gap for text alignment on rtl.
N/A
WOAUILIB-3704

Automation gap - WOAUILIB-3704

---

src/components/text/__tests__/index.driver.spec.tsx

Changed naming of the automation gap tests and changed their order.
None
None

Change test naming and reordered tests

---

src/components/hint/index.tsx

Currently, headless tests are breaking with another module transitively most likely because of incomplete mocking in infra.
Adding type safe way to access refs. In general, it would be best to treat ref types as partial.

Type safe access to ref to avoid breaking tests

---

src/style/colors.ts

Fix typing of Colors.getColorTint api
We handle an undefined value for the first argument so the type should also include undefined. 
This is relate to fixing typings issues in private (strict:true) effort 
Fix typing of Colors.getColorTint api

Fix typing of Colors.getColorTint api

---

src/commons/modifiers.ts

Our bg-? modifier didn't work well, it didn't autocomplete based on our colors tokens
This fixes it 
Fix bg-? modifier typings

Fix bg-? modifier typings

---

src/style/colors.ts

Fix Colors.isDark typings to accept undefined argument
Fix Colors.isDark typings to accept undefined argument

Fix Colors typings

---

demo/src/screens/componentScreens/TimelineScreen.tsx
src/components/timeline/Point.tsx
src/components/timeline/types.ts

TimeLine new `removeIconBackground` prop, Icon can be displayed without point background.
The Icon display size fix, set to `16` instead of `12`.
TimeLine new `removeIconBackground` prop, Icon can be displayed without point background.

removeIconBackground prop added to TimeLine, fixed Icon size

---

demo/src/screens/MenuStructure.js
demo/src/screens/incubatorScreens/IncubatorSliderScreen.tsx
src/components/colorPicker/ColorPickerDialogHeader.tsx
src/components/colorPicker/ColorPickerPreview.tsx
src/components/slider/ColorSliderGroup.tsx
src/components/slider/GradientSlider.tsx
src/components/slider/slider.api.json
src/incubator/Slider/Thumb.tsx
src/incubator/Slider/index.tsx

Slider - add 'enableShadow' prop 
GradientSlider - display color only changes on hue change
ColorPicker - minor UI changes
Slider - bug fix - invoke onChange only when user move slider
Slider - add 'enableShadow' prop 
GradientSlider - display color only changes on hue change
ColorPicker - minor UI changes
Slider - bug fix - invoke onChange only when user move slider
MADS-3847

Slider 'enableShadow' prop and ColorPicker - minor UI changes

---

demo/src/screens/componentScreens/SliderScreen.tsx
src/components/slider/ColorSlider.tsx
src/components/slider/ColorSliderGroup.tsx
src/components/slider/GradientSlider.tsx
src/components/slider/context/SliderGroup.tsx
src/components/slider/index.tsx
src/components/slider/slider.driver.ts
src/components/slider/types.ts
src/incubator/Slider/index.tsx
src/index.ts

Slider - wrap in asBaseComponent and fix typings
Slider - wrap in asBaseComponent and fix typings

Slider - wrap in asBaseComponent and fix typings

---

src/components/colorPicker/ColorPickerDialog.tsx
src/components/colorPicker/ColorPickerDialogSliders.tsx
src/components/slider/ColorSlider.tsx
src/components/slider/ColorSliderGroup.tsx
src/components/slider/GradientSlider.tsx
src/components/slider/context/SliderContext.ts
src/components/slider/context/SliderGroup.tsx
src/components/slider/types.ts

The bug: When moving the lightness slider to white, a #fffff color is set back to the component creating a color of h=0,s=0,l=0 values.
Now when moving the hue slider the color remains grey as the saturation is 0, and when moving the lightness slider the color remains red as the hue is 0.
The solution: Passing the color as HSL instead of converting it to hex allows the new color to keep the values of the hue and saturation in the transition so when moving either slider the color changes from the last values and not from the white color values.
ColorPicker - fix - hue changes to red after moving lightness to white

ColorPicker - fix - hue changes to red after move lightness to white

---

src/components/slider/ColorSliderGroup.tsx
src/components/slider/GradientSlider.tsx

`GradientSlide` & `ColorsSliderGroup` generic type fix, expected error on `asSliderGroupChild`

fixed GardientSlider getHSL call

---

demo/src/screens/componentScreens/IconScreen.tsx
src/components/badge/index.tsx
src/components/icon/index.tsx

`Icon` support in badge.
Added 2 new props `badgeProps | hideBadge` to the `Icon` component.
`Icon` support in badge.

icon support in badge

---

demo/src/screens/componentScreens/SegmentedControlScreen.tsx
src/components/segmentedControl/index.tsx
src/components/segmentedControl/segment.tsx
src/components/segmentedControl/segmentedControl.api.json

SegmentControl support in custom typography, new `segmentTypography" prop
SegmentControl support in custom typography

new segemntTypography prop

---

demo/src/screens/incubatorScreens/IncubatorSliderScreen.tsx
src/incubator/Slider/index.tsx

Incubator.Slider - fix onSeek functions
Fix for error: ReanimatedError: Tried to synchronously call a non-worklet function on the UI thread.
Incubator.Slider - fix onSeek functions
Incubator.Slider - fix onSeek functions

Incubator.Slider - fix onSeek functions

---

demo/src/screens/componentScreens/PickerScreen.tsx
src/components/picker/index.tsx
src/components/picker/types.tsx
src/index.ts
webDemo/src/examples/Picker.tsx

Picker - export RenderCustomModalProps and PickerItemsListProps
Will be used in strict effort
Note: I did not see a usage of the `show: boolean` prop, let me know if I missed something 🙏 
Picker - export RenderCustomModalProps and PickerItemsListProps
None

Picker - export RenderCustomModalProps and PickerItemsListProps

---

demo/src/screens/componentScreens/FloatingButtonScreen.tsx
src/components/floatingButton/__tests__/index.spec.tsx
src/components/floatingButton/floatingButton.api.json
src/components/floatingButton/index.tsx

FloatingButton - add 'fullWidth' prop
FloatingButton - add 'fullWidth' prop
ticket 4057

FloatingButton - add 'fullWidth' prop

---

src/components/picker/index.tsx

`Picker` - `fieldType - settings` changed the `View` wrapper `flex` to be `flexGrow` as passing `position: relative` to shrink and grow according to the parent.
`Picker` - `fieldType - settings` changed the wrapper `flex` to `flexGrow` to solve flex issues according to the parent style.
ticket 4018

Picker settings field flex changed to flexGrow

---

lib/ios/reactnativeuilib/keyboardtrackingview/ObservingInputAccessoryViewTemp.m
lib/package.json

TextInput - fix application halting when `keyboardType=“number-pad”` with external keyboard (not sure if Apple keyboard reproduces)
Real device only
Example screen:
```
import {ScrollView, TextInput} from 'react-native';
import {Keyboard, View} from 'react-native-ui-lib';
render() {
return (
<ScrollView contentContainerStyle={{flex: 1}}>
<View flex centerV>
<TextInput placeholder={'TextInput'} keyboardType="number-pad"/>
<Keyboard.KeyboardAwareInsetsView/>
</View>
</ScrollView>
);
}
}
```
TextInput - fix application halting when `keyboardType=“number-pad”` with external keyboard (not sure if Apple keyboard reproduces)
Ticket 4007

TextInput - keyboardType="number-pad" with external keyboard

---

src/components/icon/index.tsx
src/components/image/index.tsx
src/utils/__tests__/imageUtils.spec.js
src/utils/imageUtils.ts

Image support strings as type for `source`.
Source now support `svg` image string, requested from the `CTO` and the `web editor` teams.
Image support strings as type for `source`.

Image support in string as source, for svg strings

---

src/components/avatar/index.tsx
src/components/icon/index.tsx

Avatar and Icon - update the source prop type to the new `ImageSourceType` from Image.
[Related PR ](https://github.com/wix/react-native-ui-lib/pull/2983)
Avatar and Icon source prop type update to `ImageSourceType`

changed the source type to ImageSourceType

---

src/components/picker/__tests__/index.spec.tsx
src/components/picker/helpers/usePickerLabel.tsx

when passing undefined after a value already selected, it's not being cleared on the UI.
fix: clearing picker value on web
MADS-4071

fix: [MADS-4071] clear picker value on web

---

src/components/WheelPicker/index.tsx

WheelPicker - fix item snap to vertical center
WheelPicker - fix item snap to vertical center
ticket 4032, 3661

WheelPicker - fix item snap to vertical center

---

src/components/WheelPicker/WheelPicker.driver.tsx
src/components/button/Button.driver.new.ts
src/components/carousel/Carousel.driver.new.ts
src/components/checkbox/Checkbox.driver.ts
src/components/modal/Modal.driver.new.ts
src/components/sectionsWheelPicker/SectionsWheelPicker.driver.tsx
src/components/sortableList/SortableListItem.driver.new.ts
src/components/switch/switch.driver.ts
src/components/text/Text.driver.new.ts
src/components/text/__tests__/index.driver.spec.tsx
src/components/textField/TextField.driver.new.ts
src/components/view/View.driver.new.ts
src/incubator/Dialog/Dialog.driver.new.ts
src/incubator/toast/Toast.driver.new.ts
src/testkit/new/Component.driver.ts
src/testkit/new/useDraggable.driver.ts
src/testkit/new/usePressable.driver.ts
src/testkit/new/useScrollable.driver.ts

Removed the usage of getProps from the basic component driver. To get the element props we now need to use getElement().props.
Changed Text driver getText to return text if it has only one children.
None.
MADS-4058

Removed getProps/getElementProps entirely

---

src/style/typographyPresets.ts

fix: https://github.com/wix/react-native-ui-lib/issues/2696#issue-1835247503
I switched to weightKey -> weightValue.
The fontWeight BO, H, and BL were not applied to Android.
const weightsMap = {
THIN: 'T',
LIGHT: 'L',
REGULAR: 'R',
MEDIUM: 'M',
BOLD: 'BO',
HEAVY: 'H',
BLACK: 'BL'
};
_.forEach(keys, (key) => {
_.forEach(weightsMap, (weightValue, weightKey) => {
const fontKey = `text${key}` as keyof TypographyKeys;
const fontWeightKey = `${fontKey}${weightValue}` as keyof TypographyKeys;
Typography[fontWeightKey] = {
...Typography[fontKey],
fontWeight: Constants.isIOS ? WEIGHT_TYPES[weightKey] : ['BO', 'H', 'BL'].includes(weightKey) ? 'bold' : undefined
};
});
});
In this codes, weightKey can never be included in ['BO', 'H', 'BL']. It can be only 'THIN', 'LIGHT', 'REGULAR' ....
weightValue …

fix: android font weight not matching

---

src/incubator/Slider/SliderPresenter.ts

Incubator Slider - fix step interpolation
to reproduce:
`      
<Incubator.Slider
value={sliderValue}
onValueChange={setSliderValue}
step={1}
minimumValue={12}
maximumValue={50}
/>
`
Slider or press track to see the slider jumps.
Incubator Slider - fix step interpolation
ticket 4070

Incubator Slider - fix step interpolation

---

src/components/textField/validators.ts

Updated the `email` and `number` validators in `validator.ts` to allow empty strings. Now, empty email and number strings are considered valid.
issue #2807
- Modified the `email` validator logic to allow empty strings explicitly.
- Modified the `number` validator logic to consider empty strings as valid.
This change ensures a more permissive validation for both email and number fields. If a field is not required, no error message will be displayed when users clear their input.
**If you encounter any issues or have further suggestions, please let me know.**
<table border="0">
<tr>
<td><b style="font-size:30px">1. Invalid Email </b></td>
<td><b style="font-size:30px">2. Invalid Number</b></td>
</tr>
<tr>
<td><img src="https://github.com/wix/react-native-ui-lib/assets/134603758/c08e3800-4231- …

fix: Allow empty strings for email and number validation in validators.ts

---

src/components/image/index.tsx
src/components/overlay/index.tsx

Image\Overlay - support borderRadius (only via the prop, not via style)
Image\Overlay - support borderRadius (only via the prop, not via style)
Ticket 4074

Image\Overlay - support borderRadius

---

.yarnrc
yarn.lock

Set the npm registry we use to the public one (instead of the private wix) because it's being saved in our yarn.lock and when other people (outside of Wix) try to run it, they can't fetch the packages 
Fix registry used when running yarn and fix yarn.lock

Set registry to public one

---

src/components/expandableSection/index.tsx

[Android] ExpandableSection - fix inner component's animation not working
In this case `TextField` with `floatingPlaceholder` inside `ExpandableSection` causes the `placeholder` on Android to not be shown.
Credit to: https://dev.to/dimaportenko/collapsible-card-with-react-native-reanimated-495a
Example screen:
```
import {ScrollView, TextInput} from 'react-native';
import {View, Text, TextField, ExpandableSection} from 'react-native-ui-lib';
state = {
isExpanded1: false,
isExpanded2: false
};
getHeaderElement() {
return (
<View margin-10 spread row>
<Text grey10 text60>
ExpandableSection sectionHeader
</Text>
</View>
);
}
render() {
return (
<ScrollView>
<ExpandableSection …
```

[Android] ExpandableSection - fix inner component's animation not working

---

src/incubator/Slider/index.tsx

Incubator.Slider - value updates fix flag
The fix is for GradientSlider which doesn't get updated since the value changes on init thus the flag turns true and onValueChange is not called on the first change.
Incubator.Slider - value updates fix flag
Fix for PR https://github.com/wix/react-native-ui-lib/pull/2994

Incubator.Slider - value updates fix flag

---

src/components/svgImage/index.tsx

Passing undefined to display prop of Svg in order to handle svgs with `display="block"` which causes any error.
**Not sure if this should be in the change log**
SvgImage - Fix svgs with `display="block"` causes crashes.
MADS-4017

passing display undefined to svgs

---

src/components/textField/index.tsx

`TextField` bottom view should render the `validationMessage` only if the user passed `validationMessage`.
Currently the `validationMessage` renders most of the times because the default value for `validationMessagePosition` is `bottom` and break the alignment when the user passes `bottomAccessory` by it self.
`TextField` bottom view should render the `validationMessage` only if the user passed `validationMessage`.

bottom validation message should render only if validation message sent

---

src/incubator/Slider/Thumb.tsx

Fix/ call onSeekStart only on start (today it's triggered on every value change)
Slider - fix call onSeekStart only on start

Fix/ Slider - call onSeekStart only on start

---

src/incubator/Slider/index.tsx
src/incubator/Slider/slider.api.json

Add throttleTime prop in Slider component

Slider/add throttleTime prop

---

src/components/hint/index.tsx

Hint passing TestID to the Text component.
We should add test for this, waiting for this [PR](https://github.com/wix/react-native-ui-lib/pull/2898) to merge first to use the new driver.
Hint passing TestID to the Text component.
ticket 3682

pass the testID to the Text component

---

src/components/picker/index.tsx

because of https://github.com/wix/react-native-ui-lib/pull/2986, the placeholder stopped being rendered for `settings` and `filter` Picker.
fix: filter and settings picker placeholder on web
MADS-4118

fix: [MADS-4118] filter and settings picker placeholder on web

---

src/incubator/toast/index.tsx

This fixes an issue where the pan view in not rendered when the toast is rendered with children making in unswipable
Toast - fix PanView not rendered with children.
MADS-4134

Fix Toast not swipable when rendered with children.

---

src/testkit/new/Component.driver.ts

Niryo said he need the type here to change so it can integrate with amino
ComponentDriver - Changed props typings.
MADS-4062

changed driver props typing

---

src/components/textField/index.tsx

Revert to #3012 . It was causing layouting problems with modules.
TextField - Reverted validation message block not rendered by default.
MADS-4147, MADS-4143

Revert to #3012

---

src/incubator/Dialog/__tests__/index.new.spec.tsx

I changed the test so it would test for existence of the dialog instead of testing for the visibility of the modal. I thought they're the same thing.
None
None

Fixed dialog test to actually test for existence

---

src/testkit/new/Component.driver.ts

Added type to `testID` in the drivers typings
ComponentDriver - Added extra type to testID.
MADS-4062

Changed ComponentProps typing for amino

---

src/assets/Assets.ts
src/typings/assets.d.ts
src/typings/common.d.ts

Fixed typings when assets where loaded to an already loaded path. When loading to an already loaded path the type was overridden and not combined. 
Assets - Fix loading assets typings to preloaded path.
MADS-4126

handled case of assets union

---

demo/src/screens/componentScreens/SortableGridListScreen.tsx
demo/src/screens/componentScreens/SortableListScreen.tsx
src/components/sortableGridList/index.tsx
src/components/sortableGridList/sortableGridList.api.json
src/components/sortableGridList/types.ts
src/components/sortableList/SortableList.api.json
src/components/sortableList/index.tsx
src/components/sortableList/types.ts

When we started wrapping our SortableList and SortableGridList components with `GestureHandlerRootView` we should have pass flex style so the list have a flexed behavior like other RN lists (FlatList, ScrollView, etc..) 
This migration is for transition to this default behavior
Start a migration to add flex to SortableList and SortableGridList
MADS-4163

Add flexMigration to SortableList and SortableGridList components

---

demo/src/screens/SettingsScreen.js
demo/src/screens/componentScreens/PickerScreen.tsx
demo/src/screens/realExamples/ProductPage/index.tsx
webDemo/src/examples/Picker.tsx

Picker screens aligned to the new picker props deprecation.
Note: the only example didn't fixed yet is the `Custom Modal` which has an issue with the `renderItem` function.
I'm working on a fix separately. 
Picker screens refactor according to the Picker refactor.
None

Picker screens aligned to the new props migration

---

src/components/segmentedControl/index.tsx

The SegmentedControl outline sometimes renders a straight line and doesn't cover entire segment. Changed the height dimension on the outline to also be a shared value.
SegmentedControl - Fix outline sometimes renders as a straight line.
MADS-4246

SegmentedControl - fixed Outline sometimes renders as a line

---

demo/src/screens/componentScreens/PickerScreen.tsx
src/components/picker/index.tsx
src/components/picker/types.tsx

Picker support passing items when passing renderCustomModal.
When passing items the Picker index file will return array of PickerItems instead of Children to the modal props.
Picker support passing items when passing renderCustomModal.
MADS-4228

Picker render custom modal support items

---

src/components/textField/index.tsx

TextField - fix extra margin at the bottom - don't render Text component if no helperText
TextField - fix extra margin at the bottom - don't render Text component if no helperText
hot fix

TextField - fix extra margin at the bottom

---

src/components/gridList/index.tsx

We had an issue in GridList after recent changes I did
React Native doesn't like it when we pass columnWrapperStyle while number of columns is 1 
Fix issue in GridList when passing numColumns 1

avoid passing columnWrapperStyle when numberOfColumns is 1

---

src/components/picker/types.tsx

`onChange` is invoked with `PickerMultiValue` in multi mode, needs to be reflected in types

types(Picker): correct type for `onChange` in multi mode

---

src/components/picker/PickerItem.tsx

PickerItem renderItem passing to the PickerItem is stronger then renderItem from the contextValue.
None
None

PickerItem renderItem stronger then Picker renderItem

---

demo/src/screens/componentScreens/TextFieldScreen.tsx
src/components/textField/ValidationMessage.tsx
src/components/textField/textField.api.json
src/components/textField/types.ts

TextField - fix validationIcon with no validationMassage and change type
TextField - fix validationIcon with no validationMassage and change type to IconProps

TextField - fix validationIcon with no validationMassage

---

src/components/animatedImage/index.tsx
src/components/image/index.tsx

Pass `imageStyle` to Image component when internally it renders ImageBackground (whenever we render children inside the Image) 
This fix some issues where image styling is not being passed to the Image that rendered by ImageBackground component 
See reference in [React Native docs](https://reactnative.dev/docs/imagebackground#imagestyle)
Fix nesting image style props in Image component with children (overlay, content).. 
ticket 4290

Support passing imageStyle when rendering internally ImageBackground

---

src/components/textField/ClearButton.tsx
src/components/textField/index.tsx

TextField - clearButton - fix animation
TextField - clearButton - fix animation

TextField - clearButton - fix animation

---

src/incubator/expandableOverlay/index.tsx

Modal support onRequestClose for Android users close modal on back button press.
Note the `onRequestClose` is in RN AndroidModal types - [link](https://reactnative.dev/docs/modal#onrequestclose)
Related [PR](https://github.com/wix/react-native-ui-lib/pull/3128) that closed
Modal support closing on Android back button press.
MADS-4238

passing onRequestClose to Modal

---

src/components/hint/index.tsx

Allow passing `(string | ReactElement)[]` in HintProps.message. This is handy when we want to pass a string with formatting (array of strings / <Text /> elements) 
Improved HintProps typing
N/A

[interface] Allow array in HintProps.message

---

demo/src/screens/componentScreens/TextFieldScreen.tsx

TextField - fix screen cases
TextField - fix screen cases for snapshot tests

TextField - fix screen cases

---

src/components/picker/types.tsx

getItemLabel type changed since it's not deprecated
getItemLabel type changed since it's not deprecated
MADS-4191

getItemLabel type changed since it's not deprecated

---

src/components/textField/index.tsx

PR #2489 moved and renamed the `incubatorScreens/IncubatorTextFieldScreen.tsx` file to be `componentScreens/TextFieldScreen.tsx`. This PR adjusts sources to changes.
Update example in TextField
Fixes #3108

TextField - Update example

---

src/components/hint/index.tsx

After changing `Hint` `message` prop type in this [PR](https://github.com/wix/react-native-ui-lib/pull/3133) which became a bit lossy type, changing the `message` type to be `ContentType` more strict type.
Hint message prop type fix.
None

Fixed Hint message type

---

demo/src/screens/__tests__/__snapshots__/AvatarScreen.spec.js.snap
demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/image/index.tsx

Until now `borderRadius` was passed to `imageStyle` which is only for `overlayContent` use case.
That caused a bug in the web environment which `image` without `overlayContent` didn't get the `borderRadius` that passed via the `imageProps`.
[related PR](https://github.com/wix/react-native-ui-lib/pull/3131)
[related issue/feature](https://github.com/necolas/react-native-web/issues/2692) request in `react-native-web`
Note:
```
<Image
source={{uri: 'https://github.com/pedrottimark.png'}}
style={{width: 200, height: 200, margin: 20}}
borderRadius={45}
/>
```
This is basic RN Image with `borderRadius`, this is working on mobile but not on web environment. 
Image passing `borderRadius` to style. 
None

borderRadius is passed to image style

---

demo/src/screens/componentScreens/PickerScreen.tsx
src/components/picker/helpers/__tests__/usePickerLabel.spec.ts
src/components/picker/helpers/usePickerLabel.tsx

Picker - usePickerLabel - fix picker label is empty if the 'value' prop is a string and no 'items' passed.
usacase: `<Picker value={'Picker Value'}/>`
⚠️ Picker - usePickerLabel - fix picker label is empty if the 'value' prop is a string and no 'items' passed.

Picker - fix usePickerLabel

---

src/components/picker/PickerItemsList.tsx

Picker support `renderHeader` in wheel picker mode.
PickerItemList file arrangment. 
Picker support `renderHeader` in wheel picker mode.
MADS-4314

support renderHeader in useWheelPicker mode

---

src/components/picker/index.tsx

Picker with field type is using `label and placeholder` props to render the text filed inner input.
The `useFieldType` hook was using the label from the props instead from the `usePickerLabel` hook, now it uses the value from the label hook and as fallback the label prop value.
related [PR](https://github.com/wix/react-native-ui-lib/pull/3130)
Fix Picker with field type not showing the selected value.
None

passing label from usePickerLabel when using filter filedtype

---

src/components/picker/helpers/__tests__/usePickerLabel.spec.ts
src/components/picker/helpers/usePickerLabel.tsx

Picker - usePickerLabel - revert fix fro string value
Picker - usePickerLabel - revert fix fro string value

Picker - usePickerLabel - revert fix fro string value

---

demo/src/screens/componentScreens/PickerScreen.tsx
src/components/picker/__tests__/index.spec.tsx
src/components/picker/helpers/useFieldType.tsx
src/components/picker/index.tsx

Picker - fieldType - fix and align to UX guidelines
Picker - fieldType - fix and align to UX guidelines

Picker - fieldType - fix and align to UX guidelines

---

demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
demo/src/screens/componentScreens/ButtonsScreen.tsx
src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/button/__tests__/index.spec.js
src/components/button/index.tsx

Separate the icon color we pass in Button from the icon style object. 
This allows up to pass iconColor to the `tintColor` prop and allow the user to override it color properly 
Fix issue with Button's icon color not being overridden when passing `iconProps`/`iconStyle`

Separate icon color passed in Button from icon style

---

src/components/picker/index.tsx

Avoid memoizing renderTextField in Picker using useCallback 
Fix Picker not responding to changes

Avoid memoizing render textfield in Picker

---

demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
demo/src/screens/componentScreens/TextFieldScreen.tsx
src/components/textField/index.tsx

TextField - fix for centered input
Fix for this PR: https://github.com/wix/react-native-ui-lib/pull/3178
TextField - fix for centered input

TextField - fix for centered input

---

docs/foundation/modifiers.md

Reverts wix/react-native-ui-lib#3186
Unfortunately had to revert, this change breaks our docs build script

Revert "fix(docs): broken links in docs"

---

src/components/tabController/TabBar.tsx

bugfix: remove TabController.TabBar defaultProps, use JavaScript default parameters instead.
```
remove code:
TabBar.defaultProps = {
labelStyle: DEFAULT_LABEL_STYLE,
selectedLabelStyle: DEFAULT_SELECTED_LABEL_STYLE,
faderProps: DEFAULT_FADER_PROPS,
spreadItems: true
};
use parameters instead: 
const {
items: propsItems,
height,
enableShadow,
shadowStyle: propsShadowStyle,
indicatorStyle,
labelStyle = DEFAULT_LABEL_STYLE,
selectedLabelStyle = DEFAULT_SELECTED_LABEL_STYLE,
labelColor,
selectedLabelColor,
uppercase,
iconColor,
selectedIconColor,
activeBackgroundColor,
backgroundColor = Colors.$backgroundElevated,
faderProps = DEFAULT_FADER_PROPS,
containerWidth: propsContainerWidth,
centerSelected,
spreadItems = true,
indicatorInsets = Spacings.s4,
indicatorWidth,
containerStyle,
testID
} = …
```

bugfix: remove TabController.TabBar defaultProps, use JavaScript default parameters instead

---

src/components/sectionsWheelPicker/SectionsWheelPicker.driver.tsx

Added handling for custom testID in the `SectionsWheelPicker` driver. Taking just the element isn't enough to get the testID we need to go one level down (taking the props from the instance).
SectionsWheelPicker - Fixed driver custom testID capture.
MADS-4398

SectionsWheelPickerDriver - Fixed handling of custom testID.

---

src/components/textField/index.tsx

TextField - only use leadingAccessoryRef when needed (i.e. floatingPlaceholder={true})
If the user has a function component for `leadingAccessory`:
```
export const LeadingAccessory = () => {
return <Text marginR-2>leading accessory</Text>;
};
```
They will get an error since we require a ref for the `leadingAccessory` and in a function component it needs to be forwarded.
One solution is to use `React.forwardRef`, however this can be avoided in cases where `floatingPlaceholder={false}` because that's the only reason to have the `ref`.
TextField - only require `leadingAccessory` to have a ref when needed (i.e. floatingPlaceholder={true})
Channel (Aug. 4th)

TextField - only use leadingAccessoryRef when needed (i.e. floatingPlaceholder={true})

---

src/components/picker/PickerItemsList.tsx

When passing items as empty array to the Picker, it will report an error
error message:  Cannot read property 'value' of undefined
When passing items as empty array to the Picker, it will report an error.

fix: picker items list is error when array is empty

---

demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/button/index.tsx

Button `borderWidth` grow outside the container fix for outline button.
In outline mode, the padding isn't negative anymore so the border doesn't fill the button container inside part.
Snippet to reproduce:
```
import {View, Colors, Stepper, Button} from 'react-native-ui-lib';
state = {outlineWidth: 1};
render() {
const {outlineWidth} = this.state;
return (
<View bg-grey80 flex padding-20 center gap-s3>
<Button label="Button" outline onPress={() => {}} outlineWidth={outlineWidth}/>
<Button label="Button" outline round onPress={() => {}} outlineWidth={outlineWidth}/>
<Button label="Button" onPress={() => {}} outlineWidth={outlineWidth} outlineColor={Colors.red30}/>
<Button label="Button" round …
```

button border width grow outside the container

---

src/components/chip/index.tsx

Enabled the chip to get only partial width and height to the size prop. Currently if you wanted you couldn't change only one of them (typing wise)
Chip - changed size typings.
MADS-4439

enabled partial sizes to the chip size

---

src/incubator/Dialog/index.tsx
src/incubator/Dialog/useDialogContent.tsx

The new useDialogContent hook was creating a component (DialogContent) on every render and then rendering it. This component is a "new" component every time therefore causing the component to render nonstop.
This could also be solved using useMemo but I don't see any use to it since DialogContent has no state.
Incubator.Dialog - Fixed content renders.
MADS-4444

Incubator.Dialog - Fixed content component being created on every render.

---

src/components/WheelPicker/index.tsx

WheelPicker separators was rendered above the AnimatedFlatList, which cause that the separator render over the current item.
example code snippet (from the example screen):
```
<WheelPicker
initialValue={'February'}
activeTextColor={Colors.$textPrimary}
inactiveTextColor={Colors.$textNeutralHeavy}
items={monthItems}
textStyle={Typography.text60R}
numberOfVisibleRows={3}
separatorsStyle={{backgroundColor: Colors.red70}}
/>
```
WheelPicker separators render below the list items.          
#3028

wheel picker separators code refactor

---

src/components/picker/PickerItemsList.tsx

Remove default background color from `PickerItemList` to let the user pass `overlayBackgroundColor` to the Modal.
Please check this in dark mode also.
Picker support for Modal `overlayBackgroundColor`, removed default color from PickerItemList.
#3111

removed default background from picker item list

---

src/components/tabController/useScrollToItem.ts

TabController - fix indicator when using old reanimated (ignore TS)
TabController - fix indicator when using old reanimated (ignore TS)
None

TabController - fix indicator when using old reanimated (ignore TS)

---

demo/src/screens/ExampleScreenPresenter.tsx
demo/src/screens/MainScreen.js
demo/src/screens/componentScreens/ConversationListScreen.js
demo/src/screens/componentScreens/DrawerScreen.tsx
demo/src/screens/componentScreens/IconScreen.tsx
demo/src/screens/componentScreens/NumberInputScreen.tsx
demo/src/screens/componentScreens/PickerScreen.tsx
demo/src/screens/componentScreens/TabControllerScreen/index.tsx
demo/src/screens/componentScreens/index.js
demo/src/screens/incubatorScreens/IncubatorToastScreen.tsx
demo/src/screens/incubatorScreens/PanViewScreen.tsx
demo/src/screens/incubatorScreens/index.js
demo/src/screens/index.js
demo/src/screens/realExamples/Pinterest/index.tsx
demo/src/screens/realExamples/index.js
src/components/WheelPicker/index.tsx
src/components/drawer/Swipeable.tsx
src/components/drawer/drawer.api.json
src/components/drawer/index.tsx
src/components/fadedScrollView/index.tsx
src/components/scrollBar/index.tsx
src/components/tabController/apis/tabController.api.json
src/components/tabController/index.tsx
src/incubator/Slider/index.tsx
src/incubator/TouchableOpacity.tsx
src/incubator/panView/index.tsx

⚠️ GestureHandlerRoot - wrap components instead of screens
GestureHandlerRoot - wrap components instead of screens

GestureHandlerRoot - wrap components instead of screens

---

jestSetup/jest-setup.js
src/components/dateTimePicker/DateTimePicker.driver.ts
src/components/dateTimePicker/__tests__/index.spec.tsx
src/components/dateTimePicker/index.tsx
src/testkit/index.ts
src/utils/dateUtils.ts
src/utils/index.ts

Added handling to invoke onChange only when the value really change.
DateTimePicker - onChange fixes. Only calls onChange when value really changes.
MADS-4209
MADS-4210
MADS-4211

DateTimePicker - invoke value change only on real change

---

jestSetup/jest-setup.js
src/commons/Constants.ts

inside Constants.ts made statusBarHeight dynamic to mobile orientation changes
Instead of using StatusBarManager.HEIGHT, now setStatusBarHeight will use StatusBarManager.getHeight() method which provides the right height when called (HEIGHT is declared once when the app initialized)
When starting IOS application in landscape mode and then changing to portrait statusBarHeight value wont change and remain 0.
Fix statusBarHeight value to by dynamic when changing orientation

Make Constants.statusBarHeight dynamic on phone orientation change

---

eslint-rules/lib/rules/no-direct-import.js
eslint-rules/lib/utils/importUtils.js
eslint-rules/tests/lib/rules/no-direct-import.js

Fixed `addToImports` to handle default import.
Eslint - Fixed default import rule capture.
MADS-4416

Eslint - Fix default import capture

---

docuilib/src/theme/ReactLiveScope/index.js
scripts/buildDocs.js
src/components/image/image.api.json
src/components/textField/textField.api.json
src/components/touchableOpacity/touchableOpacity.api.json
src/components/view/view.api.json

Support live code for components .
* Need to add components to `ReactLiveScope` and test all relevant components.
* Some snippets need to be fixed.
* Looks like the `$1` (etc) are ignored (at least in the components I've tested).
* In `View`: `<View style={{width: 50, height: 50}} bg-orange50/>` is working while `<View width={50} height={50} bg-orange50/>` is not working (I did not test in the webDemo or dig deeper, it is also working in `Image` for example).
None
Ticket 4470

Support live code for components

---

src/components/maskedInput/index.tsx

Add migration message to MaskedInput component
It's actually an old migration but I noticed now I didn't add any warning for the open source users
Add migration message to MaskedInput component

Add migration message to MaskedInput component

---

demo/src/screens/MainScreen.js
demo/src/screens/SettingsScreen.js
demo/src/storage.ts

Add recent screens chips feature to our demo app for easy access
Add recent screens chips feature to our demo app for easy access

Add recent screens chips to our demo app for easy access

---

docuilib/index.js
docuilib/package.json

Patch PR, exporting `src index` file of `uilib-docs` from package root instead from src only.
Based on [PR](https://github.com/wix/react-native-ui-lib/pull/3286).
`uilib-docs` src index file export.
None

uilib-docs src index export

---

src/style/__tests__/colors.spec.js
src/style/colors.ts
src/style/scheme.ts

Add Colors.getColor API for getting a color in a specific schemeType regardless to current scheme 
usage: `Colors.getColor('$backgroundPrimaryHeavy', 'light')`
Add `Colors.getColor` API for getting a color in a specific schemeType regardless to current scheme. usage: `Colors.getColor('$backgroundPrimaryHeavy', 'light')`
MADS-4505

Add Colors.getColor api to get a color by token name and schemeType

---

docuilib/index.js
docuilib/package.json

uilib-docs new version 3.1.3
changed the `main` entry point in `package.json` file to export `ReactLiveScope`.
uilib-docs new version 3.1.3
None

uilib-docs new version 3.1.3

---

src/components/sortableGridList/index.tsx
src/components/sortableList/index.tsx

Fix sortable list components flexMigration  to use a container with flexGrow
Using flex caused issue when rendering the list in a specific layout with horizontal direction
```
<View flex>
<View>
<SortableList horizontal ...../>
</View>
<View>
```
Fix sortable list components flexMigration

Fix sortable list components flexMigration

---

src/components/gridList/useGridLayout.ts
src/components/sortableGridList/__tests__/usePresenter.spec.tsx
src/components/sortableGridList/index.tsx
src/components/sortableGridList/usePresenter.ts

This change does not fix an issue but I think it improves the code
SortableGridList - single source of truth for itemWidth and itemSpacing
None

SortableGridList - single source of truth for itemWidth and itemSpacing

---

docuilib/src/components/ColorsSection.js

Docs Colors page, onTokenPress show hex value and system color.
This change is according to the UX request.
None
None

onTokenPress show hex value and system color

---

src/components/dash/index.tsx
src/components/dialog/DialogDismissibleView.tsx
src/components/icon/index.tsx
src/components/picker/index.tsx
src/components/stackAggregator/index.tsx

React will stop support `defaultProps` in feature major release warning.
Migrate `defaultProps` to parameter props for: `Dash, DialogDismissibleView, Icon, Picker, StackAggregator`.
Related React docs [link](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops)
Functional component `defaultProps` migrate to `parameter props`.
Related issue #3285

Components defaultProps migrate to default parameters

---

docuilib/src/components/ComponentPage.tsx
src/components/test.api.json

Docs - section - renaming 'massage' type 'banner' to align with component name
Docs - section - renaming 'massage' type 'banner'

Docs - section - renaming 'massage' type 'banner'

---

src/components/colorPicker/index.tsx

`ColorPicker.Dialog` exporting `ColorPickerDialog`.
This export help us to use `ColorPickerDialog` after package build (usage for Doc's).
Checked by `build:local` package.
`ColorPicker.Dialog` exporting `ColorPickerDialog`.
None

ColorPicker.Dialog exporting ColorPickerDialog

---

demo/src/screens/componentScreens/PickerScreen.tsx
src/components/actionSheet/index.tsx
src/components/picker/PickerItemsList.tsx
src/components/picker/index.tsx
src/incubator/Dialog/types.ts
src/incubator/expandableOverlay/index.tsx

I fixed here couple of things
- First, I'm always using the new dialog (Incubator.Dialog) in Picker since `useDialog` is a new feature there's no need to go thru migration
- There were some issues when the dialog height. When the user don't pass any height it should based the dialog height on its content. I fixed how the height is set and the layout inside PickerItemsList component
Picker - Fix dialog UI when passing useDialog

Fix Picker to use new dialog and also fix height issues

---

demo/src/screens/__tests__/__snapshots__/AvatarScreen.spec.js.snap
src/components/animatedImage/index.tsx

This is a fix of a rare case of infinitive skeleton  animation in AnimatedImage component that happens when the component is invisible.
AnimatedImage
This issue could happen for example in a long scroll list of animated images that are out of screen. In that case image is not starting to being loaded but we do start to show the animation (invisible).
This is not a real problem in production, but it does brakes Detox tests in components that are using AnimatedImage

Fixed rare case of infinitive animation of animated image

---

src/components/tabController/TabBarItem.tsx

There was an error occurring when using a tab item with a trailingAccessory which was passed with a ref on it. We're not sure what exactly causes the error but seems like taking the onPress outside of the scope of the handler fixes the error.
TabBarItem - onPress taken from props at the beginning.
MADS-4537

Fix error with the TabController and Gesture Handler when passing a ref

---

scripts/docs/buildDocsCommon.js

Remove double header when component has Hero section by setting an empty string in markdown title
N/A

Remove double header when component has Hero section

---

docuilib/src/components/pageComponents/ContentItem.tsx
src/components/test.api.json

Added handling for the component props type so now it will add `"` for strings.
N/A
N/A

Added handling for string prop in component content.

---

src/commons/Constants.ts
src/incubator/Calendar/__tests__/DateUtils.spec.ts

Fix for StatusBarManager undefined for RN with new architecture. 
Constants.ts - Fixed StatusBarManager being undefined with new RN architecture. 
7.34.2-snapshot.5844
#3320 
#3329

fix: 🐛 status bar manager issue with new rn fabric

---

scripts/docs/buildDocsCommon.js

I want to create (in private) some api.json files that will be part of the services section (not components) 
I updated the build script to create relevant md files in a separate (services) folder 
N/A

Build docs of services category in a separate folder

---

src/components/tabController/PageCarousel.tsx
src/components/tabController/TabBar.tsx
src/components/tabController/useScrollToItem.ts

`TabController` support RTL on IOS and Android.
After the RN 73 upgrade there isn't and RTL issue on Android but on IOS.
Fixing the issue in `TabController` by reversing the selected index when using RTL on IOS.
`TabController` support RTL on IOS and Android.
MADS-4571

refactor: simplify RTL handling in tab controller components

---

demo/src/screens/componentScreens/DateTimePickerScreen.tsx
src/components/dateTimePicker/index.tsx

Add textColor and backgroundColor props to DateTimePicker component
This allows us to control the color we use in the component and have it support branded colors properly 
Add textColor and backgroundColor props to DateTimePicker component
MADS-4583

Add textColor and backgroundColor props to DateTimePicker component

---

src/components/button/types.ts

Changed `ButtonProps.iconProps` to use `IconProps` instead of `ImageProps`.
Button - Fixed `iconProps` to use `IconProps`;
MADS-4593

Update ButtonProps to use IconProps for iconProps type

---

src/components/textField/ClearButton.tsx
src/components/textField/index.tsx
src/components/textField/presets/outline.ts
src/components/textField/presets/underline.ts
src/components/textField/types.ts

TextField - ClearButton - fix right margin with `preset={'outline'}`
To test use:
```
<TextField value={'Test '} showClearButton preset={'underline'}/>
<TextField value={'Test '} showClearButton preset={'outline'}/>
```
TextField - ClearButton - fix right margin with `preset={'outline'}`
See internal channel

TextField - ClearButton - fix right margin

---

src/components/picker/PickerItemsList.tsx

Fixes bug where for some searched values in the Picker, the FlatList starts at an incorrect offset after the search. The FlatList items change, causing it to change its height and make it start the scroll at some negative offset. I've made it take the entire height that is left so this way the height will not change when the content changes so theres no jump.
I'm not sure if this is the correct solution. As it seems when the items change the FlatList goes under the TextInput, like having a negative offset so the picker item seems cut. After scrolling a little the item goes to its correct place and scroll resets correctly.
1. Open the modal
2. Search for Sh
3. "Shell" item should be cut
```tsx
import {View, Picker} from 'react-native-ui-lib';
const …
```

Picker - Fix wrong offset when items change from search

---

src/components/floatingButton/index.tsx

When the `FloatingButton` is rendered inside the `Keyboard.KeyboardTrackingView` its not pressable. Removing the absoluteFillObject from the containing view style seems to solve this.
**ran it with a snapshot version in private. All test are passing but there is a chunk below the the button for some reason. Is also happens with a different component so its probably not related whats inside that view.**
FloatingButton - Fixed not pressable when wrapped with Keyboard.KeyboardTrackingView.
Snippet to reproduce:
```tsx
import React, {useRef} from 'react';
import {View, TextField, Button, Keyboard, FloatingButton} from 'react-native-ui-lib';
const PlaygroundScreen = () => {
const textInput = useRef<any>(null);
return (
<View bg-grey80 flex>
<TextField
label="Enter Text"
placeholder="Type …
```

FloatingButton - Not pressable when wrapped with Keyboard.KeyboardTrackingView.

---

package.json
yarn.lock

Building android demo fails on blur view dependencies. Updating blur view version fixes this issue.
BlurView - Updated dependency to version 4.4.1
Seems like a similar issue: https://github.com/Kureev/react-native-blur/pull/626

Updated blur view version - fix for building android demo

---

src/components/hint/__tests__/index.spec.tsx
src/components/view/View.driver.new.ts

Add support to flatten style in View driver, this helps with testing specific cases when styles are a complex, nested object
Support flatten style in View driver

Refactor HintDriver to allow optional style flattening in tests

---

src/components/avatar/__tests__/index.spec.js

These tests were not supposed to be deleted in the avatar hit target change pr (https://github.com/wix/react-native-ui-lib/pull/3521)
N/A
N/A

Reverted the deletion of the avatar tests

---

demo/src/screens/componentScreens/HintsScreen.tsx
src/components/hint/hooks/useHintLayout.ts

Fix issue with Hint's targetFrame feature after recent refactor 
Also, update the example demonstrating this feature
Fix Hint's targetFrame position

Fix issue with hint targetFrame prop

---

src/components/button/index.tsx

Fixed accessibleHitSlop overriding hitSlop when its passed with undefined.
N/A
MADS-4591

Button - undefined hitSlop overrides internal hitSlop

---

webDemo/webpack.config.js

Add `uilib-native` module to project source paths.
Since we upgraded to RN 0.73 I find this error appears about the native component coming from `uilib-native`.
To reproduce the issue, run `npm install` in the webDemo folder and start the project.
None
None

add uilib-native module to project source paths

---

src/components/badge/__tests__/index.spec.js
src/components/badge/index.tsx

Badge should be pimple size when label undefined
Fix Badge should be pimple size when label undefined
MADS-4577

fix badge should be pimple when label undefined

---

src/components/avatar/avatar.api.json
src/components/avatar/index.tsx

AnimatedImage doesn't work on web platform.
When using animated Avatar we render AnimatedImage which doesn't work, for now when using web we will set animate to false to prevent Avatar not to render as expected.
snippet:
```
<Avatar source={src} animate /> 
```
Avatar with animated not supported on web.
MADS-4577

Avatar animate mode not supported on web

---

.eslintrc.js
src/components/card/index.tsx
src/components/connectionStatusBar/index.tsx
src/components/dateTimePicker/index.tsx
src/components/dateTimePicker/useOldApi.ts
src/components/modal/index.tsx
src/components/pieChart/index.tsx
src/components/skeletonView/index.tsx
src/components/svgImage/index.tsx
src/incubator/slider/SliderPresenter.ts
src/services/HapticService.ts
src/services/LogService.ts

Forbid using console.error as it is being sent to Sentry
I've added a few `// eslint-disable-next-line max-len`, sorry if it'll cause confusion.
Together with private 4899
Forbid using console.error
None

Forbid using console.error as it is being sent to Sentry

---

docuilib/src/components/pageComponents/ContentItem.tsx

When using Figma embed link we should add `page-selector=false` to hide the page selector on our docs.
`modifiedValue` takes care of that, when the embed link doesn't include `page-selector`.
ContentItem - Figma embed hide page selector.
None

Update iframe src in ContentItem to include page-selector parameter

---

src/components/timeline/timeline.api.json

Fix timeline docs

---

scripts/docs/buildDocsCommon.js

Add support for foundation category in documentation build process
Now it will create a foundation dir at root level of the docs instead of creating it inside the components folder
NA

Add support for foundation category in documentation build process

---

docuilib/src/components/UILivePreview.tsx
docuilib/src/components/pageComponents/Usage.tsx
scripts/docs/buildDocsCommon.js

Docs - `Usage` section, should show live playground or code block.
If the component is part of the `ReactLiveScope` we should show live playground else code block.[
Old PR](https://github.com/wix/react-native-ui-lib/pull/3452) - closed because of the `api` files.
Docs - `Usage` section, should show live playground or code block.
None

Usage component support live preview for compatible components

---

docuilib/src/components/ComponentPage.tsx
docuilib/src/components/pageComponents/Banner.tsx
docuilib/src/components/pageComponents/SectionHeader.tsx
src/components/test.api.json

Dev tab - Don't render empty sections or the tab:
No usage without snipper, no banner without description and no Dev tab without props
Dev tab - Don't render empty sections or the tab

Dev tab - Don't render empty sections or the tab

---

docuilib/package.json
docuilib/src/components/ComponentPage.tsx

Fix not showing dev tab when props is an empty array
NA

Fix not showing dev tab when props is an empty array

---

docuilib/package.json
src/components/timeline/timeline.api.json

Docs - Timeline - fix live components
Docs - Timeline - fix live components

Docs - Timeline - fix live components

---

docuilib/src/components/UILivePreview.tsx
docuilib/src/components/pageComponents/Usage.tsx
docuilib/src/utils/componentUtils.ts

New componentUtils file to include common logic, in this case `isComponentSupported` which is used in `UILivePreview` and `Usage` components.
New componentUtils file to include common logic.
None

Component Utils for docs

---

docuilib/package.json
docuilib/src/components/pageComponents/ContentItem.module.scss
docuilib/src/components/pageComponents/ContentItem.tsx

Docs - LiveCode in table cell - block interaction
Docs - LiveCode in table cell - block interaction

Docs - LiveCode in table cell - block interaction

---

src/commons/Constants.ts
src/components/colorPicker/ColorPickerPreview.tsx

Adding `getFontScale` to constants and removing direct usage of PixelRatio.
Constants - Added getFontScale.
AI of MADS-4620

Constants - add getFontScale

---

scripts/docs/buildDocsCommon.js

Log all kind of statistics when generating docs like components that have duplicate occurrences (public/private), components that are missing snippets, etc.. 
N/A

Log all kind of statistics when generating docs

---

docuilib/docusaurus.config.js
docuilib/package.json
docuilib/src/components/MainSection.tsx

Fixed view docs button going to `next` version of docs when in localhost. This was breaking private docs because we don't use next in it.
N/A
N/A

Docs - Fix development main entry

---

docuilib/package.json
docuilib/src/components/ComponentPage.tsx
src/components/tabController/apis/pageCarousel.api.json

Fixing missing Dev page in some components, and wrap ComponentPage with BrowserOnly
NA

Fix missing dev page in some components

---

docuilib/package.json
docuilib/src/components/UILivePreview.module.scss
docuilib/src/components/UILivePreview.tsx
docuilib/src/components/pageComponents/TableSection.tsx
docuilib/src/css/custom.css
docuilib/src/hooks/useFormattedCode.ts
docuilib/src/pages/livePreview.module.css
docuilib/src/pages/livePreview.tsx
docuilib/src/theme/ReactLiveScope/index.js
docuilib/yarn.lock
src/components/button/button.api.json
src/components/sortableList/SortableList.api.json

Improve live code visuals
- Move to css styling 
- Add theme to the live code
- Fix preview container flex to behave like it does in mobile
- Increase page max width 
Unrelated, fix minor issue in TableSection to avoid error when missing cell (item) data - this will show empty cell instead of throwing a vague error 
N/A

Improve live code visuals

---

src/components/icon/index.tsx

Icon `size` prop support object with `width, height`.
`iconSize` moved into `useMemo` depend on the size type.
Icon `size` prop support object with `width, height`.
None

IconProps to support size as an object for width and height

---

src/components/button/button.api.json
src/components/button/types.ts

Update button docs, remove stuff that are not relevant to public docs 
I did keep some UX guidelines that are still possible to achieve 
N/A

Update button docs

---

package.json
yarn.lock

Upgrade flashlist version to 1.7.6 to be aligned with the Engine
Upgrade flashlist to version 1.7.6 in our demo app

Upgrade flashlist version to 1.7.6

---

demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
src/components/textField/Input.tsx

It seems like setting `left` alignment for the textfield input cause issue with displaying ellipsis 
changing it to undefined (basically the default behavior) fix it 
This fix the issue only iOS, on Android the issue remains
Fix missing ellipsis when text is overflowing in TextField
https://wix.slack.com/archives/C3B1EMVF0/p1744121944667609

Fix issue with missing ellipsis

---

docuilib/src/theme/ReactLiveScope/index.js
src/components/avatar/avatar.api.json

Add relevant docs sections to Avatar docs 
Remove old deprecated props from api.json
Update snippet
NA

Add Avatar component to ReactLiveScope and update API documentation

---

src/components/drawer/index.tsx

Currently we can set `itemsTintColor` for all the drawer items, if we want to set each drawer is own colors we need to expose `text/icon` color.
Drawer item support custom text and icon colors.
Drawer item support custom text and icon colors.
MADS-4291

Drawer item custom icon and text colors

---

src/components/timeline/Point.tsx
src/components/timeline/types.ts

Point support custom `labelColor` prop to override the default token `$textDefaultLight`.
Timeline - Point support custom `labelColor` prop 
MADS-4291

Point new labelColor prop

---

src/components/timeline/index.tsx

Timeline `useThemeProps` implemtion to support usage of config file.
Timeline `useThemeProps` implemtion to support usage of config file.
MADS-4291

Refactor Timeline component to use theme props to support config.

---

src/components/WheelPicker/wheelPicker.api.json
src/components/chipsInput/chipsInput.api.json
src/components/drawer/drawer.api.json
src/components/image/image.api.json
src/components/numberInput/numberInput.api.json
src/components/pageControl/pageControl.api.json
src/components/pieChart/pieChart.api.json
src/components/sortableGridList/sortableGridList.api.json
src/components/switch/switch.api.json

Add missing pages to with figma embed
N/A
MADS-4671

Docs - Added figma embed links for missing pages

---

src/components/WheelPicker/Item.tsx
src/components/picker/PickerItemsList.tsx
src/components/picker/index.tsx

Picker - useWheelPicker fix accessibility
Picker - useWheelPicker fix accessibility
4712

Picker - useWheelPicker fix accessibility

---

docuilib/package.json
docuilib/src/components/pageComponents/ContentItem.tsx

Figma embed removed footer ([Figma docs](https://www.figma.com/developers/embed#resources) look for `footer`)
Figma embed removed footer
None

figma embed removed footer

---

scripts/docs/buildDocsCommon.js

Added composite component category to docs build script.
Docs - added composite to build script
MADS-4671

Docs - added composite tab to docs build script

---

scripts/docs/buildDocsCommon.js

This reverts commit 67c484e63b2b7178755496752aab637f0702c624.

Docs - remove composite tab from docs build script

---

src/components/chip/__tests__/index.spec.tsx
src/components/chip/chip.driver.ts
src/testkit/index.ts

Chip Driver, and basic Chip test.
Chip Driver, and basic Chip test.
MADS-4456

Add ChipDriver and associated basic tests for Chip component

---

src/components/timeline/Line.tsx
src/components/timeline/Point.tsx
src/components/timeline/__tests__/driver.index.spec.tsx
src/components/timeline/index.tsx
src/components/timeline/line.driver.ts
src/components/timeline/point.driver.ts
src/components/timeline/timeline.driver.ts
src/components/timeline/types.ts
src/testkit/index.ts

TimeLine component `testID` prop set to use for testing improvements, passed to the sub components: `Line, Point`.
TimeLine `testID` prop.
None

Timeline - Add testIDs

---

src/components/picker/helpers/useNewPickerProps.tsx

When passing `customPickerProps` with `modalProps` the default modal props are getting overridden.
This pr fixing the issue, by merging the default props with the user custom modal props to not override the animation unless the user passed the relevant props. 
Snippet:
```
<Picker
placeholder="Favorite Language"
value={language}
onChange={item => setLanguage(item)}
items={options}
customPickerProps={{
modalProps: {}
}}
/>
```
Picker merging default modal props with the user custom modal props.
None

Picker - enhance modalProps merging in useNewPickerProps

---

src/components/picker/Picker.driver.new.ts
src/components/picker/__tests__/index.spec.tsx

Picker - test items exists (Automation gap)
Picker - test items exists
ticket 4716

Picker - test items exists (Automation gap)

---

docuilib/package.json
docuilib/src/components/ColorsSection.js

Colors token box to copy token on press
Docs - Colors Token in colors table now copies token when clicking

Docs - Colors token box to copy token

---

docuilib/src/components/UILivePreview.module.scss
docuilib/src/components/UILivePreview.tsx

Docs - fix playground preview divider
Remove prettify button - crashes the site when editing the code in the live editor
Docs - fix playground preview divider

Docs - fix playground preview divider

---

src/components/button/button.api.json

Docs - button api update
Docs - button api update
N/A

Docs - button api update

---

scripts/release/prReleaseNotesCommon.js

Release notes script now include pr labels, filter out PR's with `hotfix` label.
This is part of the Hotfix release notes we spoke about, and ignoring those PR in the next version.
Release notes script now include pr labels, filter out PR's with `hotfix` label.
None

Release Notes Script - to include labels and filter out hotfixes

---

scripts/release/prReleaseNotesCommon.js

Changed release notes generation script to ignore hot fixed prs.
Changed release notes generation so it will take hotfix prs when generating a patch release release notes.
Infra - release notes generation script now excludes hot fixed prs.
MADS-4718

Filetered hotfix prs from release notes

---

.github/workflows/deployDocs.yml

Enabling the docs build workflow to run on every branch but only deploy on release branch. This will verify that the docs build passes whenever we change things.
Docs - added docs build check.
N/A

Docs workflow - Run check on every branch

---

src/components/expandableSection/index.tsx

Rendering a view when the expandable section is not pressable.
ExpandableSection - render view when not pressable (Accessiblity)
MADS-4748

ExpandableSection - Render view when not pressable

---

src/components/chip/index.tsx

Increased chip hit slop to fix 48x48 hit target.
Chips - Increased chip hit slop to hit 48x48 hit target for accessibility
N/A

Chip - Increased hit slop for accessibility

---

lib/scripts/releaseNative.js

uilib-native - add a snapshot release
`master` will still release the `uilib-native` package.
Starting a build with the `snapshot` message (also requires incrementing the version) will release a snapshot version with the build number (to allow for fixes without further incrementing the version)
None
None

uilib-native - add a snapshot release

---

src/components/checkbox/index.tsx
src/components/pageControl/index.tsx
src/components/radioButton/index.tsx
src/utils/styleUtils.ts

Carousel - pageControl set hitSlop as part of a11y fix.
Moved `getAccessibleHitSlop` function into `StyleUtils` to make reuse instead of duplications.
Carousel - pageControl set hitSlop as part of a11y fix.
MADS-4757

Carousel - page control hit slop fix a11y

---

demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
src/style/designTokens.ts

Update `danger` design tokens colors.
Changed -  `$backgroundDangerHeavy, $textDangerLight, $iconDangerLight, $outlineDanger` from `red30` to `red10`.
Note that now:
`$textDangerLight equal to $textDanger` and `$iconDangerLight equal to $iconDanger`
Colors - Update `danger` design tokens colors (a11y).
MADS-4756

Colors - update danger design tokens colors (a11y)

---

lib/components/HighlighterOverlayView/HighlighterViewNativeComponent.ts
lib/components/Keyboard/KeyboardTrackingView/KeyboardTrackingViewNativeComponent.ts
package.json
yarn.lock

Change from codegenNativeComponent to requireNativeComponent in order to fix error after transpilation
None
None

Change from codegenNativeComponent to requireNativeComponent in order to fix error after transpilation

---

src/components/avatar/index.tsx

When the user pass a custom accessibility label (when avatar is NOT clickable) we are ignoring it because the reader just read the avatar text. 
This pass on the label to the Avatar text to give the user more control
Fix Avatar custom accessibility label when Avatar is not clickable

Pass on avatar accessibility label

---

demo/src/screens/componentScreens/ButtonsScreen.tsx
src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/button/__tests__/index.spec.js
src/components/button/button.api.json
src/components/button/index.tsx
src/components/button/types.ts

New `customBackground` prop to the Button component that allows users to render custom React elements as button backgrounds.
This prop takes precedence over the `backgroundColor`.
Button - Added `customBackground` prop to enable custom background elements
N/A

feat(Button): add customBackground prop for custom background elements

---

.github/workflows/pr-description-check.yml

Adding a workflow that will fail when the pr description doesn't have content in one of the sections.
Infra - added pr description validation check
N/A

feat: add PR description validation workflow
