demo/src/screens/componentScreenScreens/ModalScreen.js

add demo Modal Screen close function

---

package.json

refs https://github.com/react-native-community/react-native-blur/pull/211

pin react-native-blur version due to critical bug in 3.1.0

---

package.json

our fix was merged and released in 3.1.1
https://github.com/wix/react-native-ui-lib/pull/13

unpin react-native-blur

---

demo/src/screens/componentScreens/ToastsScreen.js
src/components/toast/index.js

Added relative positioning for the toast container and improved the component and its animations to support it.

Relative position

---

src/screensComponents/modal/TopBar.js

Hi. This PR is related to this JIRA task - https://jira.wixpress.com/browse/WSM-354

increase top bar button tap area

---

src/components/button/index.js

Allow passing allowFontScaling to Text in Button component

---

src/components/actionBar/index.js

first commit

---

src/components/button/index.js

Fix button component's borderRadius in Android API 16 and 17

Fix issue#48

---

demo/src/screens/MainScreen.js
src/components/button/index.js
uilib-docs/src/pages/modifiers.js
uilib-docs/src/pages/modifiers.scss
uilib-docs/src/templates/component.js

Adding components to the demo app's main screen

Adding textInput for components search

---

demo/src/screens/MainScreen.js
src/components/avatar/index.js
src/components/button/index.js
src/components/card/CardSection.js
src/components/card/index.js
src/components/inputs/MaskedInput.js
src/components/inputs/TextArea.js
src/components/inputs/TextInput.js
src/components/listItem/index.js
src/components/picker/PickerItem.js
src/components/picker/index.js
src/components/tagsInput/index.js
src/components/touchableOpacity/index.js
src/lists/BaseListItem.js
src/lists/gridList/GridListItem.js
src/lists/gridList/GridListNewItem.js
src/lists/gridList/index.js
src/screensComponents/modal/index.js
uilib-docs/gatsby-config.js
uilib-docs/src/pages/modifiers.js
uilib-docs/src/pages/modifiers.scss
uilib-docs/src/templates/component.js

Adding link to @extends; ignoring unused components; hide props table when no props for component; editing modifiers page

Demo app update

---

demo/src/screens/componentScreens/AvatarsScreen.js
src/components/avatar/__tests__/index.spec.js
src/components/avatar/index.js

Adding support to status prop in Avatar component.

Fix issue#24

---

demo/src/screens/MainScreen.js
src/components/actionSheet/index.js

Fix issue - actionSheet: items aligned left with title

---

.eslintrc
demo/package.json
demo/src/screens/componentScreens/BadgesScreen.js
package.json
src/components/badge/index.js

Fix for Badge stretch when label value change number of chars

---

demo/src/menuStructure.js
demo/src/screens/componentScreens/FeatureHighlightScreen.js
src/components/featureHighlight/__tests__/index.spec.js
src/components/featureHighlight/index.js
src/components/index.js
src/index.js

FeatureHighlight adjustments to guidelines, including passing frame to be highlighted

FeatureHighlight adjustments to guidelines

---

README.md

Using js was leading to incorrect highlighting for properties like `paddingT-120`.

Change readme to use jsx syntax highlighting.

---

lib/android/src/main/AndroidManifest.xml
package.json

Text input fixed title

---

src/components/inputs/TextInput.js
src/components/inputs/__tests__/TextInput.spec.js

Removing underline red color change when character counter reaches its limit

Removing underline red color change when character counter limit

---

src/components/inputs/TextInput.js
src/components/inputs/__tests__/TextInput.spec.js

Text input char limit

---

src/components/inputs/TextInput.js

Bug fix: character counter not showing in View (only in ScrollView)

---

demo/src/menuStructure.js
demo/src/screens/nativeComponentScreens/SafeAreaSpacerViewScreen.js
demo/src/screens/nativeComponentScreens/index.js
lib/ios/reactnativeuilib.xcodeproj/project.pbxproj
lib/ios/reactnativeuilib/safearea/SafeAreaManager.h
lib/ios/reactnativeuilib/safearea/SafeAreaManager.m
src/nativeComponents/SafeArea/SafeAreaInsetsManager.js
src/nativeComponents/SafeArea/SafeAreaSpacerView.js
src/nativeComponents/index.js

add a new `SafeAreaSpacerView` which sets its height based on the safe area insets that it gets from the native window.
useful for layouts which include absolutely positioned top/bottom views, where it is hard or impossible to change the layout or wrap everything with RN `SafeAreaView`

add SafeAreaSpacerView

---

demo/src/screens/PlaygroundScreen.js
src/components/card/CardImage.js
src/screensComponents/loaderScreen/index.js
src/screensComponents/modal/index.js

fix for blurView crash in Android

---

src/components/featureHighlight/index.js
uilib-docs/src/templates/component.js

and editing FeatureHighlight docs

Adding important notes to Docs

---

.eslintrc.js
eslint-rules/lib/rules/no-hard-coded-color.js
eslint-rules/lib/utils.js
src/components/badge/index.js
src/components/connectionStatusBar/index.js

Editing eslint's rule 'no-hard-coded-colors'; fixing lints in uilib library

Eslint colors

---

demo/src/screens/componentScreens/FeatureHighlightScreen.js
lib/android/src/main/java/com/wix/reactnativeuilib/highlighterview/HighlighterView.java

Fix for borderRadius prop; fix for innerPadding; fix for recurring frame updates invoked by onDraw()

Android highlighter view

---

.eslintrc.js
src/screensComponents/modal/index.js

issue #135 - Adding blurView prop to pass a custom view to be rendered as BlurView

Modal blur view

---

demo/src/screens/componentScreens/FormScreen.js
src/components/picker/PickerItem.js
src/components/picker/PickerModal.js
src/components/picker/index.js

issue #170 - Adding support for search input text color, placeholder text color, selection color, and for placeholder text

Adding support for search input style props

---

demo/src/screens/componentScreens/ToastsScreen.js
src/components/toast/index.js

issue #134 Adding 'autoDismiss' prop to pass the number of milliseconds to invoke the 'onDismiss' callback (only when passing onDismiss :)

Adding support to autoDismiss functionality

---

.eslintrc.js
android/app/build.gradle
android/app/src/main/java/com/uilib/MainApplication.java
android/settings.gradle
demo/src/screens/componentScreens/TabBarScreen.js
ios/uilib.xcodeproj/project.pbxproj
package.json
src/components/picker/PickerModal.js
src/components/tabBar/TabBarItem.js
src/components/tabBar/__tests__/index.spec.js
src/components/tabBar/index.js

Adding scroll mode to TabBar; 
Adding support for gradient effect on scroll bar; 
Adding support for maxLines, width, divider to TabBarItem.

Tab bar style

---

demo/src/screens/componentScreens/ActionSheetScreen.js
src/components/actionSheet/index.js

issue #149 - Support for icons to default ActionSheet (when sent in 'options' objects' array).

Adding support for icons in default ActionSheet

---

src/components/checkbox/index.js

allows evaluating checkbox status

Add test id to checkbox

---

src/components/inputs/TextInput.js

Fix issue when floating placeholder text was outside parent view
before fix:
After fix:

Fix issue with floatingPlaceholder overflow

---

src/components/inputs/MaskedInput.js

to allow smooth interactions and keyboard events

moving hidden TextInput to front 

---

src/components/avatar/index.js

Added Image props to encapsulate Avatar image props.

Added imageProps

---

src/components/inputs/MaskedInput.js

blocking style passed to hidden TextInput

Masked input

---

src/components/avatar/index.js
src/components/image/index.js

Added imageStyle prop to allow passing additional style props by components which render image

Image - ImageStyle prop

---

demo/src/index.js
demo/src/screens/PlaygroundScreen.js
demo/src/screens/componentScreens/ButtonsScreen.js
demo/src/screens/componentScreens/RadioButtonScreen.js
src/components/button/__tests__/index.spec.js
src/components/button/index.js

Adding a round button option; adding an animated button option

Animated button

---

src/animations/animatedScanner/index.js
src/commons/SelectableComponent.js
src/commons/baseComponent.js
src/components/actionSheet/index.js
src/components/button/index.js
src/components/featureHighlight/index.js
src/components/inputs/TextField.js
src/components/inputs/TextInput.js
src/components/picker/index.js
src/components/radioButton/RadioGroup.js
src/components/switch/index.js
src/components/tabBar/TabBarItem.js
src/components/tabBar/index.js
src/components/tagsInput/index.js
src/components/toast/index.js

Reverts wix/react-native-ui-lib#298

Revert "rename (about to be) deprecated lifecycle methods for future deprecation"

---

src/components/button/index.js

fixed button animation

---

src/components/inputs/TextInput.js
src/helpers/Constants.js

Please check if the warning resolved

rendering expandable modal only when 'expandable'

---

demo/src/screens/DemoScreen.js
demo/src/screens/MainScreen.js
demo/src/screens/componentScreens/InputsScreen.js
src/components/inputs/MaskedInput.js
src/components/inputs/TextField.js
src/components/inputs/TextInput.js
src/components/picker/NativePicker.js
src/components/tagsInput/index.js
src/index.js

TextField has some unit tests included

create a replacement component for TextInput, the TextField.

---

src/components/badge/index.js
src/components/card/index.js
src/components/listItem/index.js
src/screensComponents/loaderScreen/index.js

Adding deprecation warning for animationProps

conditioning Animatable.View with animationsProps;

---

eslint-rules/lib/rules/component-deprecation.js

for deprecated components and their import specifier

adding fix type component_name 

---

demo/src/screens/componentScreens/AvatarsScreen.js
demo/src/screens/componentScreens/BadgesScreen.js
src/components/avatar/index.js

- Refactored Avatar's Badge location logic
- Updated demo screens of Avatar + Badge

Refactored Avatar + Badge, Avatar demo screens

---

src/components/checkbox/index.js
src/components/radioButton/RadioButton.js
src/components/switch/index.js

- Added accessibilityLabel to Switch, Checkbox, RadioButton

Feat/Added accessibilityLabel

---

src/components/carousel/index.js

(when there are a lot of pages, moving from high to low page)

Fix carousel onPageChange not being triggered

---

demo/src/screens/componentScreens/HintsScreen.js
src/components/hint/index.js

Added testID support for Hint component.

Feat/Hint testID

---

src/style/spacings.js
src/style/typography.js

Very small changes, but in screens with a lot of text render time decreased by 50ms (with debugger connected).

Optimize typography and spacing modifier key patterns

---

demo/src/screens/componentScreens/AvatarsScreen.js
src/components/avatar/index.js

- Added support for multiple Avatar Badge positions.
- Added 2 enum presets.
- Updated example screen.

Feat/Avatar - support multiple Badge positions

---

src/components/inputs/TextField.js
src/components/pageControl/index.js
src/components/slider/GradientSlider.js
src/components/slider/index.js

Slider, TextField, PageControl

Accessibility adjustments

---

demo/src/screens/componentScreens/CardsScreen.js
src/components/card/index.js

fix for passing borderRadius 0

---

src/index.js
src/services/LogService.js
src/services/index.js

Feat/Add LogService

---

demo/src/screens/componentScreens/DialogScreen.js

The caching caused wrong text to be shown.

DialogScreen - fix - remove caching

---

src/components/colorPicker/ColorPalette.js
src/components/colorPicker/ColorSwatch.js
src/components/colorPicker/index.js

in ColorPicker, ColorPalette and ColorSwatch

fix import path of internal components

---

demo/src/screens/componentScreens/PickerScreen.js
src/components/picker/index.js

When migrating from native picker to default picker

Fix issue with picker api 

---

demo/src/screens/componentScreens/OverlaysScreen.js
src/components/card/CardImage.js
src/components/image/index.js
src/components/overlay/index.js

(and add support for Card.Image) - using ImageBackground

Fix Overlay with absolute position

---

demo/src/screens/componentScreens/FloatingButtonScreen.js
src/components/floatingButton/index.js

Adding a prop to allow removing the gradient background

Adding 'hideBackgroundOverlay' prop

---

src/components/picker/index.js

Picker + Picker item accessibility fixes.

Fix/Accessibility - picker/item

---

src/components/inputs/TextField.js

Fix for space between placeholder and title in TextField and expandable TextField

TextField - Fix placeholder top space

---

src/components/slider/index.js

I need onSeekStart and onSeekEnd callbacks in Slider

Add onSeekStart and onSeekEnd callbacks to slider

---

demo/src/screens/componentScreens/AvatarsScreen.js
demo/src/screens/componentScreens/PickerScreen.js
demo/src/screens/incubatorScreens/TabControllerScreen/tab3.js
demo/src/screens/interactableComponentScreens/DrawerScreen.js
demo/src/screens/listScreens/ContactsListScreen.js
demo/src/screens/listScreens/ConversationListScreen.js
eslint-rules/tests/component_deprecation.json
eslint-rules/tests/lib/rules/component-deprecation.js
src/components/avatar/index.js

Converting `imageSource` props to `source`

Avatar-ImageSource prop deprecation

---

demo/src/screens/componentScreens/CarouselScreen.js
src/components/carousel/index.js

Adding 'enablePagination' prop to allow blocking multiple pages scroll (full-width pages only)

Carousel - enablePagination

---

src/components/drawer/index.js

- Fix issue with Drawer not being render when not inside a ScrollView (remove flex)
- Fix issue when container style didn't update when changing background color for items

fix minor issues with drawer

---

src/components/view/index.js

Allow passing `inaccessible` prop to View to disable its accessibility (including its nested children)
https://jira.wixpress.com/browse/WOAUILIB-431

View inaccessible prop

---

src/components/dateTimePicker/index.js

There was an issue where the component couldn't have an undefined for the initial value so the placeholder never really worked. 
This is related to https://jira.wixpress.com/browse/WOAUILIB-432

Fix DateTimePicker placeholder, allow undefined as initial value

---

src/components/inputs/TextField.js

Fixes
https://jira.wixpress.com/browse/WOAUILIB-389
https://jira.wixpress.com/browse/WOAUILIB-400

Add TextField accessibility info for required fields and fix accessibility for error messages

---

src/components/actionSheet/index.js
src/components/dialog/index.js
src/components/inputs/MaskedInput.js
src/components/inputs/TextField.js
src/components/listItem/index.js
src/components/picker/PickerItem.js
src/components/picker/PickerModal.js
src/components/picker/index.js
src/components/scrollBar/index.js
src/components/sharedTransition/SharedArea.js
src/components/slider/index.js
src/components/tagsInput/index.js
src/components/toast/index.js
src/incubator/TabController/TabPage.js

PropTypes.elementType is the right prop type to expect a component. Using PropTypes.func as it currentl is causes issues with class components.

Use PropTypes.elementType for components

---

src/components/dateTimePicker/index.js

Fix iOS chosenDate when there was no actual change in wheel picker but the user clicked 'V' button for choosing currently displayed value

DateTimePicker - iOS issue

---

src/components/inputs/TextField.js

fix charCounter state colors; shorting constants names

TextField - fix charCounter state colors

---

demo/src/screens/ExampleScreenPresenter.js

Added: 
- Checkbox post-state update callback arguement 
- RadioGroup row flexWrap styling

Feat/ExampleScreenPresenter - Small additions

---

src/components/inputs/TextField.js

Adding value to accessibilityLabel

TextField - fix accessibility for expandable input

---

src/components/avatar/__tests__/index.spec.js
src/components/avatar/index.js

We need this to enable an image preview of an avatar

Pass avatar container ref

---

src/components/inputs/TextField.js

- Fix issue with animation triggered every time value has changed
- Make the animation useNativeDriver for better performance

fix TextField floating placeholder animation

---

src/components/colorPicker/index.js
src/components/slider/ColorSliderGroup.js
src/components/slider/GradientSlider.js

Adding 'accessibilityLabels' prop to allow custom labels

ColorPicker - Adding accessibility features

---

src/components/picker/index.js

invoke TopBar onCancel callback when dimissing Picker modal

---

expoDemo/MainScreen.js

Add Search Input to our Expo example project

Woauilib 591

---

src/components/colorPicker/ColorPalette.js

ColorPalette - fix orientation change called unnecessarily

---

demo/src/screens/SettingsScreen.js

SettingsScreen - remove section headers from list (also fixes yellow warning about missing keys)

SettingsScreen - remove section headers from list

---

demo/src/screens/componentScreens/CarouselScreen.js
src/components/carousel/CarouselPresenter.js
src/components/carousel/index.js

Carousel - fix various bugs related to tablet, orientation change and Android's screen VS window size.

Carousel - fix various bugs

---

src/components/progressBar/index.js

Will readout `progress bar. ${Math.round(progress)}%`

Feat/ProgressBar - Adding accessibility support

---

src/components/switch/index.js

- Pass accessibilityValue (for e2e testing) 
- Pass an object to accessibilityState (according to rn62 API) 
blocking 
https://github.com/wix-private/wix-react-native-ui-lib/pull/1154

Switch accessibilityValue

---

src/components/dialog/DialogDismissibleView.js

- Fixed the exit animation on iPhoneX (with bottom safe area) 
- Changed the bezier easing values to make the animation smoother.

Dialog Animation

---

markdowns/foundation/style.md

Fix the url for presets in docs.
closes #795

fix url for presets link

---

lib/android/src/main/java/com/wix/reactnativeuilib/keyboardinput/CustomKeyboardRootViewManager.java
lib/components/Keyboard/KeyboardInput/CustomKeyboardView.android.js

Rename CustomKeyboardViewNative --> CustomKeyboardViewNativeTemp for hermes

---

uilib-docs/package.json

Set gatsby to a fixed version until [this](https://github.com/gatsbyjs/gatsby/issues/26038) is resolved.

Docs - set fixed version to gatsby

---

src/components/dateTimePicker/index.js

create onToggleExpandableModal function in DateTimePicker to allow passing callback

create onToggleExpandableModal function

---

src/components/picker/index.js

Dialog-Picker's search was not reset when Dialog canceled

added reset search when modal is dismissed

---

src/components/slider/index.js

moving componentWillMount code to c'tor

Slider - Removing UNSAFE method

---

typings/components/Slider.d.ts

Add missing callbacks to Slider's typings

Update Slider typings

---

demo/src/screens/componentScreens/TabBarScreen.tsx
src/components/tabBar/TabBarItem.tsx

TabBarItem - allow passing style (solves issue ##874)

TabBarItem - passing style 

---

src/components/animatedScanner/index.js

AnimatedScaner - replace 'componentWillReceiveProps' with 'componentDidUpdate'.

AnimatedScaner - remove UNSAFE mothod

---

src/components/actionSheet/index.js

ActionSheet - replace 'componentWillReceiveProps' with 'componentDidUpdate'.

ActionSheet - Remove UNSAFE method

---

demo/src/screens/componentScreens/TabBarScreen.tsx
src/components/tabBar/index.tsx

Passing 'backgroundColor' prop to adjust the entire background and gradient color.

TabBar - Adding 'backgroundColor' prop

---

src/components/image/index.tsx

Link to example is broken in the Image documentation.

Update from .js to .tsx file in docs 

---

demo/src/screens/componentScreens/HintsScreen.js
src/components/hint/index.js

update hint testID's to support e2e tests

hint testID's

---

src/components/textField/index.js

Fix testID duplication that is sent to both input and text area from Picker to TextField.
TextField - Fix 'testID' duplication.

Fix testID duplication

---

generatedTypes/index.d.ts
src/index.ts

Export Dialog and DialogProps (do not merge until the private PR has been approved)
Export Dialog and DialogProps

Export Dialog and DialogProps (do not merge until the private PR has been approved)

---

scripts/buildPackages.js

Add typings to packaged components.
* Keyboards are not handled (they have no typings ATM).
Add typings to packaged components (resolves #910)

Add typings to packaged components

---

scripts/buildPackages.js

Create a style package (add a new package to our already provided packages).
Not sure if we want the `ThemeManager` in this one, what do you think?
Create a style package (add a new package to our already provided packages).

Create a style package

---

package.json
src/.babelrc.json
tsconfig.build.json

Fix generated JS files to include propTypes
Fix generated JS files to include propTypes

Fix generated JS files to include propTypes

---

src/components/slider/index.js

Support passing Slider a testID
Support passing Slider a testID

Add Slider testID

---

demo/src/screens/componentScreens/AvatarsScreen.tsx
src/components/avatar/index.tsx

Cancel label overriding in avatar badge. 
Add example to AvatarScreen.
Support custom text in avatar badge

Support custom text in avatar badge

---

src/components/carousel/__tests__/CarouselPresenter.spec.js
src/components/colorPicker/ColorPalette.js

Carousel - remove references to migrate
Carousel - remove references to migrate

Carousel - remove references to migrate

---

src/components/floatingButton/index.tsx

*Enter description to help the reviewer understand what's the change about...*
Fix children typing for floating button props
*Add a quick message for our users about this change*
Fix typing for floating button props

fix button props typing for floating button

---

package.json

Upgrade to most recent 1.. reanimated version - 1.13.1
reanimated is updated to 1.13.1

upgrade reanimated version

---

demo/src/screens/componentScreens/PickerScreen.js
src/components/picker/PickerItem.js
src/components/picker/PickerPresenter.js
src/components/picker/index.js

Fix issue with missing selected indicator in Picker items
Fix issue with missing selected indicator in Picker items

Fix issue with missing selected indicator in Picker items

---

src/components/badge/index.tsx

Remove unnecessary view from bagde

Remove unnecessary view from bagde

---

src/incubator/WheelPicker/helpers/useListMiddleIndex.ts
src/incubator/WheelPicker/index.tsx

Fixing ESLint errors in the new WheelPicker

fix eslint

---

.eslintignore
.eslintrc.js
package.json

Enable eslint on our ts and js files 
**This is still requires fixing lint errors in Incubator/WheelPicker**
Enable eslint on our ts and js files

enable eslint on both ts and js files

---

demo/src/screens/SettingsScreen.js

SettingsScreen - rename componentWillMount to UNSAFE
SettingsScreen - rename componentWillMount to UNSAFE

SettingsScreen - rename to UNSAFE

---

generatedTypes/components/textField/TextFieldMigrator.d.ts
src/components/textField/TextFieldMigrator.tsx

Set proper displayName on our TextFieldMigrator
Set proper displayName on our TextFieldMigrator

Fix/text field migrator/set display name

---

demo/src/screens/componentScreens/CardsScreen.tsx
demo/src/screens/componentScreens/PickerScreen.js
expoDemo/ios/Podfile.lock
expoDemo/package.json
generatedTypes/components/card/index.d.ts
generatedTypes/components/modal/index.d.ts
ios/rnuilib.xcodeproj/project.pbxproj
jest-setup.js
markdowns/getting-started/setup.md
package.json
src/components/card/index.tsx
src/components/modal/index.tsx
src/components/picker/PickerModal.js
src/components/picker/index.js
typings/components/Picker.d.ts
typings/components/Toast.d.ts

Remove Blur (and fix CardsScreen)
Remove Blur (and fix CardsScreen)

Remove Blur (and fix CardsScreen)

---

src/components/wizard/WizardStep.js

Wizard - add circleBackgroundColor
Wizard - add circleBackgroundColor
Related to: #1128

Wizard - add circleBackgroundColor

---

lib/components/Keyboard/KeyboardInput/CustomKeyboardView.android.js
lib/components/Keyboard/KeyboardInput/CustomKeyboardView.ios.js
lib/components/Keyboard/KeyboardInput/CustomKeyboardViewBase.js

CustomKeyboardView - remove unsafe methods (UNSAFE_componentWillReceiveProps)
CustomKeyboardView - remove unsafe methods

CustomKeyboardView - remove unsafe methods

---

src/components/tabController/TabBar.tsx

TabController.TabBar - fix items not being updated
TabController.TabBar - fix items not being updated

TabController.TabBar - fix items not being updated

---

generatedTypes/components/radioButton/RadioGroup.d.ts
generatedTypes/components/touchableOpacity/index.d.ts
src/components/radioButton/RadioGroup.tsx
src/components/touchableOpacity/index.tsx
typings/components/ColorPicker.d.ts

Fix issues related to TS issues found in other modules
Fix TS issues

Fix issues found in other modules

---

demo/src/screens/componentScreens/ExpandableSectionScreen.tsx

Fix broken UI for Galaxy S20 in expandableSection screen
Fix broken UI for Galaxy S20 in expandableSection screen

Fix/expandableSection screen UI

---

android/app/build.gradle
android/app/src/main/java/com/rnuilib/MainApplication.java
babel.config.js
package.json

Migrate our demo project to reanimatedv2
Migrate our demo project to reanimatedv2

Reanimated v2

---

src/incubator/WheelPicker/index.tsx

WheelPicker - fix typescript error in function sent to onLayout.
This is failing the build, please find another solution if it's wrong.
WheelPicker - fix typescript error in function sent to onLayout

WheelPicker - fix typescript error in function sent to onLayout

---

generatedTypes/index.d.ts

Export HapticService and HapticType in generatedTypes
Export HapticService and HapticType in generatedTypes

Infra/export haptic in generatedTypes

---

generatedTypes/incubator/index.d.ts
src/incubator/index.ts

Export Incubator.TextField typings
Export Incubator.TextField typings

Export Incubator.TextField typings

---

src/components/picker/PickerDialog.android.js
src/components/picker/PickerDialog.ios.js

Pass testID to native PickerDialogs
Fix - testID now passed to native PickerDialog

Fix/ Pass testID to native PickerDialog

---

src/components/hint/index.tsx

Hint - allow user to send zero to props (currently sending 0 will be ignored)
Hint - allow user to send zero to props

Hint - allow user to send zero to props

---

src/incubator/WheelPicker/index.tsx

Add testID to wheel picker list
Add testID to wheel picker list (`${testID}.list`)

Add testID to wheel picker list

---

src/components/slider/index.js

Fix slider's thumb position
Fix https://github.com/wix/react-native-ui-lib/issues/734
Fix slider's thumb position

Fix/ Slider's thumb position

---

src/components/picker/PickerModal.js
src/components/picker/index.js

PickerModal - support onShow
PickerModal - support onShow

PickerModal - support onShow

---

eslint-rules/lib/rules/prop-value-shape-deprecation.js
eslint-rules/package.json

Fix undefined length error in prop-value-shape rule
Fix undefined length error in prop-value-shape rule

Fix undefined length error in prop-value-shape rule

---

src/components/tabController/TabBar.tsx

TabController - TabBar - add scrollViewStyle
TabController - TabBar - add scrollViewStyle

TabController - TabBar - add scrollViewStyle

---

src/components/hint/index.tsx

Add `testID` support to `Hint` component container.
Add `testID` support to `Hint` component container.

Hint - support container test id

---

demo/src/screens/componentScreens/StepperScreen.js
src/components/stepper/index.js

Stepper - Adding 'step' props to control the increase and decrease level.
Stepper - Adding 'step' props to control the increase and decrease level (default = 1).

Stepper - Add step prop

---

generatedTypes/components/carousel/index.d.ts
generatedTypes/index.d.ts
src/components/carousel/index.tsx
src/index.ts

Export PageControlPosition
Export PageControlPosition

Feat/ Export PageControlPosition

---

README.md

Should help new users with the code examples. 
Readme.md code example syntax highlight.

docs(README): use proper syntax highlighting

---

demo/src/screens/ExampleScreenPresenter.js

ExampleScreenPresenter - fix typo
ExampleScreenPresenter - fix typo

ExampleScreenPresenter - fix typo

---

src/index.ts

Fix export of AvatarHelper in src/index.ts
Fix export AvatarHelper (which fix its typings)

Fix export of AvatarHelper in src/index.ts

---

src/incubator/WheelPicker/index.tsx

Add `onChange` to `onValueChange`'s dependency array
WOAUILIB-1919
Add `onChange` to `onValueChange`'s dependency array

Fix/ IncubatorWheelPicker onChange

---

src/components/picker/index.js
src/components/textField/index.js

Show the beginning of a long text in textField on Android
WOAUILIB-1892
Show the beginning of a long text in textField on Android

Feat/ show the beginning of a long text in textField on Android

---

src/components/picker/index.js

Fix alias usage in js file
Fix alias usage in js file

Fix alias usage in js file

---

src/components/picker/index.js

Pass prop selection of textField as object and not as boolean
Pass prop selection of textField as object and not as boolean

Fix/ selection TS

---

src/components/badge/index.tsx

Support passing custom accessibilityLabel to Badge
Support passing custom accessibilityLabel to Badge

Support passing custom accessibilityLabel to Badge

---

src/components/segmentedControl/index.tsx

Add RTL support to segmentedControl
(Tested on both iOS and Android)
Add RTL support to segmentedControl

Fix/ support RTL in segmentedControl

---

src/components/hint/index.tsx

Fix critical issue with Hint blocking touch events 
Fix critical issue with Hint blocking touch events

Initialize hintUnmounted state according the hint visibility

---

generatedTypes/components/hint/index.d.ts
src/components/hint/index.tsx

Hint - Fix exception when using targetFrame prop
Fix #1447
Hint - Fix exception when using targetFrame prop

Have a return fallback when using targetFrame for Hint component

---

eslint-rules/lib/utils/generalUtils.js
eslint-rules/package.json

Improve undefined checks to use _.get'
Improve undefined checks to use _.get

Improve undefined checks to use _.get

---

src/incubator/TextField/useFieldState.ts

Revalidate field when value programmatically changed (and validateOnChange is true)
Fix #1477
Revalidate field when value programmatically changed (and validateOnChange is true)

Revalidate field when value programmatically changed

---

generatedTypes/index.d.ts
generatedTypes/src/components/panningViews/panDismissibleView.d.ts
generatedTypes/src/components/panningViews/panListenerView.d.ts
generatedTypes/src/components/panningViews/panningProvider.d.ts
src/components/panningViews/panDismissibleView.tsx
src/components/panningViews/panListenerView.tsx
src/components/panningViews/panningProvider.tsx
src/index.ts

PanningProviderDirection - remove type.
PanningProviderDirection - remove type.

PanningProviderDirection - remove type

---

generatedTypes/src/components/avatar/index.d.ts
src/components/avatar/index.tsx

Avatar - revert 'imageSource' deletion.
Avatar - revert 'imageSource' deletion.

Avatar - revert 'imageSource' deletion

---

lib/components/SafeArea/SafeAreaSpacerView.tsx

Fix render condition for SafeAreaSpacerView
Fix #1532
Fix SafeAreaSpacerView error on Android (this native component is relevant only to iOS)

Fix render condition for SafeAreaSpacerView

---

markdowns/foundation/modifiers.md

doc: fixed links

---

demo/src/configurations.js
demo/src/index.js
demo/src/screens/index.js

Export our demo configurations as a function that can be called anywhere (specifically for our expo-snack demo)
Related to this issue #1556
Export our demo configurations as a function

Export loadDemoConfigurations for expo-snack app

---

lib/components/Keyboard/KeyboardInput/KeyboardAccessoryView.tsx

Fix issue with Expo doesnt recognize uilib native modules (keyboard)
Fix issue with Expo doesnt recognize uilib native modules (keyboard)

Fix issue with Expo doesnt recognize uilib native modules

---

generatedTypes/src/commons/modifiers.d.ts
src/components/progressBar/index.tsx

Fix ProgressBar's customElement style
Fix ProgressBar's customElement style

Fix/ ProgressBar customElement

---

generatedTypes/src/components/dialog/DialogDismissibleView.d.ts
generatedTypes/src/components/panningViews/panningProvider.d.ts
src/components/dialog/DialogDismissibleView.tsx
src/components/panningViews/panningProvider.tsx

Dialog and Panning - allow union type for direction
Dialog and Panning - allow union type for direction (typescript)

Dialog and Panning - allow union type for direction

---

README.md
generatedTypes/src/components/avatar/index.d.ts
generatedTypes/src/components/badge/index.d.ts
src/components/avatar/index.tsx
src/components/badge/index.tsx

Deprecate string badge size
WOAUILIB-2125
Deprecate string badge size

deprecate string badge size

---

src/components/maskedInput/maskedInput.api.json
src/components/modal/api/modal.api.json
src/components/modal/api/modalTopBar.api.json
src/components/overlay/overlay.api.json

Add docs for components m-o
Add docs for components m-o

Add docs for components m-o

---

src/components/sectionsWheelPicker/sectionsWheelPicker.api.json
src/components/segmentedControl/segmentedControl.api.json
src/components/skeletonView/skeletonView.api.json
src/components/slider/slider.api.json
src/components/stackAggregator/stackAggregator.api.json
src/components/stateScreen/stateScreen.api.json
src/components/stepper/stepper.api.json
src/components/switch/switch.api.json

Add docs for S components
Add docs for S components

Add docs for all S components

---

src/components/chipsInput/index.tsx

*Enter description to help the reviewer understand what's the change about...*
wrong url
*Add a quick message for our users about this change (include Compoennt name, relevant props and general purpose of the PR)*

update example pages docs

---

generatedTypes/src/components/skeletonView/index.d.ts
src/components/skeletonView/index.tsx

SkeletonView - support content visible on start
SkeletonView - support content visible on start

SkeletonView - support content visible on start

---

src/components/textField/index.js

TextField - fix placeholder memoization
TextField - fix placeholder memoization

TextField - fix placeholder memoization

---

src/incubator/WheelPicker/Item.tsx

Limit number of lines for WheelPicker items labels
Limit number of lines for WheelPicker items labels

Limit number of lines for WheelPicker items

---

generatedTypes/src/hooks/index.d.ts
generatedTypes/src/hooks/useCombinedRefs/index.d.ts
src/hooks/index.ts
src/hooks/useCombinedRefs/index.ts

Add a new hook for combining refs 
Add useCombineRefs - new hook for combining refs

Create new hook for combining refs

---

scripts/build-docs.js
src/components/hint/hint.api.json

Fix issue with displaying docs types special chars
Fix issue with displaying docs types special chars

Fix issue with displaying docs types special chars

---

src/incubator/ChipsInput/index.tsx

Fix chips input flicker issue after adding new chip by delaying the onChange event so the clear functionality will complete 
Fix chips input flicker issue after adding new chip

Fix chips input flicker issue after adding new chip

---

android/build.gradle

Update kotlin version to 1.6.0
Update kotlin version to 1.6.0

update kotlin version to 1.6.0

---

lib/android/src/main/java/com/wix/reactnativeuilib/keyboardinput/CustomKeyboardLayout.java

KeyboardInput - fix NPE in CustomKeyboardLayout
KeyboardInput - fix NPE in CustomKeyboardLayout

KeyboardInput - fix NPE in CustomKeyboardLayout

---

.buildkite/pipeline.yml

Builds have no default timeout so they can hang forever. this should limit build to 15 min
Add timeout to the build

Set timeout

---

docs/getting-started/setup.md

Mention starter kits in our docs
Add links to various RNUILib starter kits in our docs

Mention starter kits in our docs

---

src/index.js

Export TextFieldMigrator to initiate migration
Start TextField migration into new implementation (Incubator.TextField)

Export TextFieldMigrator to initiate migration

---

generatedTypes/src/incubator/TextField/Label.d.ts
src/incubator/TextField/Label.tsx
src/incubator/TextField/index.tsx

Pass testID for internal label component to be able to test in UT.
Add testID to TextField label component.

TextField - pass testID to internal Label component

---

src/components/hint/index.tsx

Limit hint width to screenWidth 
WOAUILIB-2374
Fix Hint max width

Fix/ Hint max width

---

src/components/avatar/index.tsx

**This will fail private snapshots, only merge after looking at the appropriate private PR**
Avatar - add container testID.
Avatar - add container testID

Avatar - add container testID

---

generatedTypes/src/components/button/index.d.ts
generatedTypes/src/style/colors.d.ts
src/style/colors.ts

Add designTokens to Colors type
Add designTokens to Colors type

Fix/ add designTokens to Colors type

---

demo/src/screens/componentScreens/SliderScreen.tsx
generatedTypes/src/components/slider/GradientSlider.d.ts
generatedTypes/src/components/slider/index.d.ts
src/components/slider/index.tsx
src/components/slider/slider.api.json

Add RTL support to Slider component
Add `disableRTL` prop to keep the slider LTR even if the app is in RTL mode.
Add RTL support to Slider component

Feat/ Slider RTL

---

ios/rnuilib.xcodeproj/project.pbxproj
package.json

Upgrade gesture-handler to v2
Upgrade gesture-handler to v2

Upgrade gesture-handler to v2

---

src/index.js
src/index.ts

Remove testkite exports
Remove testkite exports

Remove testKits exports

---

demo/src/screens/componentScreens/PickerScreen.js
src/components/picker/index.js
src/components/textField/TextFieldMigrator.tsx

Initiate TextField migration in Picker component
Initiate TextField migration in Picker component by passing `migrateTextField` prop

Initiate TextField migration in Picker component

---

src/incubator/TextField/useFieldState.ts
src/incubator/TextField/useImperativeInputHandle.ts

On demand validation for migrated TextField
Return TextField's validation result when calling it imperatively (using ref)

Allow on demand validation for migrated TextField

---

docuilib/docusaurus.config.js
scripts/build-docs.js
src/components/textField/textField.api.json
src/components/toast/toast.api.json

Add directing pages for unmaintained components, specifically TextField and Toast
Direct to our new implementation for TextField and Toast in the docs

Add directing pages for unmaintained components

---

src/components/avatar/index.tsx

Avatar - fix border radius (Android)
This can be seen in the private lib's demo screen.
Avatar - fix border radius (Android)

Avatar - fix border radius (Android)

---

package.json

Upgrade reanimated to 2.4.1 (for private tests)
Upgrade reanimated to 2.4.1

Upgrade reanimated to 2.4.1

---

src/style/designTokens.ts

Design tokens - fix backgroundWarning
Design tokens - fix backgroundWarning

Design tokens - fix backgroundWarning

---

demo/src/screens/SettingsScreen.js
demo/src/screens/componentScreens/GridViewScreen.tsx
demo/src/screens/componentScreens/TabControllerScreen/index.tsx
demo/src/screens/incubatorScreens/IncubatorChipsInputScreen.tsx
expoDemo/MainScreen.tsx
package.json
scripts/build-docs.js
scripts/prRelesaeNotes.js
src/.babelrc.json
src/assets/Assets.ts
src/commons/modifiers.ts
src/components/gridView/index.tsx
src/components/picker/index.js
src/helpers/AvatarHelper.ts
src/style/spacings.ts
src/style/typography.ts
uilib-docs/configurations/pageCreators/createComponentPages.js

Reverts wix/react-native-ui-lib#1825
Revert the revert of lodash babel plugin
Remove the plugin code
Revert the revert of lodash babel plugin

Revert "Revert "Infra/lodash babel plugin (#1815)""

---

generatedTypes/src/incubator/TextField/usePreset.d.ts
src/incubator/TextField/textField.api.json
src/incubator/TextField/usePreset.ts

Support overriding TextField preset's default fieldStyle
Support overriding TextField preset's default fieldStyle

Support overriding TextField preset's fieldStyle

---

generatedTypes/src/components/image/index.d.ts
src/components/card/CardImage.tsx
src/components/image/image.api.json
src/components/image/index.tsx

Support imageId in Image, and fix props passing in Card.Image
Support imageId in Image component, and fix props passing in Card.Image

Support imageId in Image, and fix props passing in Card.Image

---

src/.babelrc.json

Add lodash plugin to reduce bundle size 
Checked on private with version `6.10.0-snapshot.654`
Add lodash plugin to reduce bundle size

Infra/ add lodash plugin

---

generatedTypes/src/incubator/TextField/usePreset.d.ts
generatedTypes/src/style/colors.d.ts
generatedTypes/src/style/designTokens.d.ts
generatedTypes/src/style/designTokensDM.d.ts
src/style/designTokens.ts
src/style/designTokensDM.ts

Add DarkElevated and DarkActive
Add DarkElevated and DarkActive

Add DarkElevated and DarkActive

---

src/components/fadedScrollView/index.tsx

Fix ref of FadedScrollView component
WOAUILIB-2544
Fix ref of FadedScrollView component

Fix ref of FadedScrollView component

---

src/components/switch/index.tsx

Move Switch component to design tokens
Move Switch component to design tokens

Infra/ move switch to design tokens

---

generatedTypes/src/incubator/toast/helpers/useToastPresets.d.ts
src/incubator/toast/helpers/useToastPresets.ts
src/incubator/toast/index.tsx

Move Incubator.Toast to design tokens
WOAUILIB-2495
Move Incubator.Toast to design tokens

Infra/ move Incubator.Toast to design tokens

---

demo/src/screens/nativeComponentScreens/keyboardInput/KeyboardInputViewScreen.js
generatedTypes/lib/components/Keyboard/KeyboardInput/KeyboardAccessoryView.d.ts
generatedTypes/lib/components/Keyboard/KeyboardTracking/KeyboardTrackingView/index.d.ts
generatedTypes/lib/components/Keyboard/index.d.ts
lib/components/Keyboard/KeyboardInput/KeyboardAccessoryView.tsx
lib/components/Keyboard/KeyboardTracking/KeyboardTrackingView/index.tsx
lib/ios/reactnativeuilib/keyboardtrackingview/KeyboardTrackingViewTempManager.m
lib/package.json

KeyboardAccessoryView - adding 'usesBottomTabs' prop to add bottom insets.
KeyboardAccessoryView - adding 'usesBottomTabs' prop to add bottom insets.

KeyboardAccessoryView - adding 'usesBottomTabs' prop

---

src/components/slider/index.tsx

Slider - adjust the thumb position more smoothly
If you pull the thumb really carefully you can see small "jumps" near the start and end of the slide area.
This can be seen in WOAUILIB-2518
Slider - adjust the thumb position more smoothly

Slider - adjust the thumb position more smoothly

---

src/components/checkbox/checkbox.api.json
src/components/chip/chip.api.json
src/components/colorPalette/ColorPalette.api.json
src/components/listItem/listItem.api.json
src/components/modal/api/modal.api.json
src/components/picker/api/picker.api.json
src/components/radioGroup/radioGroup.api.json
src/components/stackAggregator/stackAggregator.api.json
src/components/switch/switch.api.json
src/components/touchableOpacity/touchableOpacity.api.json
src/components/wizard/wizard.api.json
src/incubator/TextField/textField.api.json
src/incubator/WheelPicker/wheelPicker.api.json
src/incubator/toast/toast.api.json

There were some issues with some component example snippets, related to quotation('). This PR solves those issues. 
*Fixed some example code snippets*

Fix some example snippets

---

src/style/__tests__/colors.spec.js
src/style/colors.ts

Update palette generation for bright colors
WOAUILIB-1964
Update palette generation for bright colors

Feat/ update palette generation for bright colors

---

generatedTypes/src/components/icon/index.d.ts
src/components/icon/index.tsx

Fix Icon tintColor type
WOAUILIB-2574
Fix Icon tintColor type

Fix/ Icon tintColor type

---

src/style/colors.ts

Dark mode - restrict for dev only until releasing full support
Dark mode - restrict for dev only until releasing full support

Dark mode - restrict for dev only until releasing full support

---

src/components/picker/index.js
src/incubator/expandableOverlay/index.tsx

Picker (and ExpandableOverlay) - support onPress
WOAUILIB-2531
Picker (and ExpandableOverlay) - support onPress

Picker - support onPress

---

src/components/picker/helpers/usePickerSelection.tsx

Picker - forget search on cancel
Fixes #1880
Fix #1880 - Picker - forget search on cancel

Picker - forget search on cancel

---

demo/src/screens/componentScreens/RadioButtonScreen.js
src/components/radioButton/index.tsx

RadioButton - to design tokens
RadioButton - to design tokens

RadioButton - to design tokens

---

generatedTypes/src/commons/modifiers.d.ts
generatedTypes/src/style/colors.d.ts
generatedTypes/src/style/designTokens.d.ts
generatedTypes/src/style/designTokensDM.d.ts
generatedTypes/src/style/index.d.ts
src/commons/modifiers.ts
src/style/colors.ts
src/style/designTokens.ts
src/style/designTokensDM.ts
src/style/index.ts

export DesignTokens and DesignTokensDM
export DesignTokens and DesignTokensDM

Infra/ export DesignTokens and DesignTokensDM

---

src/components/tabController/TabBar.tsx
src/components/tabController/TabBarItem.tsx

TabController - Fix how we handle dynamic tab bar items
TabController - Fix how we handle dynamic tab bar items

Fix how we handle dynamic tab bar items

---

src/style/designTokens.ts
src/style/designTokensDM.ts

DesignTokens - new keys.
DesignTokens - new keys.

DesignTokens - new keys

---

src/components/picker/PickerItemsList.tsx

Fix scrolling long lists in Picker
Fix scrolling long lists in Picker

Fix/ picker with long lists

---

demo/src/screens/incubatorScreens/IncubatorChipsInputScreen.tsx

Migrate Incubator ChipsList screen to design tokens
Migrate Incubator ChipsList screen to design tokens

Infra/ migrate Incubator ChipsList screen to design tokens

---

demo/src/screens/componentScreens/SliderScreen.tsx
demo/src/screens/componentScreens/StepperScreen.tsx
src/components/slider/ColorSliderGroup.tsx
src/components/slider/GradientSlider.tsx
src/components/slider/index.tsx
src/components/stepper/index.tsx

Migrate Slider and Stepper to design tokens
Migrate Slider and Stepper to design tokens

Infra/ migrate Slider and Stepper to design tokens

---

src/style/dividers.ts

Dividers - move to design tokens
Dividers - move to design tokens

Dividers - move to design tokens

---

demo/src/screens/componentScreens/ProgressBarScreen.tsx
src/components/progressBar/index.tsx

ProgressBar - move to design tokens
ProgressBar - move to design tokens

ProgressBar - move to design tokens

---

src/style/designTokens.ts
src/style/designTokensDM.ts

Update divider and icon tokens
Update divider and icon tokens

infra/ update divider and icon tokens

---

src/commons/Config.ts
src/style/__tests__/scheme.spec.js
src/style/colors.ts
src/style/scheme.ts

Add appScheme to config
Add appScheme to config

Infra/ add appScheme to config

---

src/incubator/toast/index.tsx
src/incubator/toast/types.ts

Support passing custom loaderElement to Toast component
This is so we can inject our own loader in private
Support passing custom loaderElement to Toast component

Support passing custom loaderElement to Toast component

---

src/components/skeletonView/index.tsx

Fix margin modifiers for the basic skeleton
Fix margin modifiers for the basic skeleton

Fix/ margin modifiers for skeleton

---

lib/components/Keyboard/KeyboardTracking/keyboardAwareInsetsView.api.json
src/components/actionBar/actionBar.api.json
src/components/actionSheet/actionSheet.api.json
src/components/animatedImage/animatedImage.api.json
src/components/avatar/avatar.api.json
src/components/badge/badge.api.json
src/components/button/button.api.json
src/components/card/card.api.json
src/components/card/cardImage.api.json
src/components/card/cardSection.api.json
src/components/checkbox/checkbox.api.json
src/components/chipsInput/chipsInput.api.json
src/components/dateTimePicker/dateTimePicker.api.json

Removing "extendsLink" to uilib's components
Docs - Removing "extendsLink" to uilib's components

Removing "extendsLink" to uilib's components

---

docuilib/sidebars.js
lib/components/Keyboard/KeyboardTracking/keyboardAwareInsetsView.api.json
scripts/buildDocs.js

Fix keyboard docs
Fix keyboard docs

Fix keyboard docs

---

demo/src/screens/incubatorScreens/IncubatorTextFieldScreen.tsx
src/incubator/TextField/index.tsx

Fix issue with centering TextField component
Fix issue with centering TextField component

Fix issue with centering TextField component

---

src/components/picker/helpers/usePickerSelection.tsx
src/components/picker/new.tsx

Picker - multi select - fix behavior when the value is changed by user
Fixes #2005
Picker - multi select - fix behavior when the value is changed by user

Picker - multi select - fix behavior when the value is changed by user

---

demo/src/screens/componentScreens/BadgesScreen.tsx

Design Tokens - Badge
WOAUILIB-2724
Design Tokens - Badge

Design Tokens - Badge

---

src/components/segmentedControl/index.tsx

SegmentedControl - handle onLayout being called twice
SegmentedControl - handle onLayout being called twice

SegmentedControl - handle onLayout being called twice

---

src/style/designTokens.ts
src/style/designTokensDM.ts

Update tokens by the guidelines:
* $backgorundElevated in DM - grey1
* new $textSuccessLight - green30
* new $textSuccessLight DM - green40
Update tokens by the guidelines

Infra/ update and add tokens

---

src/components/avatar/index.tsx

Avatar - allow the override of testID in Badge
Avatar - allow the override of testID in Badge

Avatar - allow the override of testID in Badge

---

demo/src/screens/componentScreens/ButtonsScreen.tsx
src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/button/index.tsx

Update icon button color - design tokens 
Update icon button color - design tokens

Infra/ update icon button color - design tokens 

---

scripts/prReleaseNotes.js

prReleaseNotes script - remove jira issue (not relevant to public prs)
prReleaseNotes script - remove jira issue.

prReleaseNotes script - remove jira issue (not relevant to public prs)

---

src/components/dateTimePicker/index.tsx

Fix onChange type of DateTimePicker
Fix onChange type of DateTimePicker

Fix onChange type of DateTimePicker

---

src/components/modal/TopBar.tsx
src/components/modal/index.tsx
src/components/picker/PickerItemsList.tsx

Fix Modal backgroundColor
Fix Modal backgroundColor

Fix/ modal bg color

---

src/components/carousel/index.tsx

Carousel - fix initial page
WOAUILIB-2776
Carousel - fix initial page

Carousel - fix initial page

---

demo/src/screens/componentScreens/DialogScreen.js
src/components/dialog/index.tsx

Dialog (old) - add static directions
This is to allow the deprecation of `PanningProvider`
Dialog (old) - add static directions

Dialog (old) - add static directions

---

src/components/dialog/index.tsx
src/index.ts

Dialog (old) - add export for DialogDirections
Dialog (old) - add export for DialogDirections

Dialog (old) - add export for DialogDirections

---

src/components/picker/PickerItem.tsx
src/components/picker/types.tsx

Picker.Item - expose `isItemDisabled` (for `selectionLimit` in multi)
WOAUILIB-2758
Picker.Item - expose `isItemDisabled` (for `selectionLimit` in multi)

Picker.Item - expose isItemDisabled

---

src/index.ts

KeyboardAwareScrollView - fix exports
KeyboardAwareScrollView - fix exports

KeyboardAwareScrollView - fix exports

---

src/components/expandableSection/index.tsx

ExpandableSection - add expanded to the accessibilityState
Fixes #2053 
ExpandableSection - add expanded to the accessibilityState

ExpandableSection - add expanded to the accessibilityState

---

src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/text/index.tsx

Set default color for Text component to be $textDefault (instead of passing in each usage)
Set default color for Text component to be $textDefault

Set default color for Text component

---

src/incubator/WheelPicker/index.tsx

Fix Incubator.WheelPicker alignments - WOAUILIB-2768
Fix Incubator.WheelPicker alignments

Fix/ Incubator.WheelPicker alignments

---

src/style/colors.ts

colorStringValue - support null
colorStringValue - support null

colorStringValue - support null

---

src/style/colorsPalette.ts
src/style/designTokensDM.ts

Update some dark tokens
WOAUILIB-2794
Design Tokens - update colors

Infra/ update dark tokens

---

eslint-rules/tests/component_prop_deprecation.json
eslint-rules/tests/lib/rules/component-prop-deprecation.js
lib/components/Keyboard/KeyboardInput/KeyboardAccessoryView.tsx

formatting
component deprecation json formatting

json formattings

---

package.json
src/components/drawer/index.tsx
src/components/sortableGridList/SortableItem.tsx
src/components/sortableList/SortableListItem.tsx
src/components/tabController/TabBarItem.tsx
src/incubator/panView/index.tsx

react-native-gesture-handler to 2.5.0
react-native-gesture-handler to 2.5.0

react-native-gesture-handler to 2.5.0

---

demo/src/screens/componentScreens/ColorSwatchScreen.tsx
src/components/colorSwatch/index.tsx

ColorSwatch - fix - icon tint color should not change in DM
ColorSwatch - fix - icon tint color should not change in DM

ColorSwatch - fix - icon tint color should not change in DM

---

src/components/picker/index.tsx
src/incubator/TextField/types.ts

Fix minor issues in Picker fieldType
- Fix issue with Label style when using "filter" type
- Support overriding trailingAccessory when using fieldType
WOAUILIB-2878
Fix minor issues with Picker's fieldType - support changing label style for "filter" type and override trailingAccessory

Fix minor issues with Picker fieldType

---

src/components/hint/index.tsx

Fix Hint tokens
WOAUILIB-2816
Hint - Fix tokens

Fix/ Hint tokens

---

src/components/image/index.tsx
src/components/text/index.tsx
src/components/touchableOpacity/index.tsx

Pass modifiersOptions to atom components (Text, Image, TouachableOpacity)
Pass modifiersOptions to atom components (Text, Image, TouachableOpacity) to optimize performance

Optimize atom components by passing modifiersOptions

---

lib/android/src/main/java/com/wix/reactnativeuilib/keyboardinput/utils/RuntimeUtils.java

This should fix the issue https://github.com/wix/react-native-ui-lib/issues/2147
I will create a patch from this commit to release a new update to our production app to check whether the crash still occurs or not.
*Add a quick message for our users about this change (include Compoennt name, relevant props and general purpose of the PR)*

Fix crash AssertNotNull

---

src/commons/asBaseComponent.tsx

Apply ThemeManager ThemeContext in asBaseComponent
Apply ThemeManager ThemeContext in asBaseComponent

Apply ThemeManager ThemeContext in asBaseComponent

---

src/components/touchableOpacity/index.tsx

Add bg modifiers to touchable opacity
Add bg modifiers to touchable opacity

Fix/ add bg modifiers to touchable opacity

---

src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/button/index.tsx

I made some improvements to our Button component:
1. Passing `modifiersOptions` to `asBaseComponent`
2. Memoizing all the functions that are called in a prop value. 
All the changes look Kosher to me, but please give a second eye on them. 
Button perf improvements

Infra/ Button perf improvements 

---

src/components/icon/index.tsx

Ignore modifiers that not relevant to icon
Improve Icon perf - Ignore modifiers that not relevant to icon

Ignore modifiers that not relevant to icon

---

src/components/stepper/index.tsx

Stepper support for useCustomTheme added.
Stepper support for useCustomTheme.

Fix Stepper theme

---

.npmignore

npmignore - add docs eslint and tests
npmignore - add docs eslint and tests

npmignore - add docs eslint and tests

---

src/style/colorsPalette.ts
src/style/designTokensDM.ts

Update dark mode colors and tokens
WOAUILIB-2886
WOAUILIB-2888
Update dark mode colors and tokens

update dark mode colors

---

src/components/timeline/timeline.api.json

fix Timeline component's example link
fix Timeline component's example link

fix `Timeline` component's example link.

---

src/components/sortableGridList/usePresenter.ts

SortableGridList - add RTL support
WOAUILIB-2983
SortableGridList - add RTL support

SortableGridList - add RTL support

---

src/components/drawer/index.tsx

Drawer - delay actions render to reduce component loading time 
WOAUILIB-2927
Drawer - delay actions render to reduce component loading time

Perf/ Drawer - delay actions render

---

demo/src/screens/MainScreen.js

Fixed demo app dark mode
Fixed demo app dark mode

Fixed demo app dark mode, changed to design tokens

---

demo/src/screens/MainScreen.js

Fixed search functionality, search logo appearance
Fixed search functionality, search logo appearance

Fixed search functionality, search logo appearance

---

src/incubator/ChipsInput/index.tsx

ChipsInput - handle backspace with no chips
ChipsInput - handle backspace with no chips

ChipsInput - handle backspace with no chips

---

src/incubator/WheelPicker/index.tsx

* Added listKey prop to WheelPicker flatlist, so that it can be rendered inside parent flatlist
* Added listKey prop to FlatList of `WheelPicker` component

Added listKey prop to flat list of wheel picker

---

src/hooks/useThemeProps/index.ts

Fixes the issue with `View` and toggling appearance - #2127 
- added `useColorScheme()` hook to trigger a change when toggling appearance.

Fix: View mode toggle

---

src/components/modal/TopBar.tsx

Modal.TopBar - add key to buttons
This fixes `Each child in a list should have a unique "key" prop` in some cases
Modal.TopBar - add key to buttons

Modal.TopBar - add key to buttons

---

scripts/buildDocs.js

Docs support multiple example screens
None

Docs support multiple example screens

---

demo/src/screens/__tests__/__snapshots__/AvatarScreen.spec.js.snap
src/components/badge/index.tsx

Badge - update default background color
WOAUILIB-3050
Badge - update default background color

Fix/ update badge bg color

---

src/components/drawer/Swipeable.tsx

Drawer - increase threshold
WOAUILIB-3016
Drawer - increase threshold

Drawer - increase threshold

---

src/commons/new.ts
src/components/text/index.tsx

Checkbox labelProps support FlexModifires
Checkbox labelProps support FlexModifires

Checkbox labelProps added flex modifires to TextProps

---

src/components/textArea/index.js

TextArea - use Design Tokens to support dark mode
TextArea - use Design Tokens to support dark mode

Fix/ TextArea to Design Tokens

---

demo/src/screens/incubatorScreens/IncubatorExpandableOverlayScreen.tsx
src/components/modal/index.tsx

Modal - set default backgroundColor
Modal - set default backgroundColor

Fix/ set default backgroundColor for Modal

---

src/components/expandableSection/index.tsx

ExpandableSection require cycle fix
ExpandableSection require cycle fix

require cycle fix

---

src/incubator/Dialog/index.tsx
src/incubator/Dialog/useAnimatedTransition.ts
src/incubator/hooks/useHiddenLocation.ts

Incubator.Dialog - fix hiding when layout changes
Incubator.Dialog - fix hiding when layout changes

Incubator.Dialog - fix hiding

---

src/incubator/Dialog/DialogHeader.tsx
src/incubator/Dialog/dialogHeader.api.json
src/incubator/Dialog/types.ts

Incubator.Dialog - remove header's renderContent
Incubator.Dialog - remove header's renderContent

Incubator.Dialog - remove header's renderContent

---

src/incubator/Dialog/useAnimatedTransition.ts

Incubator.Dialog - fix flickering because of initial measuring + fix exit animation 
None

Incubator.Dialog - another fix for hiding

---

src/style/designTokens.ts
src/style/designTokensDM.ts

Add $backgroundElevatedLight token 
WOAUILIB-3141
Add $backgroundElevatedLight token

Infra/ add $backgroundElevatedLight token

---

src/components/scrollBar/index.tsx

ScrollBar - fix default gradientColor
ScrollBar - fix default gradientColor

Fix/ ScrollBar gradientColor

---

src/components/dash/index.tsx
src/components/index.js
src/components/timeline/Line.tsx
src/index.ts

Dash - exporting Dash as a new component
Dash - new component for drawing dashed line

Dash - exporting Dash as a new component

---

src/components/image/index.tsx
src/components/picker/PickerItem.tsx
src/components/picker/PickerPresenter.ts
src/components/picker/types.tsx

Fixing some new random TS errors. 
Not sure why they started suddenly, might be related to dependencies of `@types/xxx` packages. 
Fixing some new random TS errors.

Fix random TS errors

---

src/incubator/toast/index.tsx

Added display name to Toast component to use config file in private.
Added display name to Toast component to use config file in private.

Added display name to Toast component to use config file in private

---

package.json

Bump react-native-navigation to 7.30.0
Bump react-native-navigation to 7.30.0

Bump react-native-navigation to 7.30.0

---

android/build.gradle

Fix Android build - add exclusiveContent
Fix Android build - add exclusiveContent

Fix Android build - add exclusiveContent

---

src/incubator/Dialog/index.tsx
src/incubator/index.ts

IncubatorDialog - add imperative handle with dismiss
IncubatorDialog - add imperative handle with dismiss

IncubatorDialog - add imperative handle with dismiss

---

src/style/themeManager.ts

ThemeManager - add Theme type
ThemeManager - add Theme type

ThemeManager - add Theme type

---

src/incubator/Dialog/index.tsx

Incubator.Dialog - hoist static methods (fix statics not working)
Incubator.Dialog - hoist static methods (fix statics not working)

Incubator.Dialog - hoist static methods

---

src/incubator/Dialog/index.tsx
src/incubator/Dialog/useAnimatedTransition.ts

Incubator.Dialog - not opening correctly
WOAUILIB-3230
Incubator.Dialog - not opening correctly

Incubator.Dialog - not opening correctly

---

package.json

Blur - upgrade to 4.3.0
Blur - upgrade to 4.3.0

Blur - upgrade to 4.3.0

---

src/incubator/toast/index.tsx

Toast - update background color 
WOAUILIB-3200
Toast - update background color

Fix/ Toast bg color

---

src/components/sortableGridList/sortableGridList.api.json
src/components/sortableList/SortableList.api.json

SortableList and SortableGridList - improve `data` docs to reflect that it should not be changed on each order change
WOAUILIB-3120
SortableList and SortableGridList - improve `data` docs

SortableList and SortableGridList - improve data docs

---

package.json

Upgrade reanimated from 2.8 to 2.13
Upgrade reanimated from 2.8 to 2.13 in our demo app

Upgrade reanimated from 2.8 to 2.13

---

package.json
src/style/typography.ts

Use wix fork for `react-native-text-size`.
Use wix fork for `react-native-text-size`

Use wix fork for `react-native-text-size`

---

package.json
src/style/typography.ts

reverting the use of wix-react-native-text-size fork
reverting the use of wix-react-native-text-size fork

reverting the use of wix-react-native-text-size fork

---

src/incubator/Dialog/dialogHeader.api.json
src/incubator/Dialog/types.ts

DialogHeader - add code snippet
DialogHeader - add code snippet

DialogHeader - add code snippet

---

src/commons/Constants.ts
src/incubator/TextField/FloatingPlaceholder.tsx
src/incubator/TextField/Input.tsx

Fix Incubator.TextField for react-native-web - make it pressable + remove extra outline
WOAUILIB-3243
Fix Incubator.TextField for react-native-web

Fix/ TextField for react-native-web

---

src/components/dash/index.tsx

Adding testID to Dash component.
- Dash: adding testID prop

Adding testID to Dash

---

react-native.config.js

*Fixes Invariant Violation KeyboardTrackingissue #2204 ViewTemp  *
*Add a quick message for our users about this change (include Component name, relevant props and general purpose of the PR)*

fix: fixes Invariant Violation KeyboardTrackingViewTemp 

---

src/commons/Config.ts
src/optionalDependencies/AsyncStoragePackage.ts
src/optionalDependencies/index.ts

Add `setLocalScheme` method to our Config class to support using the scheme from the local storage.
Add `setLocalScheme` method to our Config class to support using the scheme from the local storage.

setLocalScheme

---

src/commons/Config.ts

Add getLocalScheme getter to our Config
Add getLocalScheme getter to our Config

Infra/ add getLocalScheme getter

---

demo/src/screens/incubatorScreens/IncubatorTextFieldScreen.tsx
src/incubator/TextField/index.tsx
src/incubator/TextField/textField.api.json
src/incubator/TextField/types.ts

Add inline prop to TextField to allow proper alignment for TextField that rendered inside a row container
Add inline prop to TextField to allow proper alignment for TextField that rendered inside a row container

Add inline prop to TextField

---

demo/src/screens/__tests__/__snapshots__/AvatarScreen.spec.js.snap
demo/src/screens/componentScreens/BadgesScreen.tsx
src/components/badge/index.tsx

Fix badge colors and example screen
Fix badge colors and example screen

Fix badge colors and example screen

---

src/components/switch/index.tsx

Switch - change thumb color to $iconDefaultLight
Switch - change thumb color

Use token for Switch thumb

---

demo/src/screens/__tests__/__snapshots__/AvatarScreen.spec.js.snap
src/components/avatar/index.tsx

Avatar - fix Badge color
Avatar - fix Badge color

Fix avatar badge color

---

demo/src/screens/__tests__/__snapshots__/AvatarScreen.spec.js.snap
src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/image/index.tsx

Image - fix width and height support bug
Image - fix width and height support bug

Image - fix width and height support bug

---

src/incubator/TextField/useFieldState.ts

*Enter description to help the reviewer understand what's the change about...*
*Add a quick message for our users about this change (include Component name, relevant props and general purpose of the PR)*

revert the condition adding

---

src/incubator/WheelPicker/index.tsx

Incubator.WheelPicker - allow sending FlatListProps
Relates to WOAUILIB-3314
Incubator.WheelPicker - allow sending FlatListProps

Incubator.WheelPicker - allow sending FlatListProps

---

src/incubator/TextField/useFieldState.ts

fix: text field on change when providing default value
fix: text field on change when providing default value

fix: text field on change when providing default value

---

src/incubator/TextField/index.tsx

TextField - fix value override https://github.com/wix/react-native-ui-lib/pull/2388
WOAUILIB-3377
TextField - fix value override

fix value override

---

src/incubator/TextField/useFieldState.ts

Fix TextField defaultValue condition
Fix TextField defaultValue condition

Fix/ TextField defaultValue condition

---

src/incubator/Dialog/dialog.api.json

Incubator.Dialog - add note to API about lists
Incubator.Dialog - add note to API about lists

Incubator.Dialog - add note to API about lists

---

src/incubator/toast/index.tsx

Toast - update the action design
WOAUILIB-3332
Toast - update the action design

update Toast action design

---

ReactNativeUiLib.podspec

podspec should point to lib
Fixes #2204
Fix podspec

podspec should point to lib

---

demo/src/screens/componentScreens/ColorSwatchScreen.tsx
src/components/colorSwatch/colorSwatch.api.json
src/components/colorSwatch/index.tsx

ColorSwatch new unavailable mode.
ColorSwatch new unavailable mode.

ColorSwatch new unavailable mode

---

package.json

react-native-linear-gradient version upgrade to 2.6.2.
react-native-linear-gradient version upgrade to 2.6.2.

react-native-linear-gradient version upgrade to 2.6.2

---

scripts/buildPackages.js

Add a package for our Constants 
WOAUILIB-3323
Add a package for our Constants

Infra/ build constants package

---

src/style/colors.ts

Colors - fix getTintColor - get key from a single digit (ex. green1, green5)
Colors - fix getTintColor - get key from a single digit (ex. green1, green5)

Colors - getTintColor - get key from a single digit (ex. green1, green5)

---

src/components/picker/PickerItemsList.tsx

Pass Picker's `listProp` to wheelPicker 
WOAUILIB-2134
Pass Picker's `listProp` to wheelPicker

pass listProps to wheelPicker

---

src/incubator/Calendar/Agenda.tsx
src/incubator/Calendar/index.tsx
src/optionalDependencies/FlashListPackage.ts
src/optionalDependencies/index.ts

Add FlashList to optional dependencies
Use FlashListPackage in Incubator.Calendar component
Add FlashList to optional dependencies

Add FlashList to optional dependencies

---

src/components/animatedScanner/animatedScanner.api.json
src/components/animatedScanner/index.js

Added a testID to `AnimatedScanner` to allow easier testing
AnimatedScanner - new `testID` prop - added `testID` prop to use for testing the component

Tests/Add testID to AnimatedScanner

---

demo/src/screens/foundationScreens/ShadowsScreen.js
src/style/shadows.ts

Shadows - deprecate dark presets in favor of the grey presets.
Please review by commits
Shadows - the dark presets are deprecated, please use the grey presets instead.

V7 dark shadows

---

src/components/picker/PickerItem.tsx
src/components/picker/api/pickerItem.api.json

Picker.Item - add onPress support
WOAUILIB-3417
Picker.Item - add onPress support

PickerItem - add onPress support

---

docs/foundation/colors.md

Fixed small typo in the documentation page for Colors.
docs: update typo in Colors page

docs: fixed typo in colors.md

---

demo/src/screens/componentScreens/TextFieldScreen.tsx
src/incubator/TextField/index.tsx
src/incubator/TextField/types.ts
src/incubator/index.ts
src/index.ts

Expose a TextFieldRef type that users can use for a ref they pass to TextField
Expose a TextFieldRef type that users can use for a ref they pass to TextField

Expose TextFieldRef type

---

demo/src/screens/componentScreens/HintsScreen.tsx
demo/src/screens/incubatorScreens/PanViewScreen.tsx
src/components/dialog/index.tsx
src/incubator/Dialog/index.tsx

Adjust default overlayBackgroundColor to `Colors.rgba(Colors.black, 0.5)`
WOAUILIB-3448
Adjust default overlayBackgroundColor to `Colors.rgba(Colors.black, 0.5)`

Adjust overlayBackgroundColor

---

src/incubator/TextField/index.tsx
src/incubator/index.ts
src/index.ts

export TextFieldValidator type
export TextFieldValidator type

export TextFieldValidator type

---

demo/src/screens/__tests__/__snapshots__/AvatarScreen.spec.js.snap
src/components/avatar/index.tsx
src/helpers/AvatarHelper.ts
src/helpers/__tests__/AvatarHelper.spec.js

Fix Avatar label sizes
WOAUILIB-3468
Fix Avatar label sizes

Fix/ avatar label sizes

---

GestureDetectorMock.tsx
jest-setup.js
src/incubator/Dialog/__tests__/index.spec.tsx

There is some awkward code in this PR, but after talking with Niryo, this is what we're doing in the private mocks.
None

Incubator.Dialog - fix test (add mocks)

---

demo/src/screens/componentScreens/HintsScreen.tsx
demo/src/screens/incubatorScreens/PanViewScreen.tsx
src/components/dialog/index.tsx
src/incubator/Dialog/index.tsx

Adjust default overlayBackgroundColor to `Colors.rgba(Colors.backgroundInverted, 0.3)`
WOAUILIB-3448
Adjust default overlayBackgroundColor to `Colors.rgba(Colors.backgroundInverted, 0.3)`

Dimming Overlay - background change

---

src/incubator/index.ts

ReExport calendars component in Incubator
N/A

ReExport calendars component in Incubator

---

src/components/hint/index.tsx

Hint - fix anchor position for x = 0
(ticket 3428)
Hint - fix anchor position for x = 0

Hint - fix anchor position for x = 0

---

src/optionalDependencies/index.web.ts

FlashList optional dependency added to `optional dependency` web file.
Export FlashList dependency for the web.

FlashList optional dependency

---

src/incubator/Calendar/Agenda.tsx
src/incubator/Calendar/index.tsx

Changed the FlashList require syntax according to the WebEditor ts errors.
Changed the FlashList require syntax.

Changed the FlashList using syntax according to the WebEditor errors

---

src/incubator/TextField/CharCounter.tsx

CharCounter fix to count emojis, counting 16-bit code symbols.
CharCounter fix to count emojis, counting 16-bit code symbols.

CharCounter now working with emojis (16-bit code)

---

src/services/LogService.ts

Align LogService with console
Allow sending multiple params and allow (any) objects
Align LogService with console

Align LogService with console

---

ios/rnuilib.xcodeproj/project.pbxproj
package.json
src/style/typography.ts

Replacing 'react-native-text-size' with wix fork
DO NOT MERGE YET!!!
⚠️ Replacing 'react-native-text-size' with wix fork

Replacing 'react-native-text-size' with wix fork

---

src/components/sortableGridList/__tests__/usePresenter.spec.tsx

SortableGridList - add basic presenter tests 
WOAUILIB-2984
SortableGridList - add basic presenter tests

Infra/ SortableGridList tests

---

src/incubator/TextField/FloatingPlaceholder.tsx

TextField, FloatingPlaceHolder animation fixed.
TextField, FloatingPlaceHolder animation fixed, no overlapping on the initial text.

FloatingPlaceHolder animation fix

---

src/components/picker/types.tsx

Picker - fix listProps type to be Partial
Relates to WOAUILIB-3542
Picker - fix listProps type to be Partial

Picker - fix listProps type to be Partial

---

demo/src/screens/componentScreens/ModalScreen.tsx
src/components/modal/TopBar.tsx
src/components/modal/api/modalTopBar.api.json

Modal.TopBar - Support subtitle and subtitleStyle
WOAUILIB-3454
Modal.TopBar - Support subtitle and subtitleStyle

Feat/ Support subtitle in Modal.TopBar

---

src/components/colorPicker/ColorPickerDialog.tsx
src/incubator/Slider/index.tsx

Incubator.Slider - fix onValueChange throttle
ColorPicker - add 'migrate' prop to use new SliderImplementation
Incubator.Slider - fix onValueChange throttle
ColorPicker - add 'migrate' prop to use new SliderImplementation

Incubator.Slider - fix onValueChange throttle

---

src/components/wizard/WizardStep.tsx
src/components/wizard/index.tsx

`Wizard.Step` style fix according to the guidelines.
`Wizard.Step` style fix.

Fix the Wizard.Step style according to the guidelines

---

src/components/tabController/TabBarItem.tsx
src/components/tabController/apis/tabBarItem.api.json

Support passing labelProps to TabController item
TabController - Support passing labelProps to TabController TabBarItem

Support passing labelProps to TabController item

---

demo/src/screens/incubatorScreens/IncubatorSliderScreen.tsx
src/incubator/Slider/Thumb.tsx

Incubator.Slider - fix gap not equal on both max and min ends
Incubator.Slider - fix gap not equal on both max and min ends
WOAUILIB-3239

Incubator.Slider - fix gap not equal on both max and min ends

---

src/components/segmentedControl/index.tsx

SegmentedControl - onChangeIndex should react to changes
SegmentedControl - onChangeIndex should react to changes
None

SegmentedControl - onChangeIndex should react to changes

---

demo/src/screens/componentScreens/ColorPickerScreen.tsx
src/components/colorPicker/ColorPickerDialog.tsx
src/components/colorPicker/index.tsx

ColorPicker - small fixes
ColorPicker - small fixes
None

ColorPicker - small fixes

---

webDemo/package.json

webDemo project, `react-native-reanimated` version upgrade to `3.0.1`.
webDemo project, `react-native-reanimated` version upgrade.

webDemo reanimated version upgrade to 3

---

jestSetup/jest-setup.js
src/incubator/Slider/Slider.driver.ts
src/incubator/Slider/__tests__/index.spec.tsx
src/incubator/Slider/index.tsx
src/testkit/index.ts

Add Incubator.Slider driver
None
Related to WOAUILIB-2351

Add Incubator.Slider driver

---

src/components/numberInput/index.tsx

NumberInput - fix editable
NumberInput - fix editable
None

NumberInput - fix editable

---

webDemo/src/App.tsx
webDemo/src/examples/Picker.tsx

Picker example for the web demo.
Picker example for the web demo.

Picker example for the webDemo

---

demo/src/screens/componentScreens/NumberInputScreen.tsx
src/components/numberInput/index.tsx

NumberInput - support focus
None
WOAUILIB-3406

NumberInput - support focus

---

demo/src/screens/componentScreens/PickerScreen.tsx
src/components/picker/index.tsx
src/components/picker/types.tsx

Picker migrates Dialog to use the new dialog (Incubator.Dialog).
Picker migrates Dialog to use the new dialog (Incubator.Dialog).

Picker migrate Dialog

---

src/components/text/index.tsx

Text - revert Android alignment
Text - revert Android alignment
WOAUILIB-3703

Text - revert Android alignment

---

src/components/colorPicker/index.tsx

ColorPicker - allow theme
ColorPicker - allow theme
WOAUILIB-3659

ColorPicker - allow theme

---

src/components/slider/index.tsx

Slider - fix value out of range warning in range slider
Slider - fix value out of range warning in range slider
solves #2706 2706

Slider - fix value out of range warning in range slider

---

src/components/badge/index.tsx

Add key to BadgeProps 
Badge - add key to BadgeProps type
WOAUILIB-3689

Add key to BadgeProps

---

src/components/picker/index.tsx

Picker - fix ellipsis on long text in `filterType='filter'`, add `numberOfLines` to the text.
Picker - fix ellipsis on long text in filterType set to filter.

limit picker number of lines

---

src/components/picker/PickerItemsList.tsx

Bind Picker options list a testID - `${testID}.list`
Bind Picker options list a testID - `${testID}.list`

Picker modal list testID

---

demo/src/screens/componentScreens/ColorPickerScreen.tsx
src/components/index.js
src/index.ts

Expose ColorPickerDialog as a new component to allow the display of the picker in the dialog from a custom view
Expose ColorPickerDialog as a new component

New component - ColorPickerDialog

---

lib/components/DynamicFonts/FontDownloader.ts
lib/components/DynamicFonts/FontLoader.ts
lib/components/DynamicFonts/index.ts

`DynamicFonts` - add a way to delete fonts from disk
Move\add some debug logs
Rename `buildFontName` into `buildFontInput`
None
None

Add a way to delete fonts from disk

---

lib/components/index.ts

Export FontExtension
None
None

Export FontExtension

---

expoDemo/package.json

Fix dependencies of expo demo
fix #2295
Fix expo demo app

Fix dependencies of expo demo

---

src/style/colors.ts

Colors - generatePalette - fix for white color (the only color with lightness 100)
Colors - generatePalette - fix for white color

Colors - generatePalette - fix for white color

---

lib/components/DynamicFonts/PermissionsAcquirer.web.ts
lib/components/DynamicFonts/index.ts

DynamicFonts - fix error in web
DynamicFonts - fix error in web
Fixes #2788

DynamicFonts - fix error in web

---

src/components/checkbox/index.tsx

Checkbox - bind functions
Checkbox - bind functions
None

Checkbox - bind functions

---

src/incubator/toast/index.tsx

Changed order of the activeBackgroundColor so it can be overridden with the action props.
Toast - Changed action props order.

Toast customizations

---

demo/src/screens/__tests__/__snapshots__/AvatarScreen.spec.js.snap
src/commons/__tests__/modifiers.spec.js
src/commons/modifiers.ts
src/components/view/index.tsx

Added gap modifier to the modifiers options and enabled it in the view component.
View - Added new gap modifier.
WOAUILIB-3833

Added gap modifier to the view component

---

src/incubator/Dialog/index.tsx

Dialog - BG and overlay should not be static
Dialog - BG and overlay should not be static
None

Dialog - BG and overlay should not be static

---

demo/src/screens/componentScreens/TextFieldScreen.tsx
src/style/dividers.ts

Dividers - turn to getters. 
TextFiledScreen - fix titles' color
Dividers - turn to getters. 
TextFiledScreen - fix titles' color

Dividers - turn to getters. TextFiledScreen - fix titles color

---

src/components/tabController/TabBarItem.tsx

TabBarItem - support array styles
TabBarItem - support array styles
None

TabBarItem - support array styles

---

src/components/picker/PickerPresenter.ts

Picker - fix item with value 0 is not shown as selected
You can see this after the example in #2804 is merged
Picker - fix item with value 0 is not shown as selected
None

Picker - item with value 0 is not shown as selected

---

scripts/prReleaseNotes.js
scripts/prReleaseNotesCommon.js

Release notes - add tag prefix support
None
None

Release notes - add tag prefix support

---

demo/src/screens/incubatorScreens/IncubatorToastScreen.tsx
src/incubator/toast/index.tsx

Incubator.Toast - fix error on Android with no image
Incubator.Toast - fix error on Android with no image
None

Incubator.Toast - fix error on Android with no image

---

src/components/maskedInput/old.js

MaskedInput - remove TextField.extractOwnProps
MaskedInput - remove TextField.extractOwnProps
WOAUILIB-3860

MaskedInput - remove TextField.extractOwnProps

---

src/components/maskedInput/old.js
src/components/textFieldOld/index.tsx

Return old textfield for masked input until we migrate to the new MaskedInput completely 
Return old textfield for masked input until we migrate to the new MaskedInput completely

Return old textfield for masked input

---

src/components/modal/api/modal.api.json

fixed typo

---

src/components/gridListItem/index.tsx

Fix issue with destructing hitSlop from undefined
N/A

Fix issue with destructing hitSlop from undefined

---

src/components/textField/index.tsx

TextField - fix web flexness 2
Please verify this works for you
TextField - fix web flexness 2
WOAUILIB-3701

TextField - fix web flexness 2

---

scripts/prReleaseNotesCommon.js

Report error when failing parsing PRs
N/A

Report error when failing parsing PRs

---

src/style/__tests__/scheme.spec.js
src/style/colors.ts
src/style/scheme.ts

Scheme - add isDarkMode function
Scheme - add isDarkMode function

Scheme - add isDarkMode function

---

src/components/textField/index.tsx

Reverts wix/react-native-ui-lib#2830
Reverts wix/react-native-ui-lib#2830
WOAUILIB-3867

Revert - fix: [WOAUILIB-3867] TextField default value

---

src/style/__tests__/colors.spec.js
src/style/colors.ts

Colors - generatePalette - remove 9 increment
Colors - generatePalette - remove 9 increment

Colors - generatePalette - remove 9 increment

---

src/incubator/hooks/useHiddenLocation.web.ts

useHiddenLocation - support web
Main difference is in `getHiddenLocation`
useHiddenLocation - support web
WOAUILIB-3676

useHiddenLocation - support web

---

src/index.ts
src/typings/common.d.ts

Exposed ComponentStatics type. Change implementation to be a little more readable.
ComponentStatics - Added new to to extract statics from component.
None

ComponentStatics type expose

---

src/components/checkbox/Checkbox.driver.ts
src/components/checkbox/__tests__/index.spec.tsx
src/components/checkbox/index.tsx

Checkbox - refactor driver to use new implementation, add getLabel for label testing
Checkbox - refactor driver to use new implementation

Checkbox - refactor driver to use new implementation

---

lib/package.json

Update native version
None
None

Update native version

---

src/components/carousel/Carousel.driver.ts
src/components/hint/Hint.driver.ts
src/components/image/Image.driver.ts
src/components/picker/Picker.driver.ts
src/components/radioButton/RadioButton.driver.ts
src/components/radioGroup/RadioGroup.driver.ts
src/components/slider/slider.driver.ts
src/components/switch/switch.driver.ts
src/components/text/Text.driver.ts
src/incubator/Dialog/__tests__/index.spec.tsx
src/incubator/Slider/Slider.driver.ts
src/testkit/index.ts

TestKit.index - remove old and add new drivers
TestKit.index - remove old and add new drivers

TestKit.index - remove old and add new drivers

---

src/style/designTokens.ts
src/style/designTokensDM.ts

Add missing token - $outlineNeutralHeavy
None
WOAUILIB-3950

Add missing token - $outlineNeutralHeavy

---

src/testkit/index.ts

Export `WheelPicker` and `SectionWheelPicker` drivers

export wheel picker and section wheel picker drivers

---

src/incubator/TouchableOpacity.tsx

TouchableOpacity - adding nativeID prop
TouchableOpacity - adding nativeID prop

TouchableOpacity - adding nativeID prop

---

src/components/card/index.tsx
src/components/tabController/index.tsx
src/components/touchableOpacity/index.tsx
src/index.ts

Export TabControllerBarProps, fix type for Card.containerStyle, add 'nativeID' to TouchableOpacity
Export TabControllerBarProps, fix type for Card.containerStyle, add 'nativeID' to TouchableOpacity

Export TabControllerBarProps

---

src/components/radioButton/index.tsx

RadioButton - fix label margins
RadioButton - fix label margins

RadioButton - fix label margins

---

src/components/segmentedControl/index.tsx

SegmentedControl active index style fix
SegmentedControl active index style fix

fixed active index style for SegmentedControl

---

src/components/button/index.tsx

Button - link - adjust spacing
Button - link - adjust spacing
MADS-3960

Button - link - adjust spacing

---

src/components/button/index.tsx

Button - fix TS error
None
None

Button - fix TS error

---

src/components/colorPicker/ColorPickerPreview.tsx
src/components/slider/GradientSlider.tsx

Slider - pr comments fix
Slider - pr comments fix

Slider - pr comments fix

---

src/incubator/Slider/index.tsx
src/incubator/Slider/slider.api.json

Incubator.Slider - ad disabledThumbTineColor
Fix types declaretion
Add api file and fix old Slider's api
Incubator.Slider - ad disabledThumbTineColor

Incubator.Slider - ad disabledThumbTineColor

---

src/components/sortableList/index.tsx
src/components/sortableList/types.ts

Added ref prop to the SortableList that is passed to the FlatList.
SortableList - Added ref prop for the inner FlatList.
[MADS-3993](https://jira.wixpress.com/browse/MADS-3993)

SortableList ref prop

---

demo/src/screens/incubatorScreens/IncubatorExpandableOverlayScreen.tsx

ExpandableOverlayScreen - migrate to the new Dialog
None
MADS-3956

ExpandableOverlayScreen - migrate to the new Dialog

---

src/components/sectionsWheelPicker/sectionsWheelPicker.api.json

SectionWheelPicker - api fix
SectionWheelPicker - api fix

SectionWheelPicker - api fix

---

src/incubator/Slider/index.tsx

Incubator.Slider - add displayName
Incubator.Slider - add displayName

Incubator.Slider - add displayName

---

src/components/svgImage/index.web.tsx

div wasn't aligned on center, also svg path css wasn't it in the right location.
- set the svg path css in the right location
- set the div to center its content
Web `SvgImage` style fixes.
related to [JIRA](https://jira.wixpress.com/browse/MADS-4009)

fix: web svg icon path css and div alignment

---

src/components/textField/textField.api.json

TextField - fix api file
TextField - fix api file

TextField - fix api file

---

src/components/gradient/index.tsx
src/incubator/Slider/slider.api.json

Gradient - fix Android line spaces
Gradient - fix Android line spaces
ticket 3954

Gradient - fix Android line spaces

---

src/incubator/Slider/slider.api.json

Incubator.Slider - fix category
Incubator.Slider - fix category

Incubator.Slider - fix category

---

src/incubator/Slider/index.tsx

Incubator.Slider - fix track layout when values change
Incubator.Slider - fix track layout when values change
ticket 4047

Incubator.Slider - fix track layout when values change

---

src/components/icon/index.tsx

Icon - fix wrapper breaks alignment (center modifier)
Icon - fix wrapper breaks alignment (center modifier)
ticket 4049

Icon - fix wrapper breaks alignment (center modifier)

---

src/components/slider/GradientSlider.tsx
src/components/slider/context/asSliderGroupChild.tsx

GradientSlider - fix thumbTintColor override
GradientSlider - fix thumbTintColor override

GradientSlider - fix thumbTintColor override

---

src/style/colors.ts

Colors - generatePalette with addDarkestTints change to 9 step lightness increments
Colors - generatePalette with addDarkestTints change to 9 step lightness increments
ticket 3830

Colors - generatePalette with addDarkestTints change to 9 step lightness increments

---

src/components/WheelPicker/index.tsx

WheelPicker - memoize offsets
WheelPicker - memoize offsets

WheelPicker - memoize offsets

---

src/components/floatingButton/__tests__/index.spec.tsx

Removed getProps from FloatingButton tests.
None
None

removed getProps from FloatingButton tests

---

demo/src/screens/componentScreens/NumberInputScreen.tsx
src/components/numberInput/index.tsx

NumberInput - support maxLength
NumberInput - support maxLength
None

NumberInput - support maxLength

---

src/incubator/Slider/index.tsx

Incubator.Slider - fix 'value' updates.
When value updates the slider should update position.
Incubator.Slider - fix 'value' updates
ticket 4073

Incubator.Slider - fix 'value' updates

---

package.json
yarn.lock

Remove babel-preset-react-native
https://github.com/wix/react-native-ui-lib/security/dependabot/23
Remove babel-preset-react-native
None

Remove babel-preset-react-native

---

package.json
yarn.lock

Remove mocha
https://github.com/wix/react-native-ui-lib/security/dependabot/17
Remove mocha
None

Remove mocha

---

src/incubator/Dialog/index.tsx

Incubator.Dialog - change overlayBackgroundColor to grey10 with 65% opacity
Incubator.Dialog - change overlayBackgroundColor to grey10 with 65% opacity
Ticket 4103

Incubator.Dialog - change overlayBackgroundColor to grey10 with 65% opacity

---

package.json
yarn.lock

Remove gh-pages
https://github.com/wix/react-native-ui-lib/security/dependabot/14
Remove gh-pages
None

Remove gh-pages

---

src/components/textField/index.tsx
src/index.ts

export TextField validators
Export TextField validators for external use

chore: export text field validators

---

src/style/designTokens.ts
src/style/designTokensDM.ts

DesignTokens - add $outlineNeutral token
DesignTokens - add $outlineNeutral token
ticket #4168

DesignTokens - add $outlineNeutral token

---

lib/components/Keyboard/KeyboardTracking/keyboardAwareInsetsView.api.json
src/components/chipsInput/chipsInput.api.json
src/components/dash/dash.api.json
src/components/gradient/Gradient.api.json
src/components/textField/textField.api.json
src/incubator/Dialog/dialogHeader.api.json

add examples to api files
add examples to api files
AI KB

add examples to api files

---

demo/src/screens/componentScreens/TextFieldScreen.tsx

TextField screen - fixed types because of TS errors.
None
None

fixed types in the screen

---

demo/src/screens/componentScreens/SegmentedControlScreen.tsx
src/components/segmentedControl/segment.tsx
webDemo/src/App.tsx

SegmentedControl icon support in web.
SegmentedControl icon wrapper changed from `Reanimated.Image` to `AnimatedUIIcon`.
`AnimatedUIIcon` is animated version of Icon component, due issues to render the image in web environment. 
SegmentedControl icon support in web.
MADS - 4235

SegmentedControl icon wrapper component change

---

demo/src/screens/componentScreens/SegmentedControlScreen.tsx
src/components/segmentedControl/index.tsx
src/components/segmentedControl/useSegmentedControlPreset.ts

Fixed segments props to be mandatory
Added icons example.
SegmentedControl - Segments prop is now mandatory.
N/A

added example with icons. Changed segments props to be mandatory

---

src/testkit/index.ts

Exporting PickerDriver from testKit.
None
None

Exporting PickerDriver from testKit

---

src/components/picker/Picker.driver.new.ts

Picker driver support dialog dismiss functionality 
None
None

picker driver support dialog dismiss functionality

---

scripts/prReleaseNotesCommon.js

Release notes script - fix silent PRs
Silent PRs have higher priority than categories
None
None

Release notes script - fix silent PRs

---

src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/style/designTokens.ts
src/style/designTokensDM.ts

outlineDisabled token colors change.
outlineDisabled token colors change.
MADS - 4248

changed outline disabled color

---

src/components/picker/index.tsx

Set usePickerMigrationWarnings in comment
None
None

set usePickerMigrationWarnings in comment

---

src/components/textField/index.tsx

TextField - apply marginT only to the OUTLINE preset
TextField - apply marginT only to the OUTLINE preset
4272

TextField - apply marginT only to the OUTLINE preset

---

src/style/designTokens.ts
src/style/designTokensDM.ts

New design tokens: outlinePrimaryMedium | black | white
New design tokens: outlinePrimaryMedium | black | white
MADS-4254

New design tokens: outlinePrimaryMedium | black | white

---

demo/src/screens/componentScreens/TextFieldScreen.tsx
src/components/textField/index.tsx

TextField - fix centered with new topTrailingAccessory
TextField - fix centered with new topTrailingAccessory

TextField - fix centered with new topTrailingAccessory

---

demo/src/screens/foundationScreens/ColorsScreen.js

New `black` and `white` tokens added to the Colors screen.
None
None

added system category tokens

---

demo/src/screens/componentScreens/TextFieldScreen.tsx

TextField - screen for snapshot tests
TextField - screen for snapshot tests

TextField - screen for snapshot tests

---

demo/src/screens/componentScreens/TextFieldScreen.tsx

Reverts wix/react-native-ui-lib#3143

Revert "TextField - screen for snapshot tests"

---

src/components/picker/Picker.driver.new.ts
src/incubator/Dialog/Dialog.driver.new.ts
src/incubator/Dialog/__tests__/index.new.spec.tsx

Dialog.driver - improve API
Hopefully this is better :)
It'll require a (really) small change in private.
Dialog.driver - improve API
None

Dialog.driver - improve API

---

demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
src/components/textField/TextField.driver.new.ts

TextField - clearButton tests - fir snapshot and driver
TextField - clearButton tests - fir snapshot and driver

TextField - clearButton tests - fir snapshot and driver

---

README.md

Update README.md - add link to Figma library
Update README.md - add link to Figma library

Update README.md - add link to figma library

---

demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
src/components/button/__tests__/__snapshots__/index.spec.js.snap
src/components/icon/index.tsx

In our Icon component we didn't allow custom style passed by the user to override our default style
Allow icon custom style override defaults

Allow icon custom style override defaults

---

demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
src/components/textField/index.tsx

TextField - fix bottom part: validationMassage, bottomAccessory, helperText and charCounter
TextField - fix bottom part: validationMassage, bottomAccessory, helperText and charCounter

TextField - fix bottom part

---

demo/src/screens/componentScreens/PickerScreen.tsx
src/components/picker/helpers/useFieldType.tsx

Picker - remove colon from label on filter fieldType
Picker - remove colon from label on filter fieldType

Picker - remove colon from label on filter fieldType

---

src/components/dateTimePicker/index.tsx

Adding isValid to the DateTimePicker so it would work with the form.
DateTimePicker - isValid function added to ref interface.
MADS-4209
MADS-4210
MADS-4210

add is valid to datetimepicker

---

src/components/switch/index.tsx

Switch - change off color to $backgroundNeutralHeavy
Switch - change off color to $backgroundNeutralHeavy
Ticket 4040

Switch - change off color to $backgroundNeutralHeavy

---

demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
src/components/textField/__tests__/index.driver.spec.tsx
src/components/textField/index.tsx

TextField - add margin btw bottom elements and char counter, adding tests to validationMessage change
* Will need to update private snapshot tests after merge
TextField - add margin btw bottom elements and char counter, adding tests to validationMessage change

TextField - add margin btw bottom elements and char counter

---

docs/foundation/modifiers.md

fix(docs): broken links in docs

---

src/components/textField/ValidationMessage.tsx

TextField - show validation icon only with validation massage
TextField - show validation icon only with validation massage
ticket 4391

TextField - show validation icon only with validation massage

---

demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
demo/src/screens/componentScreens/TextFieldScreen.tsx

TextField screen - fix and improve and fix tests
TextField screen - fix and improve and fix tests
TextField screen - fix and improve and fix tests

TextField screen - fix 

---

lib/android/build.gradle
lib/android/src/main/AndroidManifest.xml

In order to upgrade to Gradle 8 (Part of RN73 upgrade) we need this change on Android.
Gradle 8 update.
N/A

infra: Gradle 8 changes

---

src/components/badge/index.tsx

Badge - fix labelStyle's type
Badge - fix labelStyle's type
Relates to 4110

Badge - fix labelStyle's type

---

src/components/colorSwatch/index.tsx

ColorSwatch - support theme and color modifiers
ColorSwatch - support theme and color modifiers
Ticket 4417

ColorSwatch - support theme and color modifiers

---

src/components/index.js
src/components/progressiveImage/index.tsx
src/index.ts

ProgressiveImage component export, reformat into `tsx` file.
ProgressiveImage component export
Issue #3172

export progressiveImage component

---

src/components/button/index.tsx

Button outlineWidth support zero value.
Button outlineWidth support zero value.
MADS-4432

outlineWidth support zero value

---

demo/src/screens/componentScreens/GridViewScreen.tsx
src/components/gridListItem/index.tsx

GridView - fix after gridListIItem change (https://github.com/wix/react-native-ui-lib/pull/3001)
Fix Image style override by `ImageProps`.
GridView - fix after gridListIItem change (https://github.com/wix/react-native-ui-lib/pull/3001)
None

fixed style override in grid list item image

---

src/components/button/Button.driver.new.ts

Button driver - getIconStyle, getLabelStyle functionality.
Button driver - getIconStyle, getLabelStyle functionality.
MADS-4410

button driver getIcon/Label styles

---

src/incubator/Slider/index.tsx

Update `_thumbStyle` shared value when `customThumbStyle` changes (when the user passes thumbStyle).
not only should defaultThumbStyle update.
Update style when user pass custom style. 
Issue #3198

update thumbStyle when tintColor changes

---

src/components/actionSheet/index.tsx

Fix: ActionSheet Styling to Dynamically Use DesignTokens Colors

---

src/components/picker/Picker.driver.new.ts

Picker driver - add exists
Picker driver - add exists
Relates to ticket 4414

Picker driver - add exists

---

.gitignore
scripts/prReleaseNotes.js
scripts/prReleaseNotesCommon.js

Release notes - remove the need for a token (use gh CLI)
None
None

Release notes - remove the need for a token (use gh CLI)

---

scripts/buildPackages/buildCustomPackages.js

Remove custom handling for text field package that lead to old TextFieldMigrator
Fix text field standalone package that leads to old TextFieldMigrator

Remove custom handling for text field package

---

src/components/slider/types.ts

Slider - add extra incubator slider props (enabled with migrate only)
Slider - add extra incubator slider props (enabled with migrate only)

Slider - add extra incubator slider props (enabled with migrate only)

---

lib/.npmignore
lib/package.json

uilib-native - add .npmignore
uilib-native - add .npmignore
None

uilib-native - add .npmignore

---

eslint-rules/lib/rules/no-direct-import.js
eslint-rules/package.json
eslint-rules/tests/lib/rules/no-direct-import.js

eslint - no-direct-imports - handle no arguments
None
None

eslint - no-direct-imports - handle no arguments

---

scripts/buildDocs.js
src/components/text/text.api.json

Docs - support tabs in component pages as a infra structure for new features
Docs - support tabs in component pages
ticket 4471

Docs - support tabs in component pages

---

src/components/gridList/useGridLayout.ts

SortableGridList - fix rounding issue that causes less items to be shown in each row
SortableGridList - fix number of columns in some iPads 
Ticket 3786

SortableGridList - fix rounding issue that causes less items to be shown in each row

---

docuilib/package.json

Fix deps and devDeps of docuilib package
N/A

Fix deps of docuilib package

---

docuilib/package.json
docuilib/src/index.ts

Docs - ReactLiveScope export.
Exporting the ReactLiveScope components for reuse in the private docs.
Docs - ReactLiveScope export.
None

react live scope components export

---

src/components/button/Button.driver.new.ts
src/components/button/__tests__/index.driver.spec.tsx

Button driver - add getStyle
Button driver - add getStyle
Button driver - add getStyle

Button driver - add getStyle

---

docuilib/package.json

uilib-docs 3.1.4 - new ColorsSection component.
None
None

uilib-docs 3.1.4

---

docuilib/package.json
docuilib/src/components/pageComponents/index.ts
docuilib/src/index.ts

Docs - Export Page Components and publish
None
None

Export Page Components and publish

---

scripts/buildPackages/buildCustomPackages.js

Incubator package - fix typings
Incubator package - fix typings
None

Incubator package - fix typings

---

docs/getting-started/usage.md

Fix TextField usage in Usage.md page
Fix TextField usage in Usage.md page

Fix TextField usage in Usage.md page

---

docuilib/src/components/pageComponents/SectionHeader.tsx

Adjust ratio in docs section between header and content

Adjust ratio in docs section between header and content

---

docuilib/src/components/CodeSection.module.scss
docuilib/src/components/ComponentPage.module.scss
docuilib/src/components/ComponentsSection.module.scss
docuilib/src/components/FeatureSection.module.scss
docuilib/src/components/LibrariesSection.module.scss
docuilib/src/components/MainSection.module.scss

Fix warnings about 'src/css/constants'
https://github.com/nolimits4web/swiper/issues/7771#issuecomment-2433515054
None
None

Fix warnings about 'src/css/constants'

---

docuilib/src/components/pageComponents/ContentItem.tsx
docuilib/src/components/pageComponents/SectionContent.tsx
docuilib/src/components/pageComponents/TableSection.tsx
src/components/test.api.json

I added a new content section type that renders a component.
The structure is
```
{
props: <props dictionary>,
component?: <component name>
}
```
if component is not passed then the component that this page is about is rendered. If its passed then the component passed is renderd.
N/A
N/A

New live component content item

---

docuilib/src/components/pageComponents/ContentItem.tsx

Fix how we detect figma embed links

Fix how we detect figma embed links

---

src/components/segmentedControl/index.tsx
src/components/segmentedControl/segmentedControl.api.json
src/components/segmentedControl/useSegmentedControlPreset.ts
src/index.ts

SegmentedControl - Added export of presets enum.
N/A

SegmentedControl - Added preset prop to api.json and export to SegmntedControlPresets

---

docuilib/package.json
docuilib/src/components/pageComponents/ContentItem.tsx

update prop value formatting in ContentItem component in case of string value

bump version to 3.3.3 and update prop value formatting in ContentItem component

---

docuilib/src/components/pageComponents/SectionContent.tsx
docuilib/src/components/pageComponents/TableSection.tsx
src/components/animatedScanner/animatedScanner.api.json
src/components/checkbox/checkbox.api.json
src/components/test.api.json
src/components/textField/textField.api.json

Docs: 
TableSection - flex table to page width.
Add support for section content background color
clean up api jsons
Docs - flex table to page width and support section content background
MADS-4550

Docs - flex table to page width + support content bg

---

src/components/slider/ColorSliderGroup.tsx
src/components/slider/types.ts

ColorPicker - reduce lag with Incubator.Slider
ColorPicker - reduce lag with Incubator.Slider
Ticket 4328

ColorPicker - reduce lag with Incubator.Slider

---

.github/workflows/deployDocs.yml

Added workflow that will deploy the docs on every push to master. There is no way to test this on the branch so we have to merge this and then see if it works...
N/A
N/A

Workflow - Deploy docs on master push

---

.github/workflows/deployDocs.yml

Fixed node version in the node-setup. correct parameter was node-version-file.
N/A
N/A

Fixed node-version in node setup

---

docuilib/package.json
docuilib/yarn.lock

Updated ui-lib version in docuilib package.
N/A
N/A

updated uilib version in docs

---

lib/package.json
tsconfig.build.json

uilib-native - fix types (for root - i.e. index.d.ts)
uilib-native - fix types (for root - i.e. index.d.ts)
None

uilib-native - fix types (for root - i.e. index.d.ts)

---

package.json
yarn.lock

Update uilib-native version
Update uilib-native version
None

Update uilib-native version

---

lib/package.json

uilib-native - fix react version
uilib-native - fix react version
None

uilib-native - fix react version

---

README.md

Update README with notes on React Native new architecture support
None
None

Update README with notes on React Native new architecture support

---

src/index.ts

Exported PieChartProps.
N/A
MADS-3418

Exported PieChartProps

---

android/app/src/main/java/com/rnuilib/MainApplication.kt

Android - fix entry point after change demo to index
Android - fix entry point after change demo to index
fix for PR https://github.com/wix/react-native-ui-lib/pull/3507

Android - fix entry point after change demo to index

---

demo/src/screens/componentScreens/ColorSwatchScreen.tsx
src/components/colorSwatch/index.tsx
src/style/colors.ts

ColorSwatch - fix accessibility
ColorSwatch - fix accessibility
ticket 4610

ColorSwatch - fix accessibility

---

demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
src/components/textField/index.tsx

Increased the hit slop of the text field.
TextField - Hit target increased
MADS-4597

TextField - Increase hitslop

---

demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
src/components/button/index.tsx

Fixed hit slop overriding passed hit slop.
Button - Fixed button no receiving passed hit slop
MADS-4591

Button Accessibility hit target - Fixed hit slop overriding.

---

src/components/hint/hint.api.json

Fix hint docs line breaks

---

docuilib/src/theme/ReactLiveScope/index.js

Add Timeline to ReactLiveScope for docs
NA

Add Timeline to ReactLiveScope for docs

---

docuilib/docusaurus.config.js
docuilib/src/components/MainSection.tsx

Changed View Docs entry
N/A
N/A

Docs - changed View Docs link

---

docuilib/package.json

bump docs version

---

docuilib/src/theme/ReactLiveScope/configurations.ts

Fix assets with default
None
None

Fix assets with default

---

docuilib/package.json
docuilib/src/components/pageComponents/ContentItem.tsx
docuilib/src/theme/ReactLiveScope/index.js
src/incubator/toast/toast.api.json

Added live preview of incubator toast. Local assets doesn't work.
N/A
N/A

Docs - Toast Live Preview

---

docuilib/docusaurus.config.js
docuilib/package.json
docuilib/src/components/MainSection.tsx

Fix for private so we don't have to set this up if its not needed.
N/A
N/A

Fix - Docs development entry

---

docuilib/package.json
docuilib/src/components/ComponentPage.tsx

Docs - fix deploy - not rendring Tabs with empty tabs array
Docs - fix deploy

Docs - fix deploy

---

src/components/checkbox/index.tsx

Checkbox - fix accessibility
Checkbox - fix accessibility

Checkbox - fix accessibility

---

docuilib/src/css/custom.css

Fix for a UX QA - Fix transition of navbar tabs
NA

Fix transition of navbar tabs

---

docuilib/package.json
docuilib/src/components/pageComponents/ContentItem.tsx
docuilib/src/utils/componentUtils.ts

Usage component support check to handle nested component names
N/A
N/A

Fix component support check to handle nested component names

---

ios/rnuilib.xcodeproj/project.pbxproj
package.json
yarn.lock

Upgrade Reanimated to version 3.16.7 to be aligned with the Engine
(I already QA reanimated components on real device) 
Upgrade Reanimated to version 3.16.7 in our demo app

Upgrade Reanimated to version 3.16.7

---

scripts/release/prReleaseNotesCommon.js

Release notes - change header to getHeader
None
None

Release notes - change header to getHeader

---

src/components/tabController/useScrollToItem.ts

TabController - tix RTL in Android
TabController - tix RTL in Android
PM

TabController - tix RTL in Android

---

src/incubator/index.ts

Exporting Incubator.SliderProps
N/A
N/A

Exported Incubator.SliderProps

---

src/components/picker/index.tsx

Picker - fix crash for children not in array
Picker - fix crash for children not in array

Picker - fix crash for children not in array

---

docuilib/package.json
docuilib/src/components/UILivePreview.module.scss
docuilib/src/components/UILivePreview.tsx

Refactor UILivePreview component to support code format
Refactor UILivePreview component to support code format
None

Refactor UILivePreview component to support code format

---

docuilib/package.json
docuilib/src/components/UILivePreview.tsx

Docs - Fix the Prettify button import error
Docs - Fix the Prettify button import error
None

Docs - Fix the Prettify button import error

---

demo/scripts/releaseDemo.js
docuilib/scripts/releaseDocs.js
eslint-rules/scripts/releaseEslint.js
lib/scripts/releaseNative.js
scripts/release/release.js

Move release checks into scripts
None
None

Move release checks into scripts

---

src/components/carousel/index.tsx

Fixed page control not aligned with scrolling direction in carousel.
Carousel - Fixed PageControl not aligned with scrolling direction in carousel.
MADS-4775

Carousel - Flip page control in rtl.

---

src/components/button/Button.driver.new.ts
src/components/button/__tests__/index.driver.spec.tsx

Added util for checking if the button is disabled.
ButtonDriver - added util for checking if the button is disabled.
N/A

ButtonDriver - add isDisabled 

---

src/style/borderRadiuses.ts

New Border Radius preset - br70.
New Border Radius preset - br70.
Ticket 4810

feat(borderRadiuses): add br70 radius value

---

package.json
yarn.lock

Update RN peer dependency to 0.77

chore(dependencies): update react-native peer dependency to 0.77.0
